cakephp/docs

en/views/helpers/form.rst
fr/views/helpers/form.rst

Update form helper template customization.

Use loadHelper() instead of $helpers array.

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

loadHelper() only exists in a View class. I've probably butchered the french changes :cry:

Fix incorrect docs for FormHelper

---

zh/contents.rst
zh/development/configuration.rst
zh/tutorials-and-examples.rst

also done /zh/tutorials-and-examples.rst

[zh_CN] done /zh/development/configuration.rst

---

en/orm/saving-data.rst
en/views/helpers/form.rst

I've added some examples for associated form inputs. I hope this covers #2179 and #1960

Add examples for associated form inputs

---

en/appendices/3-0-migration-guide.rst
en/contents.rst
en/core-libraries/text.rst
en/epub-contents.rst
en/pdf-contents.rst
en/views/helpers/text.rst
fr/appendices/3-0-migration-guide.rst
fr/contents.rst
fr/core-libraries/text.rst
fr/epub-contents.rst
fr/pdf-contents.rst
fr/views/helpers/text.rst

ref cakephp/cakephp#5550
If you agree with those change, I'd like to add the french version before it's being merged

3.0 rename String class to Text

---

en/core-libraries/collections.rst

Ref to #2210.
The output of list() was not correct in the docs.
I tried to use the function `listNested()` with examples from the doc and the api, but both don't give me the expected output. For instance, the api example is the following as described [here](http://api.cakephp.org/3.0/source-class-Cake.Collection.CollectionInterface.html#693-732):
$collection = new Collection([
['id' => 1, 'children' => [['id' => 2, 'children' => [['id' => 3]]]]],
['id' => 4, 'children' => [['id' => 5]]]
]);
$flattenedIds = $collection->listNested()->extract('id'); // Yields [1, 2, 3, 4, 5]
But my output is the following:
[
(int) 0 => (int) 5,
(int) 1 => (int) 4
]
Maybe I did not understand how this function works.

collection nest and listNested

---

en/appendices/2-7-migration-guide.rst

Docs for https://github.com/cakephp/cakephp/pull/5558

Docs for clear($renew)

---

en/appendices/3-0-migration-guide.rst

Docs for https://github.com/cakephp/cakephp/pull/5543

Docs for session::clear()

---

en/views/helpers/form.rst
es/core-libraries/helpers/form.rst
fr/views/helpers/form.rst
pt/views/helpers/form.rst

Replacing `$this->Form->unlockField('User.id');` with `$this->Form->unlockField('id');`

Fix error on how to use $this->Form->unlockField()

---

en/tutorials-and-examples.rst
en/tutorials-and-examples/blog/part-three.rst
en/tutorials-and-examples/blog/part-two.rst

Ref to #1322.
I tried to start a tuto about the TreeBehavior. I'm not fluent in english so you'll probably need to rephrase some sentences and my poor vocabulary causes redudant sentences. Sorry for that :)
As I needed to create some tables, I also added a small part that describes the basic steps of the migration Plugins.
So basically, It deals with 4 main ideas:
- Migrations plugin to create categories and articles table
- Generate the categories files with Bake plugin
- Print and reorder the categories with TreeBehavior
- Attach the CategoriesTable to ArticlesTable and insert article
This is just a draft so it needs lots of changes so I'm waiting for your comments and improvements :-)

first draft of tree tuto combined with migrations plugin

---

fr/orm/saving-data.rst

@antograssiot Please review this when you can

[fr] follow #2214 & translate en parts

---

en/tutorials-and-examples/blog/part-three.rst
fr/tutorials-and-examples.rst
fr/tutorials-and-examples/blog/part-three.rst
fr/tutorials-and-examples/blog/part-two.rst

@antograssiot and other french people, if you see changes, feel free to add commits or add comments

[fr] follow #2215

---

en/appendices/orm-migration.rst
en/orm/entities.rst
fr/appendices/orm-migration.rst
fr/orm/entities.rst

It was full of lies around validation changes. Refs cakephp/cakephp#5574 as well

Update ORM migration guide

---

fr/development/routing.rst

**Attention à ma question en ligne 302**

[fr] routing.rst quelques corrections

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst

We had some docs for methods that were removed :D

Removing references to the validate() and validateMany methods

---

fr/core-libraries/validation.rst

french people, waiting for your comments

[fr] translate en parts

---

fr/development/routing.rst

Some improvements to the section "Tour Rapide".
Especially change the sentence "Ceci ne va pas en revanche fonctionner pour les gens qui essaient d’accéder aux URLs ressemblant à /articles/foobar. Si vous le souhaitez, vous pouvez rechanger quelques paramètres pour vous conformer à une expression régulière:"

[fr] Update routing.rst

---

en/appendices/3-0-migration-guide.rst
en/orm/behaviors/counter-cache.rst
en/orm/behaviors/timestamp.rst
en/orm/behaviors/translate.rst
en/orm/behaviors/tree.rst
fr/orm/behaviors/counter-cache.rst
fr/orm/behaviors/timestamp.rst
fr/orm/behaviors/translate.rst
fr/orm/behaviors/tree.rst

follow cakephp/cakephp#5528 and ref cakephp/cakephp#5600

3.0 orm namespace

---

fr/appendices/orm-migration.rst
fr/orm/query-builder.rst

@antograssiot another one to review when you can.
Je trouve ça pas mal d'avoir la version anglaise déjà intégrée. Ca serait pas mal d'intégrer à chaque fois la version anglaise dans les fichiers fr quand il y a des modifs sur des fichiers en.

[fr] follow #2228

---

en/development/routing.rst

$this replaced with  $routes in equivalent for Calling fallbacks

$this replaced with  $routes in equivalent for Calling fallbacks

---

fr/orm/database-basics.rst

Replacing `connection`by `connexion`, excepted in source code blocks

[fr] Update database-basics.rst

---

en/appendices/3-0-migration-guide.rst
en/development/configuration.rst
en/views/helpers/form.rst
fr/appendices/3-0-migration-guide.rst
fr/development/configuration.rst
fr/views/helpers/form.rst

3.0 config

---

en/development/dispatch-filters.rst

Maybe the wording needs adjusting, "higher" could also mean the opposite in semantic meaning.
The higher the number, .. ?

Note about order.

---

en/orm/retrieving-data-and-resultsets.rst

Update docs for streaming results improvements.

---

en/debug-kit.rst
fr/debug-kit.rst
fr/development/debugging.rst
fr/development/dispatch-filters.rst
fr/orm/retrieving-data-and-resultsets.rst
fr/orm/table-objects.rst

#2262, #2261, #2248, #2260, #2259
@antograssiot Please review this and merge when you can :)

[fr] follow all recent en parts

---

en/orm/query-builder.rst
fr/orm/query-builder.rst

Add docs for (right|inner|left)Join.

---

en/tutorials-and-examples/blog/part-three.rst

Fix that and i have rewrite layout for fit Bake code auto generate

Wrong write function move up and move down in

---

en/appendices/3-0-migration-guide.rst
en/development/configuration.rst
fr/appendices/3-0-migration-guide.rst
fr/development/configuration.rst

Add info regarding php config file change.

---

fr/controllers.rst
fr/controllers/components.rst
fr/controllers/components/pagination.rst
fr/orm/retrieving-data-and-resultsets.rst
fr/plugins.rst

@cake17 une partie du #2260 a été oubliée apparement.

[fr] 3.0- missing modification

---

en/development/sessions.rst

[en] Including Session config acceptable values.

---

en/development/sessions.rst
fr/development/sessions.rst

Added docs to remove inexistent configuration values and to clarify the confusion brought in https://github.com/cakephp/cakephp/issues/5664

Improved session docs to clarify cookie lifetime and timeouts

---

en/debug-kit.rst
fr/debug-kit.rst
pt/debug-kit.rst

@lorenzo  this modification should allow to get back to the "normal" pdf-content.rst

3.0 exclude gif file from pdf build

---

en/orm/behaviors/translate.rst
es/core-libraries/behaviors/translate.rst
fr/orm/behaviors/translate.rst
pt/orm/behaviors/translate.rst

It now needs to contain a table class name. Fixes #2266

Correct translationTable.

---

ja/controllers.rst

The $file paramter of the render function does not already exist.

Remove the $file parameter from the render function

---

ja/controllers.rst

updated Controller::render() info

updated Controller::render() info

---

en/orm/query-builder.rst
es/orm/query-builder.rst
fr/orm/query-builder.rst
pt/orm/query-builder.rst

Remove query argument as it was inconsistently passed.

---

en/orm/database-basics.rst
en/orm/query-builder.rst
en/orm/retrieving-data-and-resultsets.rst
es/orm/database-basics.rst
es/orm/query-builder.rst
fr/orm/database-basics.rst
fr/orm/query-builder.rst
fr/orm/retrieving-data-and-resultsets.rst
pt/orm/database-basics.rst
pt/orm/query-builder.rst

I went for MySQL, SQLite, PostgreSQL and SQLServer but I'm still open to modify it...

3.0 unify database driver naming

---

en/core-libraries/components/authentication.rst

Don't pass (unhashed) passwords when manually passing data into Auth->login($data);

Security Note When Manually Passing Data to Login

---

en/core-libraries/time.rst
en/orm/database-basics.rst

Add localized datetime parsing docs.

---

en/orm/saving-data.rst
en/orm/table-objects.rst
fr/orm/saving-data.rst
fr/orm/table-objects.rst

Related to cakephp/cakephp#5704

Add documentation for beforeMarshal event.

---

en/core-libraries/time.rst
en/development/sessions.rst
fr/core-libraries/time.rst
fr/development/sessions.rst
fr/orm/database-basics.rst
fr/orm/saving-data.rst
fr/orm/table-objects.rst

@antograssiot and french, I'm waiting for your reviews :)
Quelques termes que je n'ai pas su traduire : marshalling, cast. Je les rajoute dans le lexique : https://github.com/cakephp-fr/docs-cakephp/wiki/Lexique-de-traduction-des-termes-techniques

3.0 fr follow

---

fr/appendices/3-0-migration-guide.rst
fr/development/sessions.rst
fr/development/testing.rst
fr/orm/database-basics.rst
fr/orm/saving-data.rst
fr/orm/table-objects.rst

mostly on ORM. 
@cake17 I also included some modificatino related to you last PR

[fr] set of correction

---

en/development/testing.rst

adding Articles table to the table test and correcting class name as conventions.
(both are improvements that come from baking a table test)

testing.rst

---

en/tutorials-and-examples/blog-auth-example/auth.rst

According to the flow of document, Authentication Layer was missing in the above code.

Upadate auth.rst

---

en/installation.rst
fr/installation.rst

Summarize all comments made in #1687 to explain how to install php extensions in xampp and wamp installations

add a note about php extensions installation on XAMPP and WAMP

---

en/core-libraries/validation.rst

Add quick example of using uploadedFile rule.

---

fr/views/helpers/form.rst

Oui "loadHelper" n'est pas une méthode de "Controller"

[fr] fix commentaire form.rst

---

en/core-libraries/validation.rst

The current example is a little confusing as it stand with only one argument although below explanation talk about two

Update closure validation example

---

en/tutorials-and-examples/bookmarks/part-two.rst

Text above the example code talked about authentication and the proceeded to configure authorization, this confuses the two and needed fixing.

change unauthorizedRedirect to loginAction AuthComponent options in /en/tutorials-and-examples/bookmarks/part-two.rst

---

en/orm/saving-data.rst

Documentation for https://github.com/cakephp/cakephp/pull/5724

Documentation for disabling existing check

---

en/orm/table-objects.rst
fr/development/errors.rst
fr/orm.rst
fr/orm/entities.rst
fr/orm/saving-data.rst
fr/orm/table-objects.rst

part two of french ORM docs review.

[fr] translation review

---

en/intro/conventions.rst

As the Bookmarker is the first tutorial listed in the Tutorial section of the book, it seems to make morse sense for this to the one suggested here.

Updated the suggested primary tutorial to Bookmarker

---

en/core-libraries/logging.rst

Cliche and honestly the world of AJAX, SOAP, etc is here already.

In a world .... replaced

---

en/views/helpers/form.rst

Clarify the submit() docs.

---

en/core-libraries/inflector.rst
es/core-utility-libraries/inflector.rst
pt/core-libraries/inflector.rst

Sorry for all the commits - just quickly did in browser.

Fix spelling mistake.

---

en/development/routing.rst

Better grammar

---

en/orm/saving-data.rst

Convert existing examples to use marshalling methods. This makes the docs better match what people will do in the real world.
Refs cakephp/cakephp#5808

Add docs for saving joint table data from request data.

---

en/appendices/orm-migration.rst
en/orm/saving-data.rst
fr/appendices/orm-migration.rst
fr/orm/saving-data.rst

Update docs regarding naming of application rules.

---

en/appendices/2-7-migration-guide.rst

Add info about TreeBehavior::getLevel() to migration guide.

---

en/development/dispatch-filters.rst

There is no Cache dispatcher anymore. But a LocaleSelector one.
Also added a plugin example and a note about prios.

Upgrade dispatcher docs.

---

en/views/helpers/rss.rst

Rename page RSS to RssHelper

---

en/contributing/documentation.rst

I failed on this myself, so it might help others, too.

Make it clearer how to add links in RST

---

en/tutorials-and-examples/bookmarks/intro.rst

Probably that's a leftover from an earlier version.

Remove invalid placeholder

---

en/controllers/components/flash.rst

Note about FlashComponent::__call() plugin param

---

en/orm/saving-data.rst

Add note about existsIn().

---

fr/orm/saving-data.rst

Traduction de ma tentative d'explication de l'option accessibleFields.
Voir pull request doc Anglaise.

[fr] update saving-data.rst

---

en/orm/saving-data.rst
es/orm/table-objects.rst
fr/orm/saving-data.rst
pt/orm/saving-data.rst

Not sure about how translations are handled by now, so I've updated all occurrences.

Update note regarding `isNew()` check.

---

en/development/exceptions.rst
en/development/testing.rst

- en/development/testing.rst
- en/development/exceptions.rst

[en] correct origianl text

---

ja/tutorials-and-examples/blog-auth-example/auth.rst

replace SimplePasswordHasher into BlowfishPasswordHasher

use BlowfishPasswordHasher

---

en/development/testing.rst

looks like ComponentCollection is no longer used, instead the used class is ComponentRegistry.

updating component test

---

en/controllers/request-response.rst

an Authenticated user normally has the session data under Auth.

request session user info through Auth

---

en/installation.rst

https://github.com/cakephp/docs/issues/2385

Branch tag is not clear enough

---

fr/appendices/orm-migration.rst
fr/orm/query-builder.rst
fr/orm/retrieving-data-and-resultsets.rst

@cake17 Es-tu d'accord avec ces modif ?

[fr] typos

---

en/contributing/documentation.rst
fr/contributing/documentation.rst

add a link to jenkins server to check docs build.

3.0 continous integration note

---

en/contributing/documentation.rst
fr/contributing/documentation.rst

draft linked to #1152 after @bcrowe proposal

usage of backticks draft

---

en/orm/query-builder.rst
fr/orm/query-builder.rst

Following a discussion on cakephp/cakephp#5870 with @markstory, I think this should be put somewhere in the doc.
If adding this is okay and the location is accepted, I'll take care of the French version (and other versions that are in English) before this is merged.

Defining joins conditions when the quoteIdentifiers option is set to true

---

en/development/testing.rst
en/orm/associations.rst
fr/development/testing.rst
fr/orm/associations.rst

Update docs for cakephp/cakephp#5601 and #2358. If there is more to do for #2358 I'm happy to do that too.

Update docs for associations and plugin testing

---

en/appendices/2-7-migration-guide.rst
en/core-libraries/components/flash.rst
en/core-libraries/components/sessions.rst
en/core-libraries/helpers/flash.rst
en/core-libraries/helpers/session.rst
en/core-libraries/toc-components.rst
en/core-libraries/toc-helpers.rst
fr/appendices/2-7-migration-guide.rst
fr/core-libraries/components/flash.rst
fr/core-libraries/components/sessions.rst
fr/core-libraries/helpers/flash.rst
fr/core-libraries/helpers/session.rst
fr/core-libraries/toc-components.rst
fr/core-libraries/toc-helpers.rst

Related to cakephp/cakephp#5823

Backport docs for Flash Helper/Component.

---

en/core-libraries/components/flash.rst
en/core-libraries/helpers/flash.rst

Replacing short arrays by long arrays

---

README.mdown

[3.0] Adding sphinx alert

---

README.mdown

Fixing sphinx alert

---

en/installation.rst
en/tutorials-and-examples/bookmarks/intro.rst
en/tutorials-and-examples/bookmarks/part-two.rst

Refs https://github.com/cakephp/docs/issues/1152

3.0 - Start cleaning up markup

---

es/tutorials-and-examples/blog/part-two.rst

Changed translate of "save"

---

fr/core-libraries/helpers/form.rst

Correction d'une faute de conjugaison

---

en/views/helpers/flash.rst

See https://github.com/cakephp/cakephp/pull/5936

Document that the FlashHelper obeys themes

---

en/orm/saving-data.rst
fr/orm/saving-data.rst

Not sure if using english terms is correct for the french translation, I just followed the description for the `propertyName` option in the [associations section](http://book.cakephp.org/3.0/fr/orm/associations.html).

3.0 - Correct association property conventions

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

Might be helpful for people suffering from reading aversion...

3.0 - Connect form field naming convention sections

---

en/development/rest.rst
en/development/routing.rst
fr/development/rest.rst
fr/development/routing.rst

Add documentation for additional resource methods.

---

en/orm/behaviors/translate.rst

Related to https://github.com/cakephp/cakephp/pull/5983

Document allow empty translations

---

config/cakei18n.py
themes/cakephp/layout.html

fix for issue [#2463](https://github.com/cakephp/docs/issues/2463)

[zh_CN] fix the URL for "Improve this Doc" button

---

en/orm/table-objects.rst

Add info about afterSaveCommit and afterDeleteCommit

---

en/development/routing.rst

Inconsistency in description and example

Update REST routes

---

en/core-libraries/form.rst

Added new section: Invalidating Individual Form Fields from Controller .
It will guide newbies who have a situation where they have to manually invalidate form fields without the use of validator class due to circumstances. The section is inline with the flow of the existing tutorial.

Added new section

---

fr/core-libraries/collections.rst

if french language people want to read and add comments for changes, please don't hesitate

[fr] start collections file

---

en/tutorials-and-examples/blog-auth-example/auth.rst
en/tutorials-and-examples/bookmarks/intro.rst

Codesniffer will complain if use classes are not in alphabetical order. (I know youre also not including documentation, but this is no additional code required)

Reorders Use classes in Docs

---

en/orm/saving-data.rst

Add note about dirty() to saving docs.

---

en/controllers.rst

Added missing colon in Configure singleton call.

Fixed typo

---

pt/core-utility-libraries/file-folder.rst

I really like this Folder and File's utilities, and i always open the documentation (because i never remember the methods) and ever appears the same pt page without a translated documentation, it's make me sad, but now, after long a half hour of hard work, i translated this page for us.
I think it's will help a lot of brazilian guys, i'll work to increase this documentation in the future, this utility is really good.
tnx for all!

Added Folder & Files documentation in pt-br lang

---

en/core-libraries/form.rst
fr/core-libraries/collections.rst
fr/core-libraries/form.rst
fr/views/helpers/form.rst

Finish french translation of modelless Form documentation

3.0 [fr] modeless form

---

en/core-libraries/email.rst

should be: Cake\Network\Email\Email instea of Cake\NetworkEmail\Email

Update missing \ charactor

---

en/appendices/3-0-migration-guide.rst
en/appendices/orm-migration.rst
en/controllers/components/authentication.rst
en/controllers/components/cookie.rst
en/controllers/components/csrf.rst
en/core-libraries/caching.rst
en/core-libraries/collections.rst
en/core-libraries/events.rst
en/core-libraries/registry-objects.rst
en/core-libraries/security.rst
en/core-libraries/validation.rst
en/debug-kit.rst
en/development/routing.rst
en/development/testing.rst
en/orm/behaviors.rst
en/orm/behaviors/translate.rst
en/orm/database-basics.rst
en/orm/query-builder.rst
en/orm/retrieving-data-and-resultsets.rst
en/orm/saving-data.rst
en/orm/table-objects.rst
en/tutorials-and-examples/blog/part-three.rst
en/tutorials-and-examples/blog/part-two.rst
en/views/helpers.rst
en/views/helpers/form.rst
ja/controllers/components/authentication.rst
ja/core-libraries/events.rst

My last branch blew up and it closed the PR. :cry:

3.0 - Add '()' to method highlights

---

en/orm/database-basics.rst

Fixes broken example caused by changes in cakephp/cakephp@7468434ec14432c38562e0fa882b1c443e389787

Add missing marshal method to JsonType.

---

en/core-libraries/hash.rst
fr/core-libraries/hash.rst

Don't reference find() as find() and Hash aren't best buds anymore.
Refs #2498

Update Hash examples

---

themes/cakephp/static/cake.css
themes/cakephp/static/default.css

Refs https://github.com/cakephp/docs/pull/2503
Preview:

3.0 - Docs font

---

fr/appendices/3-0-migration-guide.rst
fr/console-and-shells.rst
fr/contributing/cakephp-coding-conventions.rst
fr/controllers/components.rst
fr/controllers/components/request-handling.rst
fr/core-libraries/hash.rst
fr/core-libraries/validation.rst
fr/development/configuration.rst
fr/development/dispatch-filters.rst
fr/development/routing.rst
fr/development/testing.rst
fr/installation.rst
fr/orm/behaviors.rst
fr/orm/entities.rst
fr/views.rst

finish translation and correct several typos + follow #2509

[fr] 3.0 dispatcher filters

---

en/tutorials-and-examples/blog/part-two.rst
fr/tutorials-and-examples/blog/part-two.rst

This is an example of a filename with a wrong name, so ArticleTable is a good misspelling example I guess ?

reverse bdadeea

---

fr/migrations.rst

Because Migrations is awesome, i translated this doc in french.

[FR] Update migrations.rst

---

en/console-and-shells.rst
en/console-and-shells/repl.rst
en/orm/behaviors/tree.rst
en/tutorials-and-examples/blog/blog.rst
en/tutorials-and-examples/bookmarks/intro.rst
es/console-and-shells.rst
es/tutorials-and-examples/blog/blog.rst
fr/console-and-shells.rst
fr/console-and-shells/repl.rst
fr/orm/behaviors/tree.rst
fr/tutorials-and-examples/blog/blog.rst
fr/tutorials-and-examples/bookmarks/intro.rst
ja/console-and-shells.rst
pt/console-and-shells.rst
pt/tutorials-and-examples/bookmarks/intro.rst
zh/console-and-shells.rst

- remove some more `-s dev` in `composer create-project ...`
- include the plugin-shell in the toc
- update REPL chapter
- fix code block in treeBehabior + french translation update/correction

3.0 several updates

---

en/views/helpers/form.rst

Also gave another example for select with multiple attribute set to true, how to pre-determined the selected options.
See http://stackoverflow.com/a/28992285/80353 for the comments about how the Cookbook is outdated.

Correct the word selected to value

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

Update documentation for form validation methods.

---

config/all.py
themes/cakephp/layout.html

and update config to show the correct copyright year

3.0 remove prev/next links

---

en/plugins.rst
fr/plugins.rst

Add more detail about how plugin AppControllers work and that they are optional.
Refs #2539

Expand documentation on plugin controller.

---

en/core-libraries/helpers/form.rst
fr/core-libraries/helpers/form.rst

Follow up on https://github.com/cakephp/docs/commit/3b92238ebfd5105a71c18b81d80595f5721b3346

Remove deprecation

---

en/core-libraries/internationalization-and-localization.rst
en/development/testing.rst
fr/core-libraries/internationalization-and-localization.rst
fr/development/testing.rst

* cakephp/cakephp#6163
* #2543

Update docs for testing and i18n.

---

en/contributing/documentation.rst
fr/contributing/documentation.rst

They are missing from the documentation.
What should I do about other languages ? Include the content in English ? Is there anyone to ping for these languages ?
When this is merged, I can take care of the 3.0 branch. (I'll wait to see if I didn't speak some bad English...)

Add notes about "versionadded" and "deprecated" admonitions

---

en/tutorials-and-examples/blog-auth-example/auth.rst

Changes deprecated add and edit functions from blog auth examples

Updated Auth Example of Tutorials

---

en/contributing/documentation.rst
fr/contributing/documentation.rst

Follow #2558 for the 3.0 branch.

3.0 - Add notes about "versionadded" and "deprecated" admonitions

---

en/controllers/request-response.rst

Some Model names have been updated like Article to Articles.. etc

Updated to avoid confusion of model Names & Others

---

en/core-libraries/behaviors/containable.rst

Fixed a small grammar correction in the second paragraph.

Grammar Correction

---

en/index.rst
es/index.rst
fr/index.rst
ja/index.rst
pt/index.rst
themes/cakephp/layout.html
tr/index.rst
zh/index.rst

Make it a more subtle warning on each translation's home page instead of a warning on every page.
Refs #2544

Update version banner.

---

en/development/routing.rst
fr/development/routing.rst

@cake17 J'ai continué la traduction du routing.

3.0 - [fr] routing

---

en/contributing/documentation.rst

Refers https://github.com/cakephp/docs/pull/2550#issuecomment-87630425
The list of "must haves" starting at https://github.com/cakephp/docs/pull/2573/files#diff-57c701e2395aec4004ed8a648c52070fR35 is probably different for 2.x, though.

Backporting changes to the doc contribution page

---

Makefile

follow #2575 | add -n to cp to avoid overwrites

---

en/views/helpers/form.rst

Add info about custom form group templates

---

en/appendices.rst
en/appendices/3-1-migration-guide.rst
en/controllers/components/flash.rst
en/views/helpers/flash.rst
es/appendices.rst
es/appendices/3-1-migration-guide.rst
fr/appendices.rst
fr/appendices/3-1-migration-guide.rst
fr/controllers/components/flash.rst
fr/views/helpers/flash.rst
ja/appendices.rst
ja/appendices/3-1-migration-guide.rst
pt/appendices.rst
pt/appendices/3-1-migration-guide.rst
zh/appendices.rst
zh/appendices/3-1-migration-guide.rst

Document the addition of the append behavior of the Flash messages.
Ref cakephp/cakephp#6161

3.1 - Multiple Flash messages

---

en/tutorials-and-examples/bookmarks/part-two.rst

This is the correct code and matches the edit() function documentation below it.

moved assignment of user_id below patchEntity() in add() method

---

en/views.rst
en/views/helpers/flash.rst
fr/views.rst
fr/views/helpers/flash.rst

Follow changes made to cakephp/cakephp#6233

3.0 - Prefix elements paths

---

en/bake.rst

Add section reminding people to install bake.

---

en/views/helpers/flash.rst
fr/bake.rst
fr/tutorials-and-examples/bookmarks/part-two.rst
fr/views/helpers/flash.rst
pt/tutorials-and-examples/bookmarks/part-two.rst

add french translation, correct build warnings, update Portuguese code sample

follow last updates

---

en/tutorials-and-examples/blog/part-two.rst
es/tutorials-and-examples/blog/part-two.rst
fr/tutorials-and-examples/blog/part-two.rst

get() already contains the 404 exception

Clean up tutorial code.

---

en/orm/saving-data.rst

Document how hasMany works with _ids.
Refs #2593

Update documentation for hasMany with _ids.

---

en/development/routing.rst

They were a bit wrong before this.
Refs #1364

Update requestAction docs.

---

en/appendices/3-1-migration-guide.rst

Refs https://github.com/cakephp/cakephp/pull/6264#event-275573208

Docs for Session helper deprecation.

---

en/orm/saving-data.rst
fr/orm/saving-data.rst

Add some headings as the section was becoming a wall of text.

Document mixed belongsToMany format.

---

config/all.py
zh/conf.py
zh/contents.rst
zh/contributing.rst
zh/contributing/cakephp-coding-conventions.rst
zh/contributing/code.rst
zh/contributing/documentation.rst
zh/contributing/tickets.rst
zh/controllers.rst
zh/controllers/components.rst
zh/controllers/pages-controller.rst
zh/controllers/request-response.rst
zh/epub-contents.rst
zh/index.rst
zh/installation.rst
zh/tutorials-and-examples/blog/blog.rst
zh/tutorials-and-examples/blog/part-two.rst
zh/views.rst
zh/views/helpers.rst
zh/views/themes.rst

change all refs to zh_CN to zh

---

en/orm/database-basics.rst

Following the pattern that other documents have for exposing the most important aspects of the chapter contents

Adding a quick tour section to Database Basics

---

en/core-libraries/internationalization-and-localization.rst

Add more complete docs for locale selector.

---

en/orm/entities.rst
en/orm/retrieving-data-and-resultsets.rst
en/orm/saving-data.rst

Improved the entities chapter and added a Quick Tour for the Saving data chapter

3.0 improve orm docs

---

en/orm/retrieving-data-and-resultsets.rst

Add example for find(list) with joinable associations.

---

en/orm/retrieving-data-and-resultsets.rst

3.0 update find list code example for joinable table

---

en/orm/saving-data.rst

The patchEntity() method does not support accsesibleFields.

---

ja/controllers/request-response.rst

Following current en document.

[ja] Update request-response.rst

---

en/orm/retrieving-data-and-resultsets.rst
fr/orm/retrieving-data-and-resultsets.rst

cherry picked commit from 3.1 branch

Correct NS for RecordNotFoundException

---

en/migrations.rst
fr/migrations.rst

Add documentation for the new `migrations mark_migrated` command
Closes #2646

Add documentation for the new `migrations mark_migrated` command

---

en/orm/saving-data.rst

Clarify docs around isUnique() rules.

---

en/appendices/3-0-migration-guide.rst

Correct docs for https://github.com/cakephp/docs/pull/2604

Fix docs for Session helper deprecation.

---

en/console-and-shells.rst

Refs https://github.com/cakephp/cakephp/pull/6399

Remove underline from red text

---

fr/core-libraries/caching.rst

1 faute et correction de formulation

[fr] Update caching.rst

---

en/orm/saving-data.rst
fr/orm/saving-data.rst

Add example of custom error message and closure rule.

Add docs for validation.

---

en/contributing/cakephp-coding-conventions.rst
fr/contributing/cakephp-coding-conventions.rst

3.0 correct naming convention

---

en/debug-kit.rst
fr/debug-kit.rst
pt/debug-kit.rst

Follows https://github.com/cakephp/debug_kit/pull/329

Use --dev option for installing Debug Kit

---

en/development/sessions.rst

`* -` produces two bullet points.

Fix bullet list

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

BelongsToMany select boxes were not well documented before.
Refs #2661

Add documentation on how to generate selects.

---

en/appendices/2-6-migration-guide.rst
en/views/json-and-xml-views.rst

Docs for https://github.com/cakephp/cakephp/pull/6466 and https://github.com/cakephp/cakephp/pull/6453

Docs for _xmlOptions and _jsonOptions

---

en/controllers/pages-controller.rst

Searching through the documentation for the generated "home.ctp" file will now list this page and therefore makes it easier to get the relation to PagesController.

Added home.ctp name

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

Expand docs to include long form radio buttons.

---

en/development/routing.rst
fr/development/routing.rst

Document how Router::addUrlFilter() works.

---

en/appendices/3-1-migration-guide.rst
en/views/json-and-xml-views.rst
fr/appendices/3-1-migration-guide.rst
fr/views/json-and-xml-views.rst

Add info about new serialization feature

---

en/appendices/3-0-migration-guide.rst
en/views/json-and-xml-views.rst

Docs for https://github.com/cakephp/cakephp/pull/6452

Docs for xmlOptions

---

en/orm.rst
en/orm/saving-data.rst
en/orm/validation.rst
fr/orm.rst
fr/orm/saving-data.rst
fr/orm/validation.rst

Create a separate chapter for the validation docs. I've also included the application rules sections as I feel they are part of validation.
Is there anything else that should be in this chapter that is currently missing?

Separate validation

---

en/orm/retrieving-data-and-resultsets.rst
fr/orm/retrieving-data-and-resultsets.rst

improvement over https://github.com/cakephp/docs/pull/2711 and https://github.com/cakephp/docs/pull/2710

Documenting the select and subquery strategy

---

zh/development/debugging.rst

[zh_CN] correct code block

---

en/appendices/3-1-migration-guide.rst
en/development/routing.rst
en/plugins.rst

Follows https://github.com/cakephp/app/pull/245

Use DashedRoute for examples, fix typo

---

fr/development/routing.rst

update the name controller "recipes" ==> "Recipes"

update the name controller

---

pt/tutorials-and-examples/blog/blog.rst

This is my translation of Blog Tutorial - CakePHP 3.0 from English to Portuguese (Brazil).
I hope it helps!
Anyway, congratulations by your framework. It helps me a lot :)
Att. Vinícius Luiz

Translate of blog.rst to pt_BR

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst

Add documentation for nested validators.

---

en/core-utility-libraries/file-folder.rst
fr/core-utility-libraries/file-folder.rst
ja/core-utility-libraries/file-folder.rst
pt/core-utility-libraries/file-folder.rst

This is a follow up to [PR #6545 for cakephp/cakephp](https://github.com/cakephp/cakephp/pull/6545) to add the option that was added in the PR.
I added the option to every language available but only added a comment to the english version since I don't speak the others.

add recursive option to folder API

---

en/orm/behaviors/tree.rst
fr/orm/behaviors/tree.rst

Add docs for treeList options.

---

en/development/rest.rst
fr/development/rest.rst

Follows and correct  34f269c09a8c04968281863f988b0c5e822e5c2c and #2740 for xml template path.

3.0 Update xml template path

---

en/orm/entities.rst

Small correction as those dont have to be "fields". So "properties" it is.

Correct typo.

---

en/appendices/2-7-migration-guide.rst
en/models/data-validation.rst
en/tutorials-and-examples/blog-auth-example/auth.rst
en/tutorials-and-examples/blog/part-two.rst

Docs for https://github.com/cakephp/cakephp/pull/6579

Deprecate notEmpty in favor of notBlank

---

en/debug-kit.rst
fr/debug-kit.rst

Documentation for custom panels in DebugKit is off

---

en/core-libraries/email.rst

using this https://support.google.com/a/answer/176600?hl=en as reference

change port for smtp.gmail.com using tls

---

zh/core-libraries.rst
zh/core-libraries/toc-components.rst
zh/core-libraries/toc-general-purpose.rst
zh/core-libraries/toc-utilities.rst

- zh/core-libraries.rst
- zh/core-libraries/toc-components.rst
- zh/core-libraries/toc-general-purpose.rst
- zh/core-libraries/toc-utilities.rst

[zh_CN] zh/core-libraries: index/toc pages done

---

en/orm/retrieving-data-and-resultsets.rst
fr/orm/retrieving-data-and-resultsets.rst

It isn't always clear that the collection methods are on ResultSet. Give examples of methods people will commonly want.

Add additional examples for first/last and take.

---

en/core-libraries/httpclient.rst

Updated Http Client documentation to reflect changes made in #6550.

Updated Http Client documentation to reflect changes made in #6550

---

fr/core-libraries/collections.rst

J'ai toujours un peu de mal avec la traduction de Closure...

[fr] collections.rst: Traduction d'un paragraphe

---

en/appendices/3-1-migration-guide.rst
en/console-and-shells.rst
en/console-and-shells/helpers.rst
fr/appendices.rst
fr/appendices/3-1-migration-guide.rst
fr/console-and-shells.rst
fr/console-and-shells/helpers.rst

Add the docs for the recent shell helper additions.

Add Docs for Shell Helpers

---

en/appendices/glossary.rst
en/console-and-shells.rst
en/console-and-shells/completion-shell.rst
en/console-and-shells/plugin-shell.rst
en/core-libraries/httpclient.rst
en/core-libraries/logging.rst
en/installation.rst
en/orm/associations.rst
en/orm/behaviors/tree.rst
en/orm/retrieving-data-and-resultsets.rst
fr/console-and-shells.rst
fr/controllers/components/authentication.rst
fr/core-libraries/collections.rst
fr/core-libraries/httpclient.rst
fr/core-libraries/inflector.rst
fr/orm/associations.rst
fr/orm/behaviors/counter-cache.rst
fr/orm/behaviors/timestamp.rst
fr/orm/behaviors/tree.rst
fr/orm/retrieving-data-and-resultsets.rst
pt/console-and-shells.rst

Merge 3.0 -> 3.1 & refs https://github.com/cakephp/docs/pull/2784#issuecomment-107083914

Add routes shell to example.

---

en/core-libraries/internationalization-and-localization.rst

internationalization - fix Bad Apostrophe

---

en/orm.rst

Unnecessary Comma

---

en/controllers/components/authentication.rst

Minor grammer modifications. Added semi-colons, removed  unnecessary commas, and also added commas where needed. Consistent use of the Oxford comma.

Grammer Modifications

---

en/core-libraries/email.rst

Matches the format used in the rest of this document.

Updates $Email to $email

---

en/orm/query-builder.rst

Updated QueryExpression examples
* added additional examples for `addCase` to explicity show to get an `if..then..else` and a nested `if..then..elseif..then..else`
* added code snippets for each of the conditional expression functions

added query expression examples

---

en/bake/usage.rst
fr/bake/usage.rst

Add `form` option for https://github.com/cakephp/bake/pull/103.

Add form option to bake usage.

---

en/console-and-shells.rst

[en] fix console-and-shells.rst

---

en/appendices/orm-migration.rst
en/orm/retrieving-data-and-resultsets.rst

Add more information on how to handle magic finders.

---

en/appendices/3-1-migration-guide.rst
en/controllers/components/authentication.rst

Refs: https://github.com/cakephp/cakephp/pull/6664

Add info about new auth storage class usage.

---

en/core-libraries/collections.rst
fr/core-libraries/collections.rst

Add documentation for TreeIterator::printer().

---

en/core-libraries/text.rst
fr/core-libraries/text.rst

documentation for cakephp/cakephp#6728

add documentation for wordWrap()

---

en/bake.rst

Fetch stable release instead of dev-master

---

en/views/helpers/form.rst

Added a missing comma into Widget example.

Added missing comma into widget example

---

en/core-libraries/httpclient.rst
en/development/routing.rst
fr/core-libraries/httpclient.rst
fr/development/routing.rst

* Add docs example on how to use OAuth2 tokens
* Attempt to address some of the issues raised in #2838

Http\Client & Router docs improvements

---

en/development/dispatch-filters.rst

Refs https://github.com/cakephp/cakephp/issues/6314

Adding a note about cacheTime for AssetFilter

---

en/console-and-shells.rst
en/tutorials-and-examples/bookmarks/intro.rst
fr/console-and-shells.rst
fr/tutorials-and-examples/bookmarks/intro.rst

Add docs for shell aliasing and try to clarify some of the gaps pointed out in #2847.

Add docs for shell aliasing & clarifications

---

en/The-Manual/Core-Utility-Libraries/Router.rst

I've dug up some bug in docs while trying to fix one of my ancient projects :)

1.3 - Fixed a link to routes config

---

en/orm/saving-data.rst

Apologies if I am just misunderstanding something.

I believe this was a typo

---

en/orm/validation.rst
fr/orm/validation.rst

Add info about changing default validator class.

---

en/core-libraries/collections.rst

Example inspired by my questions in google groups:
https://groups.google.com/forum/?hl=es#!topic/cake-php/IVSn_1GpoAI 
https://groups.google.com/forum/?hl=es#!topic/cake-php/zUwDGhkMFO4

Added closure example to combine

---

en/console-and-shells/cron-jobs.rst

comment out  an explaining line of cronjob.

fix cron-jobs.rst

---

en/orm/database-basics.rst
fr/orm/database-basics.rst

Add section for supported databases.

---

en/appendices/3-1-migration-guide.rst
en/development/routing.rst
fr/development/routing.rst

Add documentation for _namePrefix option.

---

en/appendices/3-1-migration-guide.rst
en/core-libraries/email.rst
fr/appendices/3-1-migration-guide.rst
fr/core-libraries/email.rst

Refs https://github.com/cakephp/cakephp/pull/6324

3.1 - Add Mailer docs.

---

en/development/configuration.rst
fr/development/configuration.rst

The FR version might need some additional tweaking, as my french is rather bad.

3.0 - Fix app paths configuration.

---

en/appendices/2-7-migration-guide.rst
en/core-libraries/behaviors/tree.rst

Beginning of docs for https://github.com/cakephp/cakephp/pull/6704
Feel free to adjust

Docs for formatTreeList().

---

pt/installation.rst

There was an extra line written in english in the middle of the pt-br content.

Removed an extra line with previous english content

---

en/orm/query-builder.rst
fr/orm/query-builder.rst

I think that this sentence needs to be inverted.
It makes more sense with the following example and also seems to be like this in the [source code](https://github.com/cakephp/cakephp/blob/master/src/Database/Expression/CaseExpression.php#L67)

3.0 correction on addCase function

---

fr/orm/database-basics.rst
fr/orm/query-builder.rst

Corrects 2 typos ("[...] les serveurs [...] suivants") and a wrong translation.

Corrects typos & sentences in French

---

en/core-libraries/internationalization-and-localization.rst
en/tutorials-and-examples/blog/part-three.rst
fr/core-libraries/internationalization-and-localization.rst
fr/tutorials-and-examples/blog/part-three.rst

Update blog and i18n docs

---

en/appendices/3-1-migration-guide.rst
en/orm/query-builder.rst
en/orm/retrieving-data-and-resultsets.rst
fr/appendices/3-1-migration-guide.rst
fr/orm/query-builder.rst
fr/orm/retrieving-data-and-resultsets.rst

Documented notMatching, leftJoinWith, innerJoinWith and select($tableInstance)

3.1 new query features

---

en/controllers.rst
en/tutorials-and-examples/bookmarks/part-two.rst
en/views/helpers.rst
fr/tutorials-and-examples/bookmarks/part-two.rst

Fixes up the docs for:
* #2883
* #2884

Update docs for helpers and bookmarker tutorial

---

en/views/helpers/form.rst
fr/views/helpers/form.rst

Fix missing parameter.

---

en/bake/development.rst
en/bake/usage.rst
en/orm/entities.rst
fr/bake/development.rst
fr/bake/usage.rst
fr/orm/entities.rst

Update docs for:
* #2890
* cakephp/cakephp#6856

Bake & entity documentation updates

---

fr/core-libraries/validation.rst

L'unicité doit être controllée par une règle d'application.
https://github.com/cakephp/cakephp/issues/6865#issuecomment-114560047

[fr] update validation.rst

---

en/contributing/documentation.rst
fr/contributing/documentation.rst

change files to translate for 2.x

---

en/core-libraries/email.rst

Namespace definition is needed when creating custom transports

Adding namespace definition

---

fr/development/routing.rst
fr/orm/database-basics.rst
fr/orm/deleting-data.rst
fr/orm/saving-data.rst
fr/orm/validation.rst
fr/views/helpers.rst

mostly translation for recent validation changes

3.0 [fr] more missing translation

---

en/contents.rst
en/elasticsearch.rst

This is by no means an exhaustive reference for the elasticsearch plugin. However, its a start and is enough to make me comfortable in doing an alpha release of the plugin.

Start Documentation Elasticsearch

---

en/tutorials-and-examples/bookmarks/intro.rst

Attempt to add some clarity to the bookmarker tutorial.

---

pt/index.rst

Translation of version warning.

Tradução do aviso sobre a versão.

---

en/tutorials-and-examples/blog/part-three.rst
en/tutorials-and-examples/blog/part-two.rst

Add more detail and information to blog tutorial.

---

en/tutorials-and-examples/bookmarks/intro.rst

Further clarifications to the bookmark tutorial.

---

en/contents.rst
en/upgrade-tool.rst

Add some installation/usage documentation for the upgrade tool based on the feedback in cakephp/upgrade#86

Upgrade tool

---

fr/appendices/3-0-migration-guide.rst
fr/bake.rst
fr/development/debugging.rst
fr/development/routing.rst
fr/tutorials-and-examples/blog/part-three.rst
fr/tutorials-and-examples/blog/part-two.rst
fr/tutorials-and-examples/bookmarks/intro.rst

Follow #2927, #2928, #2933, #2934, #2930, #2931, #2938, #2937 to keep in sync.

[fr] Follows recent changes and fixes

---

fr/contents.rst
fr/controllers.rst
fr/core-libraries/collections.rst
fr/core-libraries/inflector.rst
fr/development/routing.rst
fr/upgrade-tool.rst

follows #2929 and add some missing translation.

[fr] missing translation

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst

- Revert #2923 for the French translation
- Add a note about what is in $context['data']
More details on #2923 (see the comments)

Revert a commit and add a clarification

---

en/views/json-and-xml-views.rst

It  was messing around in articles and posts - should only be posts :-)

Corrected code example in views/json and xml views

---

en/views/json-and-xml-views.rst

To follow cake 3 conventions :-)
Since posts generally have been switched to articles - it's followed here too :smile: 
refs #2962 and finishes that up

Changed from posts to articles

---

ja/intro/cakephp-folder-structure.rst

This is first PR and several part of this doc still remain English sentense. So I'm going to do PR for additional translation.

Add Japanese version of cakephp-folder-structure.rst

---

en/intro/conventions.rst

Since there is just a little note in http://book.cakephp.org/3.0/en/orm/database-basics.html#data-types

3.0 - Adding a note about uuid primary key

---

en/appendices/3-1-migration-guide.rst
en/development/debugging.rst
en/orm/retrieving-data-and-resultsets.rst
fr/appendices/3-1-migration-guide.rst
fr/development/debugging.rst
fr/orm/retrieving-data-and-resultsets.rst

See cakephp/cakephp#7055 and #2944

3.1 Document late eager associations and breakpoint()

---

ja/tutorials-and-examples/bookmarks/intro.rst

@suzuki found some of Sphinx syntax miss.

first 1 page all translation mended syntax error

---

en/orm/entities.rst

For me,  can not identify single means with "over". I imaged, short circuit  it completely or through  it without customize  or with customize.

"over" is ambiguous

---

ja/intro/conventions.rst

Almost copied from 2.0 lang=ja

full page translation conventions

---

en/core-libraries/httpclient.rst

Add docs for building form data objects by hand.

---

ja/views/helpers/url.rst

translation 3.0/ja/views/helpers/url

---

en/development/errors.rst
en/tutorials-and-examples/blog-auth-example/auth.rst
fr/development/errors.rst
fr/tutorials-and-examples/blog-auth-example/auth.rst

Remove redundant code.

---

en/intro.rst

use 1st meaning in google mouse over dictionary.

fix idioms to simple words

---

en/tutorials-and-examples/blog-auth-example/auth.rst

Protect "id" field against mass assignment.

Don't promote bad practice

---

ja/intro/where-to-get-help.rst

provide en original for compare to Japanese then translate

1st full translation where-to-get-help.

---

ja/controllers/components/pagination.rst

Sorry, my file seemed to be in the wrong directory. Please merge my commit again

file directory modified

---

en/appendices/3-1-migration-guide.rst
en/orm/query-builder.rst
fr/appendices/3-1-migration-guide.rst
fr/orm/query-builder.rst

Add additional information on unsafe query usage.
Refs cakephp/cakephp#7157

SQL safety

---

en/orm/query-builder.rst
fr/orm/query-builder.rst

Add more explicit docs to expression and function docs.

---

en/development/routing.rst

end up with is idiom.
It is difficult to search in mouse-over dictionary.

change idiom to single word

---

en/controllers/components/authentication.rst

Add example for using "finder" in authenticator config.

---

en/migrations.rst
fr/migrations.rst

I'll take care of the French version once the english one is considered good.

Document the new Migrations class

---

en/core-libraries/email.rst
fr/core-libraries/email.rst

Someone on IRC found the previous example confusing.

Improve example.

---

en/controllers/request-response.rst
en/orm/retrieving-data-and-resultsets.rst
fr/controllers/request-response.rst
fr/orm/retrieving-data-and-resultsets.rst

Add docs to cover what I took away from #2966 and #2468

Cover 2966 & 2468

---

en/controllers/request-response.rst

Namespace needs to be specified to access XML class

Namespace required

---

en/core-libraries/email.rst
fr/core-libraries/email.rst

Add a version added admonition for the Mailers feature

---

en/orm/query-builder.rst

Add docs for orderDesc/orderAsc.

---

ja/controllers/components/pagination.rst

Some words were not highlighted in ``...``. Also, some few other minor amendments in Japanese wording.

modified text

---

en/controllers/request-response.rst
en/core-libraries/hash.rst
fr/controllers/request-response.rst
fr/core-libraries/hash.rst

and better highlight variables names in Hash docs

remove ref to Cakeresponse

---

fr/core-libraries/httpclient.rst

Turned out I couldn't just restore and push there @antograssiot - so those are the changes I still had in mind for it. Feel free to close or merge.

Tiny additional fixes to FR typo fixes

---

en/development/testing.rst

followup to #3098

---

en/appendices/3-1-migration-guide.rst
en/controllers.rst
en/views.rst
en/views/helpers.rst
en/views/themes.rst
fr/appendices/3-1-migration-guide.rst
fr/controllers.rst
fr/views.rst
fr/views/helpers.rst
fr/views/themes.rst

Add docs for the new ViewBuilder that was recently merged.

3.1 viewbuilder

---

en/orm/database-basics.rst

Not sure about the MariaDB note (in general, whats the stance - what if people are looking for it?)

Add meta keywords to database basics doc

---

en/controllers/components/authentication.rst

I was setting up digest authentication to test an issue and found the
docs lacking. This fixes the issues that I ran into.

Improve documentation for Basic/Digest authentication.

---

en/appendices/3-1-migration-guide.rst
en/views.rst

Related to cakephp/cakephp#7237

Add deprecation notices.

---

en/tutorials-and-examples/blog/part-three.rst
fr/tutorials-and-examples/blog/part-three.rst

This PR reorganizes blog tuto 3 #3107.
Also a fix for one part of #3123.
Let me know if this needs corrections.
It remains an issue with the categories index.

reorganize tuto3, refs #3107 & #3123

---

en/tutorials-and-examples/blog/part-three.rst
fr/tutorials-and-examples/blog/part-three.rst

Fix incorrect input name.

---

en/appendices/3-1-migration-guide.rst
fr/appendices/3-1-migration-guide.rst

Add info regarding change to Auth.redirect setting.

---

en/contributing/cakephp-coding-conventions.rst

Fixed typo ending DocBlock

---

pt/models/additional-methods-and-properties.rst

Almost finished the traduction of the page, just leave some of technical terms that is hard to translate in that context.

Added traduction for pt-br of the additional-methods-and-properties page

---

en/controllers/request-response.rst

http://api.cakephp.org/2.7/class-RequestHandlerComponent.html#_isPost

Fix outdated statement

---

en/appendices/3-1-migration-guide.rst
en/core-libraries/email.rst

Add info about auto use of default email profile.

---

en/appendices/2-8-migration-guide.rst
en/core-utility-libraries/time.rst

Add notes about changes in CakeTime::listTimezones()

---

en/core-utility-libraries/email.rst

Further explain the difference between ssl sockets and tls delivery.

---

en/console-and-shells.rst

Is this useful to be added?
Refs https://github.com/cakephp/cakephp/pull/7304

note about the convenience wrappers.

---

en/core-libraries/email.rst

Update Mailer usage examples.

---

fr/console-and-shells.rst
fr/core-libraries/email.rst
fr/tutorials-and-examples/blog-auth-example/auth.rst
fr/tutorials-and-examples/blog/part-two.rst

@antograssiot I'm sure I missed some of the last changes

[fr] #3186, #3184, #3182, #3178

---

ja/installation.rst

I translated ja: installation.rst.

Translate 'installation'

---

en/migrations.rst

[en] underscore_form note in migrations

---

fr/orm/retrieving-data-and-resultsets.rst

@antograssiot @HavokInspiration one more file started
I'll do the rest later but don't hesitate if you want to continue :smile:

[fr] start translation of retrieving

---

fr/appendices/3-0-migration-guide.rst
fr/appendices/3-1-migration-guide.rst
fr/controllers/components/authentication.rst
fr/controllers/components/request-handling.rst
fr/controllers/components/security.rst
fr/core-libraries/events.rst
fr/core-libraries/httpclient.rst
fr/development/sessions.rst
fr/orm/entities.rst
fr/orm/query-builder.rst
fr/orm/saving-data.rst
fr/orm/validation.rst
fr/tutorials-and-examples/blog/part-two.rst
fr/views/helpers.rst
fr/views/helpers/form.rst
fr/views/helpers/url.rst

3.0 fr last changes

---

en/core-libraries/number.rst

Refs https://github.com/cakephp/cakephp/pull/7339

Add ordinal method to Number doc

---

en/development/errors.rst
fr/development/errors.rst

fix wrong namespace

---

en/core-libraries/number.rst

Add docs for Number::config()

---

en/development/sessions.rst

Ref: https://github.com/cakephp/cakephp/issues/7352

Array syntax to write session data

---

en/core-libraries/number.rst

Refs https://github.com/cakephp/cakephp/pull/7350

Update ordinal method signature, add locale setting example

---

en/migrations.rst
fr/migrations.rst

To be merged when the PR https://github.com/cakephp/migrations/pull/116 is merged

Add notes about the new way to deal with primary key introduced in the migrations plugin

---

en/console-and-shells.rst
en/console-and-shells/plugin-shell.rst
en/contributing/cakephp-coding-conventions.rst
en/core-libraries/caching.rst
en/core-libraries/email.rst
en/core-libraries/internationalization-and-localization.rst
en/core-libraries/logging.rst
en/debug-kit.rst
en/development/testing.rst
en/intro.rst
en/plugins.rst
en/tutorials-and-examples/blog-auth-example/auth.rst
en/tutorials-and-examples/blog/part-two.rst
en/tutorials-and-examples/bookmarks/intro.rst
en/views.rst
en/views/cells.rst
en/views/helpers/flash.rst
en/views/helpers/paginator.rst
en/views/helpers/rss.rst

Fix formatting for file highlighting

---

en/models/saving-your-data.rst

Add docs explaining how datetimes and fieldList interact.

---

en/controllers.rst

Unless I have something terribly wrong, the `if` conditional shouldn't have a negation (`!`).

Fixed opposite logic

---

fr/appendices/3-1-migration-guide.rst
fr/controllers.rst
fr/orm/saving-data.rst
fr/views/json-and-xml-views.rst
pt/controllers.rst

- follows #3245 for fr & pt
- follows #3236 & #3241 for fr

[fr] [pt] follows #3245

---

ja/core-libraries/helpers/html.rst

Following #3234 and fixing $options parameter.

[ja] follow #3234 and fix

---

ja/development/testing.rst

Fix installation command

---

en/intro/conventions.rst
fr/intro/conventions.rst
ja/intro/conventions.rst
pt/intro/conventions.rst

I wasn't sure of the routes conventions for long names and found the info [here](http://sandbox3.dereuromark.de/pages/best-practices).
Please feel free to change the sentence if it's not correct in english.

[all lang] add a note for router name conventions

---

ja/plugins.rst

[ja] translate from en 3.0

---

en/development/routing.rst

A couple edits for URL inflection section

---

en/views/helpers/form.rst

Add classname/custom attributes examples to datetime

---

en/orm/behaviors/tree.rst

This is the documentation for the the following pull request: cakephp/cakephp#7411
Note: This pull request is not accepted yet, so the documentation is not relevant yet.

Add documentation for the TreeBehavior recoverOrder

---

en/core-libraries/internationalization-and-localization.rst

Fix locales _

---

en/tutorials-and-examples/blog-auth-example/auth.rst
en/tutorials-and-examples/blog/part-two.rst

As of 2.7.0 we recommend using the FlashHelper/Component - update the docs to reflect this.
Refs #3293

Stop using SessionHelper/Component.

---

ja/migrations.rst

[ja] translated migrations.rst

[ja] translate migrations.rst from en 3.0 (based on Sep 5, 2015 version)

---

en/appendices/orm-migration.rst
en/core-libraries/collections.rst
en/orm/query-builder.rst
en/orm/retrieving-data-and-resultsets.rst

Try to make collection title accessible/readable from the search

Collection title

---

en/appendices/3-1-migration-guide.rst
en/console-and-shells.rst

Add docs for console logging changes.

---

en/orm/behaviors/translate.rst

Add additional context and real-world methods for examples in TranslateBehavior tests.
Refs #3288

Add more context for Translate examples.

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst

Couldn't update the JA docs, somehow GIT was messing up the encoding.

Add docs for `requirePresence()` callable support.

---

fr/views/helpers/form.rst

[fr] html helper

---

en/migrations.rst
fr/migrations.rst

To be merged when https://github.com/cakephp/migrations/pull/125 will be merged.

New `all` special value added to version argument of the `mark_migrated` command

---

ja/tutorials-and-examples/blog-auth-example/auth.rst

[ja] Update validation rule

---

en/core-libraries/global-constants-and-functions.rst

Revert "Adds CONFIG constant"

---

.travis.yml

If the HTML doesn't build something is very wrong with a pull request. We could also look for new warnings, but that is a bit more advanced.
I figured this could at least be a starting place for getting some automated checks on documentation submissions.

Add a very basic build process.

---

.gitignore

Improve .gitignore to exclude various files

---

.travis.yml

after discussions in #3366, add 2 changes in travis.yml:
- install : pip install -r requirements.txt, all dependancies are et can be changed in requirements.txt
- script: make html SPHINXOPTS="-W",  meaning the warnings are changed into errors.

change install & script in travis yml

---

en/controllers/components/pagination.rst

Add information on paginating query objects.

---

en/core-libraries/global-constants-and-functions.rst

Second attempt (follow up to #3353 and #3354)

Adds CONFIG constant

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst
ja/core-libraries/validation.rst

Hopefully this is easier to find. If not, we can consider adding a big list of links.
Refs #3373

Add additional link to Validation API docs.

---

en/core-libraries/logging.rst

Follow up of https://github.com/cakephp/cakephp/pull/7539

Added note about disabling rotate by setting size to false

---

fr/bake/development.rst

replace vendor/cakephp/cakephp/src/Template/Bake/Template/ by vendor/cakephp/bake/src/Template/Bake/Template

update path of the template

---

en/models/associations-linking-models-together.rst

Hello guys, I had this issue and need to search inside the source code to discover what happened with my relations that I created on the fly.
I hope that this information will help some people.
Thanks!

Added example of bind model with __backAssociation

---

en/controllers/components/authentication.rst

Correct API docs for basic auth.

---

ja/controllers/pages-controller.rst

Hi from TOKYO.
How are you? I'm fine.
now i finished translating. this page is very easy to Japanese.
because it's similar CakePHP2. Thanks for passed translation man.
Take care and see you at Germany, CakeFest.
Bye.

finished translating pages controller

---

en/views/helpers/html.rst

Better explain how to capture, output inline and output buffered scripts.
Refs #7576

Make docs for script blocks more explicit.

---

Dockerfile
README.mdown

2.x dockerfile

---

en/core-utility-libraries/app.rst

Plus make all plural to be consistent

Add two example for loading console classes

---

README.mdown

rearange readme for docker use

---

en/migrations.rst

"config/Migration directory" should say "config/MigrationS directory"

Corrected typo

---

en/development/configuration.rst
fr/development/configuration.rst

Fix true setting description for asset timestamps

---

fr/development/testing.rst

[fr] Follows #3452

---

en/views/helpers/html.rst

Add docs for how to make <link> tags.

---

en/console-and-shells.rst
es/console-and-shells.rst
fr/console-and-shells.rst
ja/console-and-shells.rst
ja/contributing/code.rst
ja/core-libraries/behaviors/translate.rst
ja/development/configuration.rst
ja/development/dispatch-filters.rst
ja/development/routing.rst
pt/console-and-shells.rst
pt/core-utility-libraries/file-folder.rst
pt/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
zh/console-and-shells.rst

same as PR #3464 made for branch 3.0

new title for console-and-shells file

---

en/core-libraries/internationalization-and-localization.rst
fr/core-libraries/internationalization-and-localization.rst

add info about cake.po

---

en/views/json-and-xml-views.rst

Clarify the automatic _serialize addition.

---

en/bake/development.rst

Updated description for theme options to no longer use the term default, as it isn't actually changing the defaults.
Added section for customizing bake templates.

Updated Bake Templates Section

---

Dockerfile

after reading [Docker best practices](http://docs.docker.com/engine/articles/dockerfile_best-practices/)

COPY instead of ADD, clean after install

---

en/views/themes.rst

Add plugin override example.

---

en/core-libraries/logging.rst

Added some missing words, fixed some typos and fixed some grammatical errors.

Fixed typos and grammatical errors

---

ja/core-libraries/xml.rst

I begin to translate the file.
ja/core-libraries/xml.rst

[WIP] translating ja/core-libraries/xml.rst

---

ja/development/debugging.rst

[ja] translate debugging.rst

---

en/core-libraries/hash.rst

Fix Hash::insert variable name

---

ja/core-libraries/hash.rst

[ja] translate hash.rst

---

en/core-libraries/text.rst

Fix Text::truncate() $options

---

en/development/configuration.rst

Document issues with SQLServer.

---

en/orm/saving-data.rst
fr/orm/saving-data.rst

This should help people trying to understand beforeMarshal

Clarifications about beforeMarshal

---

ja/tutorials-and-examples/bookmarks/part-two.rst

[ja] Translate ja/tutorials-and-examples/bookmarks/part-two.rst

---

en/controllers/components/authentication.rst

Update code examples for stateless authenticators

---

en/controllers/components/csrf.rst
en/controllers/components/security.rst

In addition to these libraries, people should be checking HTTP methods.

Include caveats related to HTTP method checking.

---

en/plugins.rst

Refs cakephp/cakephp#7757, , https://github.com/cakephp/bake/commit/bef3c061bb9b805124d8c2d016c148bfa77a0ae5

Fix plugin route.

---

en/views/helpers/form.rst

Fix spelling error "wiget"

---

en/bake/development.rst

Add section on file-specific bake events

---

ja/core-libraries/registry-objects.rst

I begin to translate the file.
ja/core-libraries/registry-objects.rst

translating ja/core-libraries/registry-objects.rst

---

en/installation.rst

"Traffic lights" is unclear as it's a reference to the home page styling in previous versions of CakePHP.

Clarify what is displayed in the browser when an app is first launched.

---

en/orm/database-basics.rst

Added info for a connection object from DSN string without selecting a database, so we can create/modify databases.
I can't seem to format the file correctly with GitHub file editor (sorry about that).

Connection without database

---

en/installation.rst

It's a bit of a pain in the a*** as we have to keep it updated, but fixes #3546

Clone 2.7 branch

---

en/orm/entities.rst

Delete ',' in the last element of a array.

Delete ',' in the last element of a array

---

en/orm/table-objects.rst

Entity -> EntityInterface for some Callbacks

3.1 Updates

---

en/core-libraries/helpers/form.rst

While a bit quirky, its worked that way for years, and changing it now would cause more problems.
Refs cakephp/cakephp#7829

Document GET form behavior.

---

en/controllers/components/authentication.rst
fr/controllers/components/authentication.rst

Ref https://github.com/cakephp/cakephp/issues/7852#issuecomment-164811052

[EN][FR] Added a note about getting a configuration value with `$this->Auth->config()`

---

es/appendices/3-1-migration-guide.rst

Translation to spanish of 3-1-migration-guide.rst
Traducción al español de 3-1-migration-guide.rst

[ES] 3.1 Migration guide

---

en/controllers/components/authentication.rst
fr/controllers/components/authentication.rst

Ref : https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/AuthComponent.php#L138-L143

[EN][FR] Added the missed configuration option `checkAuthIn` & `storage` in AuthComponent

---

en/views.rst

Introduce the View::reset() into the 3.2 documentation.

Ticket 7561

---

en/appendices/3-2-migration-guide.rst
en/contributing/code.rst
en/core-libraries/hash.rst
en/core-libraries/time.rst
en/installation.rst
en/orm/database-basics.rst
en/tutorials-and-examples/blog/blog.rst
es/installation.rst
es/tutorials-and-examples/blog/blog.rst
fr/contributing/code.rst
fr/core-libraries/hash.rst
fr/installation.rst
fr/tutorials-and-examples/blog/blog.rst
pt/installation.rst
pt/tutorials-and-examples/blog/blog.rst
tr/installation.rst

I'm not sure I have everything covered, but if there is more people would like to see I am happy to add more detail.

Immutable time docs

---

en/appendices/3-2-migration-guide.rst
fr/appendices/3-2-migration-guide.rst
fr/core-libraries/time.rst
fr/orm/database-basics.rst
fr/views.rst

[fr] 3.2 immutable objects

---

en/appendices/2-8-migration-guide.rst
en/console-and-shells.rst
en/console-and-shells/helpers.rst

Backport documentation for ShellHelpers.

---

en/appendices/3-2-migration-guide.rst
en/chronos.rst
en/contents.rst

Add usage docs for cakephp/chronos
Refs #3574

Add chronos docs

---

en/appendices/3-2-migration-guide.rst

Not everyone has the time to fix all the deprecation warnings right after upgrading.
Refs cakephp/cakephp#7887

Add info on how to disable deprecation warnings.

---

en/appendices/3-2-migration-guide.rst
en/development/errors.rst

Document the Error.extraFatalErrorMemory configuration option.

---

pt/development/testing.rst

Translating section Installing PHPUnit. Sorry for the mistake in the previous pull request.

Translating Testing docs for pt

---

en/orm/behaviors/translate.rst

This might be a helpful info for beginners...

Added note about required "use Cake\I18n\I18n"

---

en/bake/development.rst
en/plugins.rst
fr/bake/development.rst
fr/plugins.rst

Explain that bake events can be bound in plugins. And try to clarify the plugin chapter a bit.

Plugin docs

---

en/development/errors.rst

https://github.com/cakephp/cakephp/pull/7934

3.1.7 HTTP Exceptions 406, 409, 410, 403, 503

---

en/development/errors.rst

Fix: Be transparent about when the new exceptions were actually indeed introduced.

New exceptions versionadd:: 3.1 => 3.1.7

---

en/appendices/3-2-migration-guide.rst
en/console-and-shells.rst

Add documentation for cakephp/cakephp#7921

Add documentation for Shell::abort()

---

en/appendices/3-2-migration-guide.rst
en/contributing/code.rst
en/installation.rst
en/tutorials-and-examples/blog/blog.rst
es/installation.rst
es/tutorials-and-examples/blog/blog.rst
fr/appendices/3-2-migration-guide.rst
fr/contributing/code.rst
fr/installation.rst
fr/tutorials-and-examples/blog/blog.rst
pt/installation.rst
pt/tutorials-and-examples/blog/blog.rst
tr/installation.rst

[3.2] bump minimum version of php

---

en/development/configuration.rst

Ref: https://github.com/cakephp/cakephp/pull/7935

3.1.7 Add docs for Configure::readOrFail()

---

en/development/errors.rst
fr/core-libraries/email.rst
fr/development/configuration.rst
fr/development/errors.rst

ref #3614, #3615, #3617, #3620

[fr] follow last changes

---

en/appendices/3-2-migration-guide.rst
fr/appendices/3-2-migration-guide.rst
fr/console-and-shells.rst

[fr] addition of StopException

---

en/appendices/3-2-migration-guide.rst
en/contributing/code.rst
en/installation.rst
en/tutorials-and-examples/blog/blog.rst
es/installation.rst
es/tutorials-and-examples/blog/blog.rst
fr/appendices/3-2-migration-guide.rst
fr/contributing/code.rst
fr/installation.rst
fr/tutorials-and-examples/blog/blog.rst
pt/installation.rst
pt/tutorials-and-examples/blog/blog.rst
tr/installation.rst

lower the required php version to 5.5.9

---

en/core-libraries/email.rst

Avoiding to display error message.

[3.0] delete link's query string.

---

en/development/errors.rst

* 3.x style plural table magic singletons
* 3.x style view variable setting
* Self sufficient exception (fully qualified namespace)
* Code snippets should now run by copy + paste

Fixed controller/exception examples

---

en/orm/associations.rst

The docs didn't tell users what the default was.

3.0, Added the default saveStrategy into the docs.

---

en/controllers.rst
en/core-libraries/events.rst
en/orm/table-objects.rst
en/views.rst
fr/controllers.rst
fr/core-libraries/events.rst
fr/orm/table-objects.rst
fr/views.rst

Expand on the work done in #3637. /cc @davidyell

Add more documentation around core events.

---

en/appendices/2-8-migration-guide.rst

Docs for https://github.com/cakephp/cakephp/pull/7979

Docs for FormHelper::create() and url=>false

---

en/core-libraries/inflector.rst

Ref: https://github.com/cakephp/docs/issues/3654
Also ordered methods by alphabet 
Thanks @lorenzo for pointing me to the API instead of the book.

Add docs for Inflector::dasherized()

---

en/orm/table-objects.rst

@lorenzo not sure I was able to write what you thought, but if this helps.
I will also look the other ways / conventions when I get some time.
Thank you.

Added configure write to keep the App.namespace

---

en/orm/table-objects.rst

Hi , 
@lorenzo was mentioning about `Model.initialize` event. But I missed to see in the docs. @josegonzalez mentioned to send a PR.
I am unsure about the signature of the event .
I am also not sure how the initialize method works if there are two `initialize` methods :-/ . May be add a listener ?

Model.initialize is there in events list

---

en/orm/table-objects.rst

Remove caracters unsuporoted by latex

---

en/orm/table-objects.rst
fr/core-libraries/time.rst
fr/orm/table-objects.rst

@antograssiot @HavokInspiration Let me know if you see any correction. Should we translate `method hook`?

[fr] #3666, #3658 & #3649

---

en/views/helpers/paginator.rst

Recommending devs to use AppView instead of Controller

---

en/plugins.rst

Most people are probably not aware of this.

Plugin load docs for CLI

---

en/views.rst

delete second argument of `$this->Html->css('carousel', null, ['block' => true]);`

remove second argument of $this->Html->css();

---

en/plugins.rst
fr/plugins.rst

This is mainly copied from 2.x docs.
Maybe got missing, but is sure useful on how to share it with the rest of the community.

Publish plugin notes for CakePHP 3

---

en/appendices/3-1-migration-guide.rst
en/development/testing.rst
fr/appendices/3-1-migration-guide.rst
fr/development/testing.rst

Docs for https://github.com/cakephp/cakephp/pull/7991

Docs for Fixture and model lookup for table name import

---

en/controllers/components/authentication.rst

Added deprecated notice about userFields and added text about having to select password

Added more documentation around 3.1 deprecations to Auth options

---

en/core-libraries/hash.rst

Signed-off-by: Justin Yost <self@justinyost.com>

Add Default Parameter to Hash::get

---

zh/core-libraries/xml.rst

translaste  core-libraries/xml to chinese.

translaste  core-libraries/xml to chinese

---

en/controllers/components/authentication.rst

Add info about storage config

---

en/installation.rst

I suggest to use the folder name without brackets to avoid confusion.

Update installation.rst - Suggestion for app folder name

---

en/contributing/cakephp-coding-conventions.rst

Add guidelines for multi-line function call formatting for future contributors.

Guidelines for multi-line function call formatting

---

pt/tutorials-and-examples/blog-auth-example/auth.rst
pt/tutorials-and-examples/blog/part-two.rst

Correcting indentation problems of source code. Translate to Portuguese.

Translate to portuguese.

---

en/appendices/cakephp-development-process.rst

Update the branch names to be more current, and mention the new .next
branches.

Clarify the branch types and update branch names.

---

en/core-libraries/helpers/form.rst

This use case was not really documented yet.
http://stackoverflow.com/a/11695229

Add example for 'empty' in date/datetime

---

pt/appendices/cakephp-development-process.rst
themes/cakephp/static/cake.css

I've started a quick translation, the menus, as they are in CSS and added the content for the CakePHP development process.

Translating the menu headers and the development process

---

en/intro/conventions.rst
fr/intro/conventions.rst

ref to #3710
The french conventions file now contains only english technical words

replace french words with english ones

---

en/development/testing.rst

Mostly applicable to bake tests in the core
Ref https://github.com/cakephp/cakephp/pull/8169

Document assertSameAsFile

---

en/appendices/2-1-migration-guide.rst
en/appendices/new-features-in-cakephp-2-0.rst
fr/appendices/2-1-migration-guide.rst
fr/appendices/new-features-in-cakephp-2-0.rst
ja/appendices/2-1-migration-guide.rst
ja/appendices/new-features-in-cakephp-2-0.rst

Related to https://github.com/cakephp/cakephp/pull/8195

Remove references to lighthouse

---

en/appendices/new-features-in-cakephp-1-3.rst
en/contributing/code.rst
es/cakephp-overview/what-is-cakephp-why-use-it.rst
es/installation/advanced-installation.rst
es/tutorials-and-examples.rst
fr/appendices/new-features-in-cakephp-1-3.rst
fr/core-libraries/components/access-control-lists.rst
pt/controllers.rst

There were a few broken links that I couldn't figure out a sane target for.
Refs #3735

Fix most of the broken links.

---

en/installation.rst

Make it obvious that PHP 7 is in fact supported.

Update to include the fact that PHP 7 is supported.

---

en/views.rst

Ref: https://github.com/cakephp/docs/pull/3745

add ref marker view-templates

---

en/core-libraries/collections.rst
themes/cakephp/static/cake.css

Also made the method lists in the collections page a bit more compact

Collection chunk

---

en/development/routing.rst
fr/development/routing.rst

This was proposed by @lorenzo.
Suggestions on improving the description are welcome :)

Add URL filter example

---

en/console-and-shells/helpers.rst

Made suggested amends to convert lowercase to CamelCase

Amends to helpers.rst

---

en/console-and-shells.rst
en/console-and-shells/server-shell.rst

Add simple docs for the server shell.

---

en/core-libraries/components/authentication.rst

Flash method description was listed twice

replaced Session->setFlash with FlashComponent

---

en/orm/retrieving-data-and-resultsets.rst

Document sorting contained associations.

---

en/development/testing.rst

There was no information regarding composer installed plugins and fixtures. This patch fixes the issue logged here : https://github.com/cakephp/docs/issues/3778#issuecomment-189113699

update missing information

---

en/contributing/backwards-compatibility.rst

Try and make the guidelines clearer around default arguments as per the
discussion in cakephp/cakephp#8352

Attempt to clarify the position around default args

---

en/models/deleting-data.rst

https://github.com/cakephp/cakephp/blob/2.8.1/lib/Cake/Model/Model.php#L2694-L2695

Document a limitation of 'dependent'

---

en/tutorials-and-examples/blog-auth-example/auth.rst

If one follows the blog tutorial, piece by piece Categories are added in part 3.  If you add the Authentication, the treeview is missing.  I have bow readded the missing code

The Treeview is Missing

---

en/development/testing.rst

Added some missing data types.

Added Missing Supported Internal Data Types

---

en/orm/retrieving-data-and-resultsets.rst

Added a section showing how to mutate entites in a list find using a closure

Find list with closures

---

en/views/cells.rst

Clarify view cells being self contained.

---

en/orm/entities.rst

The code we had for this had a few shortcomings, that ware handled correctly in the plugin

Removing lazy loading code for a most robust solution

---

en/core-libraries/httpclient.rst

"They can also be used" not "be use"

Fix verb tense

---

en/contributing/cakephp-coding-conventions.rst

"a non-strict test" not "a none strict test"

Fix language error

---

ja/chronos.rst

translate ja/chronos

---

en/tutorials-and-examples/blog-auth-example/auth.rst

Add more wholesome example for blog-auth tutorial.

---

en/tutorials-and-examples/bookmarks/intro.rst

Ref: https://github.com/cakephp/app/pull/356#issuecomment-198180251

Make sure composer is recent

---

en/installation.rst

Ref: https://github.com/cakephp/app/pull/356#issuecomment-198180251

Make sure composer version is recent

---

en/orm/query-builder.rst

Few people actually know what hydration means, so simplifying the language may help them find the information they are looking for

Changing sub-heading title to avoid the word "hydration"

---

en/orm/saving-data.rst

Include examples for both method based approach and using newEntity(). I've also made this chapter consistently use junction table over joint.
Refs cakephp/cakephp#8440

Attempt to clarify how to update existing junction data.

---

en/core-libraries/security.rst

Document Security::randomBytes()

---

en/development/errors.rst

Needed to close the 'article' string

Add missing single quote in example

---

en/orm/database-basics.rst

This could make cakephp immediately more appealing to people wanting to use Oracle.

Adding link to Oracle driver

---

en/installation.rst

https://github.com/cakephp/docs/issues/3851#issuecomment-200952528

Educate about minimum PHP version

---

en/orm/retrieving-data-and-resultsets.rst

added note about first() returning null

---

en/orm/associations.rst

Add cross link for how to load association data.

---

en/core-libraries/internationalization-and-localization.rst

I'm not the best at grammar but the original just didn't read easily to me.

Rewrote note to improve grammar.

---

en/appendices/3-3-migration-guide.rst
en/development/routing.rst

Update a couple of examples to be more explicit about the context the code should be run in.
Refs cakephp/cakephp#8542

Remove deprecated router methods from the docs.

---

en/controllers/components.rst
en/views/helpers.rst

improved grammar and rewrite creating helper

---

en/appendices/3-3-migration-guide.rst
en/controllers/request-response.rst

Add documentation for detectors with additional arguments.

---

ja/tutorials-and-examples/bookmarks/intro.rst

English ver. -> http://book.cakephp.org/3.0/en/quickstart.html

[ja] Add guard clause according to English ver.

---

en/tutorials-and-examples/bookmarks/part-two.rst

The finished code example was also updated.
Refs #3875

Fix up bookmarker tutorial.

---

en/development/configuration.rst
fr/development/configuration.rst

Refs to https://github.com/cakephp/app/pull/328, https://github.com/cakephp/app/issues/224 and https://github.com/cakephp/docs/issues/3674
Let me know if this is the right place in the docs ? And don't hesitate to correct my english :smile:

add a paragraph about environment variables

---

en/appendices/3-3-migration-guide.rst
en/orm/database-basics.rst

Add documentation the new expression types.
Refs cakephp/cakephp#8526

Start docs for the new expression type support.

---

en/core-libraries/inflector.rst
en/core-libraries/text.rst

Add info about new methods in Text class.

---

en/orm/database-basics.rst

* posts -> articles (for clarity)
* marshaller takes just some data not specifically POST.

minor things

---

en/views/helpers/url.rst

Add documentation for URL helper methods.

---

en/orm/query-builder.rst
fr/orm/query-builder.rst

Document SQL snippet usage in query builder.

---

en/controllers/request-response.rst
es/bake/development.rst
es/bake/usage.rst
es/orm/database-basics.rst
fr/appendices/3-3-migration-guide.rst
fr/controllers/request-response.rst
fr/core-libraries/validation.rst
fr/development/routing.rst
fr/orm/database-basics.rst

some parts still need to be translated

[fr] follows 3.3 migration

---

ja/development/errors.rst

[ja] translate development/errors.rst

---

fr/tutorials-and-examples/bookmarks/part-two.rst

Traduction paragraphe "ajouter la Déconnexion"

Translating "Adding Logout" part

---

en/chronos.rst
fr/chronos.rst

Correct documentation on ISO-8601 format

---

en/appendices/3-3-migration-guide.rst

Document behavior change in datetime serialization.

---

ja/core-libraries/form.rst

[ja] translate form.rst

---

en/core-libraries/internationalization-and-localization.rst
fr/core-libraries/internationalization-and-localization.rst

defaultLocale is now configured in **app.php** since cakephp/app#328

update defaultLocale config after cakephp/app#328

---

en/appendices/3-x-migration-guide.rst

Links aren't reasonable to make at this point in time, as sphinx can't easily make links and I'd rather not hardcode URLs.
Refs #3719

Add notes about upgrading from 1.x

---

en/orm/behaviors/timestamp.rst

Add timestamp dirty documentation.

---

en/core-libraries/logging.rst
fr/core-libraries/logging.rst

`FileLog` should be `File` or `Cake\Log\Engine\FileLog`.

Fix incorrect examples

---

en/appendices/3-3-migration-guide.rst
es/bake/development.rst

Document changes in Controller::redirect

---

en/core-libraries/helpers/form.rst

Add some notes about the options of FormHelper::create().

2.x note about form

---

en/appendices/3-3-migration-guide.rst
en/orm/entities.rst

Add documentation for recursive JSON serialization.

---

en/core-libraries/helpers/form.rst

2.x: FormHelper: special treatment of 'maxlength'

---

en/core-libraries/caching.rst

Document APCu support in 2.x as well.

---

en/core-libraries/caching.rst
en/core-libraries/time.rst

Update docs for time and apc caching

---

en/tutorials-and-examples/bookmarks/part-two.rst

Remove all empty tags in the array.
Previous version still contain "" element in the array

Remove all empty tags

---

en/tutorials-and-examples/bookmarks/intro.rst

as found at http://book.cakephp.org/3.0/en/installation.html

Add specific php version requirements 

---

ja/core-libraries/app.rst

[ja] translate core-libraries/app.rst

---

ja/tutorials-and-examples/blog/blog.rst
ja/tutorials-and-examples/blog/part-three.rst
ja/tutorials-and-examples/blog/part-two.rst

Translated to Ja
http://book.cakephp.org/3.0/ja/tutorials-and-examples/blog/blog.html
http://book.cakephp.org/3.0/ja/tutorials-and-examples/blog/part-two.html
http://book.cakephp.org/3.0/ja/tutorials-and-examples/blog/part-three.html

[Ja] Translated to Ja - CakePHP3 Blog Tutorial

---

en/console-and-shells/routes-shell.rst
fr/console-and-shells/routes-shell.rst
ja/console-and-shells/routes-shell.rst

Add [ja] translation to route-shell.rst
and fix the codeblocks.

[ja] translate route-shell.rst

---

ja/console-and-shells/i18n-shell.rst

http://book.cakephp.org/3.0/ja/console-and-shells/i18n-shell.html

[Ja] Translate ja/console-and-shells/i18n-shell.rst

---

pt/appendices/3-0-migration-guide.rst

The XML section was incomplete. Added link to Http\Client.

Update PT 3-0-migration-guide.rst

---

en/console-and-shells.rst
en/console-and-shells/helpers.rst
en/core-libraries/validation.rst

Refs #3971 
Refs #3970 
Refs cakephp/cakephp#8858

Fix a few issues in the docs.

---

ja/core-libraries/internationalization-and-localization.rst

http://book.cakephp.org/3.0/ja/core-libraries/internationalization-and-localization.html

[Ja] Translate ja/core-libraries/internationalization-and-localization.rst

---

ja/views/helpers/flash.rst

http://book.cakephp.org/3.0/ja/views/helpers/flash.html

[Ja] Translate ja/views/helpers/flash.rst

---

ja/orm/validation.rst

[ja] translate orm/validation.rst

---

en/appendices/3-3-migration-guide.rst
en/core-libraries/httpclient.rst

Make the docs have fewer API reference like by including more human friendly sectioning and examples with comments.
Refs cakephp/cakephp#6960

Update Http\Client docs for PSR7 changes.

---

en/development/routing.rst

calling Router::extensions() is not cool anymore

Improving docs on routing extensions

---

en/core-libraries/internationalization-and-localization.rst

Work on Removing You Style Clauses In Intl Docs

---

en/orm/validation.rst

@justinyost mentioned a really good point in his talk today. I think including this in the docs will help clarify how validation/rules differ and how they can be best leveraged.

Attempt to clarify the difference between rules/validation.

---

ja/controllers/components/csrf.rst

http://book.cakephp.org/3.0/ja/controllers/components/csrf.html

[Ja] Translate ja/controllers/components/csrf.rst

---

config/all.py

remove ru lang in config, folder does not exist anymore

---

config/all.py

same as #4014 for 1.2

---

ja/orm/validation.rst

[ja] #4007

---

themes/cakephp/layout.html

ref to #4013, title for 2.x docs

---

fr/core-libraries/logging.rst

Fixed a small typo error in the french traduction.

Fixed typo error for french language

---

ja/development/errors.rst

Keeping original text is not a good idea :disappointed:

[ja] Remove original text

---

en/orm/saving-data.rst

Make marshalling examples more comprehensive.

---

en/appendices/3-3-migration-guide.rst
en/console-and-shells.rst
en/console-and-shells/cache.rst
en/core-libraries/httpclient.rst

Add docs for cache shell.

---

en/appendices/3-3-migration-guide.rst
en/orm/validation.rst

Add documentation for validCount()

---

en/appendices/3-3-migration-guide.rst
en/views/helpers/form.rst
fr/appendices/3-3-migration-guide.rst
fr/views/helpers/form.rst

Document the schema defaults behavior.

---

en/orm/associations.rst

as described at http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#fetching-with-the-subquery-strategy

hasOne can use 'strategy' parameter

---

en/core-libraries/helpers/form.rst

$this->Form->create(null,array()) This should be $this->Form->create(false,array())

Documentation -> $this->Form->create(null,array())

---

en/core-libraries/caching.rst

Refs https://github.com/cakephp/cakephp/pull/8900

Adds note about separated caches for APC/Wincache cli and web

---

en/contributing/code.rst
en/contributing/tickets.rst
en/intro/where-to-get-help.rst
fr/contributing/code.rst
fr/intro/where-to-get-help.rst
ja/intro/where-to-get-help.rst
pt/intro/where-to-get-help.rst

Same as https://github.com/cakephp/docs/pull/4041 for 3.x

Remove references to our closed google group

---

ja/tutorials-and-examples/blog-auth-example/auth.rst

http://book.cakephp.org/3.0/ja/tutorials-and-examples/blog-auth-example/auth.html

[Ja] Translate ja/tutorials-and-examples/blog-auth-example/auth.rst

---

en/migrations.rst
fr/migrations.rst

Refs https://github.com/cakephp/migrations/issues/235

Add an example of how to rename a table in migration files

---

ja/console-and-shells/repl.rst

http://book.cakephp.org/3.0/ja/console-and-shells/repl.html

[Ja] Translate ja/console-and-shells/repl.rst

---

en/migrations.rst
fr/migrations.rst

Refs https://github.com/cakephp/migrations/pull/236

Documents the new ability for seeders the call other seeders

---

en/appendices/3-3-migration-guide.rst
en/contents.rst
en/controllers/middleware.rst
en/core-libraries/httpclient.rst
en/development/dispatch-filters.rst
es/contents.rst
es/controllers/middleware.rst
fr/appendices/3-3-migration-guide.rst
fr/contents.rst
fr/controllers/middleware.rst
fr/core-libraries/httpclient.rst
fr/development/dispatch-filters.rst
ja/contents.rst
ja/controllers/middleware.rst
pt/contents.rst
pt/controllers/middleware.rst
themes/cakephp/static/css/default.css
tr/contents.rst
tr/controllers/middleware.rst
zh/contents.rst
zh/controllers/middleware.rst

This isn't complete, but I wanted to get people's feedback on what is missing before I consider it 'done'. With that said:
* Are there any questions you felt were unanswered by the end of the section?
* Should there be more examples of interacting with the request/response?
* Is the middleware creation example detailed enough?
Refs cakephp/cakephp#6960

Start HTTP Server/Middleware docs.

---

themes/cakephp/static/css/default.css

Use red style to make deprecations not look like good things.
Refs #4064

Make deprecations more scary looking.

---

pt/core-libraries/email.rst

Error correction in the file internationalization-and-localization.rst

[pt] Error Correction

---

en/core-libraries/collections.rst
en/core-libraries/global-constants-and-functions.rst

Add docs for global collection() function.

---

en/intro/where-to-get-help.rst
ja/intro/where-to-get-help.rst

Change `CakePHP JAPAN Facebook Group` to `Japanese CakePHP Facebook Group`

Add Japanese Slack Channel

---

en/core-libraries/helpers/form.rst

This feature was added in version 2.8.5

Added fieldset attribute for FormHelper::radio

---

pt/migrations.rst

[pt] 3.0 Migrations translation

---

en/controllers/components/authentication.rst
en/development/testing.rst

Let me know what you think!
Closes #4078

Added docs for testing stateless authentication

---

ja/controllers/components/flash.rst

http://book.cakephp.org/3.0/ja/controllers/components/flash.html

[Ja] Translated ja/controllers/components/flash.rst

---

ja/controllers/components/authentication.rst
ja/development/testing.rst

[ja] update testing.rst

---

zh/development/rest.rst

find some short English document and translated it in Chinese, hope it would be useful. I love Cake . :)

translate rest.rst into Chinese

---

en/controllers/middleware.rst

These links won't resolve just yet, but long term they will.
Refs cakephp/cakephp#6960

Add brief application upgrade docs.

---

en/appendices/3-3-migration-guide.rst
en/core-libraries/collections.rst

Add docs for Collection::transpose()

---

en/core-libraries/helpers/form.rst

Update docs and show using url + id together.

---

ja/core-libraries/time.rst

http://book.cakephp.org/3.0/ja/core-libraries/time.html

[Ja] Translated ja/core-libraries/time.rst

---

en/core-libraries/events.rst
en/development/testing.rst
fr/appendices/3-0-migration-guide.rst
fr/appendices/orm-migration.rst
fr/controllers/components/authentication.rst
fr/core-libraries/events.rst
fr/core-libraries/registry-objects.rst
fr/development/errors.rst
fr/development/testing.rst
fr/orm/behaviors/timestamp.rst
fr/orm/deleting-data.rst

@antograssiot @HavokInspiration I'm not sur about some translations about events, if you have corrections to suggest ?

[fr] #4091

---

es/bake/usage.rst

I've corrected 2 minor languages mistakes.
Spanish and English version aligned now.
Apart from these changes, I would like to understand how I can create a new page in the repository considering I'm gaining experience on Bake commands and customization so it would be great if I can share this knowledge to the community or at least, publishing some examples. 
Regards
Ignacio (Trexa Solutions - Buenos Aires, Argentina)

Minor languages correction.

---

en/bake/usage.rst

Spanish and English version aligned now.
Apart from these changes, I would like to understand how I can create a new page in the repository considering I'm gaining lot of experience on Bake commands and customization so it would be great if I can share this knowledge with the community or at least, publishing some examples. 
Regards
Ignacio (Trexa Solutions - Buenos Aires, Argentina)

Minor updates based on newer Spanish version

---

en/tutorials-and-examples/bookmarks/intro.rst

There are some gaps in the tutorial that forces the student to make leaps in understanding to follow along.

Add a note about how to add users via the application UI

---

themes/cakephp/layout.html
themes/cakephp/localtoc.html
themes/cakephp/static/app.js
themes/cakephp/static/css/default.css
themes/cakephp/static/css/responsive.css
themes/cakephp/static/css/style.css

Place the "Back to Content" link under the edit icon on the right. Attempt for #4061
See the screenshots below

move Back To contents link under the edit icon

---

en/core-libraries/collections.rst

Indicate that children nodes are not removed.
Refs cakephp/cakephp#9031

Update collections example.

---

en/controllers/middleware.rst
en/development/testing.rst

Add docs for PSR7 integration testing and sessions.

---

ja/bake/usage.rst

[ja] update bake/usage.rst

---

en/console-and-shells/schema-management-and-migrations.rst
en/development/testing.rst

ref to #4102 
Add a note in schema-management and testing pages

add notes about foreign key constraint

---

en/installation.rst
fr/installation.rst

link and more explanations for composer install

---

en/core-libraries/internationalization-and-localization.rst

Fixed translation functions examples

---

themes/cakephp/static/css/default.css
themes/cakephp/static/css/responsive.css
themes/cakephp/static/css/style.css

rm unused classes

---

en/core-libraries/validation.rst
fr/core-libraries/validation.rst

add new validation methods for 3.2

---

pt/models.rst

Grammatical and Syntax erros
Contained grammatical and syntax errors in the Portuguese language , after a review it spotted and corrected.

Grammatical and Syntax erros

---

en/migrations.rst

Fix spelling error "ommiting"

---

pt/index.rst

[pt] Add warning to the 2.x docs.

---

pt/index.rst

[pt] Remove warning of 3.x docs.

---

en/installation.rst
en/installation/advanced-installation.rst
fr/installation/advanced-installation.rst

port #4113 for 2.x

---

en/development/routing.rst

This is what works, previous version was misled.

Update routing.rst - "Changing the Controller Actions Used"

---

en/orm/database-basics.rst

https://github.com/cakephp/cakephp/issues/6471

Note to ommit periods in database option of db config.

---

pt/contributing/code.rst

[pt] Update code contributing guidelines to reflect current branches.

---

en/contributing/code.rst

Modernize some of the content, and recommend working on `master`.

Update code contributing guidelines to reflect current branches.

---

pt/index.rst

[pt] Fixes long lines.

---

en/orm/associations.rst

I'm not sure about this one, I'm not a native speaker but it sounded better to me. please close if I'm mistaken

wording update

---

en/orm/saving-data.rst

Please update text / format as necessary.

Add info about Table::saveMany()

---

en/views/helpers/form.rst

Add docs for postLink() block option.

---

en/views/cells.rst

References: https://github.com/cakephp/cakephp/pull/9139

Recommend using render() instead of __toString

---

pt/controllers/middleware.rst
pt/intro.rst

[pt] Including middleware note.

---

en/views/cells.rst
fr/intro.rst
fr/views/cells.rst

@HavokInspiration @antograssiot any suggestions ?

[fr] #4188 and #4184

---

Makefile
deploy.Dockerfile
nginx.conf
themes/cakephp/layout.html

Concatenate the assets (but no minification yet), and enable gzipping. While I know minification would be even better, shaving off 10 HTTP requests per page and enabling gzip should make the book feel significantly faster.
Refs #4017 
cc @josegonzalez I'm not sure if I did all the nginx bits right, or if this is even the right place to be enabling gzip.

Use Combined Assets and Gzip

---

config/all.py
en/404.rst
es/404.rst
fr/404.rst
ja/404.rst
nginx.conf
pt/404.rst
themes/cakephp/layout.html
tr/404.rst
tr/controllers/request-response.rst
tr/orm/retrieving-data-and-resultsets.rst
tr/tutorials-and-examples/bookmarks/intro.rst
zh/404.rst

Add skeleton pages and update nginx configuration to redirect 404s to a real page.

Add 404 page to the book.

---

en/tutorials-and-examples/bookmarks/intro.rst
fr/tutorials-and-examples/bookmarks/intro.rst
tr/tutorials-and-examples/bookmarks/intro.rst

The bookmarker tutorial contains a wrong URL

---

ja/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst

[ja] typo actionPAth -> actionPath

---

en/development/testing.rst

Add docs on stubbing env vars for testing security component.

---

ja/controllers/components/cookie.rst

Sorry,  I closed p-r by mistake.
This is the same #4199.
@okinaka I fixed. Thank you for pointing out.

[ja] translate components/cookie.rst

---

en/controllers/middleware.rst

Update middleware class and method names.

---

en/appendices/3-3-migration-guide.rst

follow: https://github.com/cakephp/cakephp/pull/9090

Rename partialNullsPass to allowNullableNulls

---

en/orm/validation.rst

Ref: https://github.com/cakephp/cakephp/pull/9090 (changeset)
Ref: https://github.com/cakephp/docs/pull/4208 (migration guide)

Update docs to allowNullableNulls

---

en/orm/query-builder.rst

Docs to Implements QueryExpression::exists and QueryExpression::notExists cakephp/cakephp#9181

Added exists and notExists query expression docs.

---

en/appendices/3-3-migration-guide.rst
en/core-libraries/security.rst
fr/appendices/3-3-migration-guide.rst
fr/core-libraries/security.rst

Deprecated mcrypt

---

pt/contributing/cakephp-coding-conventions.rst

Alteração de fefinidas para definidas

Fix Correção Ortográfica

---

en/core-libraries/helpers/flash.rst
fr/core-libraries/components/flash.rst

add a version added note to flashhelper

---

en/views/helpers/url.rst

Update documentation for UrlHelper.

---

ja/core-libraries/hash.rst
ja/views/helpers/url.rst

[ja] update hash.rst and url.rst.

---

en/controllers/request-response.rst

Document how to access the Authorization header in apache.

---

en/appendices/3-3-migration-guide.rst
en/orm/behaviors.rst
en/orm/behaviors/translate.rst

Document behavior marshalling and streamlined translation saving.

---

ja/development/rest.rst

Fixes a little typo error in code for REST.

[ja]Fixed a typo error

---

ja/core-libraries/helpers/flash.rst
ja/core-libraries/helpers/form.rst

[ja] update flash.rst and form.rst

---

ja/appendices/3-3-migration-guide.rst
ja/orm/behaviors/translate.rst

[ja] update 3-3-migration-guide.rst

---

en/orm/query-builder.rst

Improve find('list') examples.

---

fr/core-libraries/components/request-handling.rst

Ref https://github.com/cakephp/docs/commit/8b8fcd7fccd865a8f71011eb8f005e606dd86f48

[fr] StdClass -> stdClass

---

ja/core-libraries/components/request-handling.rst

Ref https://github.com/cakephp/docs/commit/8b8fcd7fccd865a8f71011eb8f005e606dd86f48

[ja] StdClass -> stdClass

---

en/controllers/middleware.rst

Add a more real-world example to the middleware docs.
Refs #4253

Make the middleware example better.

---

ja/core-libraries/time.rst
ja/core-libraries/validation.rst
ja/elasticsearch.rst
ja/orm/query-builder.rst

Refs: #4234, #4261, #4267, #4270

[ja] update some translations.

---

pt/console-and-shells/cron-jobs.rst
pt/console-and-shells/i18n-shell.rst

[pt] i18n and cron-jobs.

---

en/contributing/backwards-compatibility.rst

We've had a few situations come up where our existing guidelines were vague/not helpful. I've updated the doc based on the decisions we've been making recently.

Clarify the BC guidelines.

---

en/controllers/components/flash.rst

For https://github.com/cakephp/cakephp/pull/9358

Rectify lies about escape.

---

en/installation.rst

Wrong Version

---

en/contributing/cakephp-coding-conventions.rst

At least until we can sniff for it properly this seems to be vital information.

Clarify IDE setup to avoid whitespace noise

---

en/appendices/3-4-migration-guide.rst
en/core-libraries/events.rst

Document changes to Event package.

---

ja/404.rst

Finished translation.
It's my first work.

[ja] translate 404.rst

---

en/controllers/components/request-handling.rst

Be more specific about when directories and templates are switched.
Refs cakephp/cakephp#9422

Attempt to clarify the requesthandler docs

---

en/views/helpers/form.rst

Missing apostrophe.

---

en/core-libraries/internationalization-and-localization.rst

The old solution just assumes that all view files of a controller have been translated, this version will actually check if the file exists

Check if translated page exists

---

en/models/data-validation.rst

Clarify documentation for Validation::maxLength()

---

en/models/data-validation.rst

All of the length vaildators are unicode aware. cc @chinpei215

Update other validation method docs.

---

zh/index.rst

translate someting for welcome page

[zh] Update index.rst

---

en/models/data-validation.rst

Ref: https://github.com/cakephp/docs/pull/4306#issuecomment-246219591

Warn about utf-8 vs ascii

---

en/core-libraries/components/pagination.rst

Refs https://github.com/cakephp/cakephp/pull/9449#issuecomment-246600475
If that is not clear I don't know what is :)

Clarify maxLimit.

---

en/orm/validation.rst

Ref for PR https://github.com/cakephp/docs/pull/4313

Ref for PR #4313

---

en/views.rst

Ref: https://github.com/cakephp/cakephp/pull/9246

Load app scope element from within plugin's template

---

en/appendices/3-4-migration-guide.rst
en/controllers/components/authentication.rst

Update documentation for AuthComponent redirect changes.

---

en/controllers/components/security.rst

Update security component docs.

---

en/development/sessions.rst

Clarify docs based on
http://discourse.cakephp.org/t/cookbook-lets-me-down-once-again/1106

Attempt to clarify the documentation based on forum feedback

---

en/controllers/components/authentication.rst

I have seen on numerous occasions people trying to debug auth issues think that the SQL query only checking for username is the source of their problems.

Clarify how password check is done.

---

en/views/helpers/url.rst

Refs https://github.com/cakephp/cakephp/pull/9483
Maybe someone can rephrase via commit.

Document Url::build() options array
