- fr/orm/saving-data.rst
Inaccurate translation which changes the meaning of the sentence and the end of the sentence was not translated.
> Inaccurate and incomplete translation

- en/core-libraries/collections.rst
Sorry I merge it a little bit fast so I reverts cakephp/docs#2204.
But there is still the following question/comment from @caBBAlainB:
The above syntax is incorrect but I cannot guess what is the correct one; listNested('leaves') maybe, but I      tried listNested('asc'), listNested('desc), listNested('leaves') and got the same result.
And I think that 'id' => 2 is not suppose to desappear from the result.
> Revert "[en] Problem in an example"

- en/appendices/2-7-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/5559
What about the docs regarding `string.rst`? Rename, as well + create a BC page with a link?
Feel free to add commits on top if something is missing.
> Docs for CakeText.

- en/orm/saving-data.rst
I think that the doc should notice that now, setting a field with the set() method could be a problem in the way that all validation rules called with patchEntity and newEntity won't be applied.
> [en] saving-data.rst Improve explanations and example

- en/core-libraries/validation.rst
I'm sure validate() is gone, not sure about its new alternatives, still learning new validation :)
> 3.0 - Old Table::validate() reference in docs

- en/development/testing.rst
As of Dec. 31st 2014, phpunit is no longer available as a pear package.
> Replace pear.phpunit.de with composer and phar.phpunit.de

- en/deployment.rst
~ line 80 of `config/bootstrap.php` uses `+1 years` for cache expiration when in development mode.
> Use correct value for development cache flush

- en/core-libraries/validation.rst
Using $value in there is wrong, the only argument is the first being $closure directly. So it should be
function ($context) {}
But I added a custom value in the use part to show how to insert those into the closure if desired.
> Correcting closure example

- en/tutorials-and-examples/blog/part-two.rst
- ja/tutorials-and-examples/blog/part-two.rst
- zh/tutorials-and-examples/blog/part-two.rst
With the current tutorial, if a delete operation fails you are met with a cakePHP error message informing you about the delete action not having its own View (because in case of failure not redirection takes place).
Instead, you should be shown a corresponding flash message and be redirected to the index page.
The simplest case to reproduce this is to open the posts/index page in 2 tabs and delete one post from the one tab and then try to delete the same post from the other tab.
> Add Flash message and redirect in case delete fails

- en/core-libraries/internationalization-and-localization.rst
- fr/core-libraries/internationalization-and-localization.rst
I found that we can have a link to the I18n shell in the main internationalization chapter.
> add link to i18n shell in internationalization

- en/bake/development.rst
- en/controllers/components/csrf.rst
- en/core-libraries/events.rst
- en/core-libraries/registry-objects.rst
- es/core-libraries/components/csrf-component.rst
- es/core-libraries/events.rst
- es/core-libraries/registry-objects.rst
- fr/bake/development.rst
- fr/controllers/components/csrf.rst
- fr/core-libraries/events.rst
- fr/core-libraries/registry-objects.rst
- ja/core-libraries/events.rst
- pt/bake/development.rst
- pt/controllers/components/csrf.rst
- pt/core-libraries/events.rst
- pt/core-libraries/registry-objects.rst
Instead of attach/detach we should document and recommend the new methods as they are likely to be familiar and are less work to use.
> Recommend EventManager::on/off.

- en/orm/saving-data.rst
$options is now an ArrayObject see here http://book.cakephp.org/3.0/en/orm/table-objects.html#table-registry-usage
> signature of beforeMarshall() updated

- en/controllers/components/cookie.rst
- en/controllers/components/csrf.rst
- en/controllers/components/flash.rst
- en/controllers/components/security.rst
- en/orm/behaviors/counter-cache.rst
- en/orm/behaviors/timestamp.rst
- en/orm/behaviors/tree.rst
- en/views/helpers/flash.rst
- en/views/helpers/form.rst
- en/views/helpers/html.rst
- en/views/helpers/number.rst
- en/views/helpers/paginator.rst
- en/views/helpers/rss.rst
- en/views/helpers/session.rst
- en/views/helpers/text.rst
- en/views/helpers/time.rst
- en/views/helpers/url.rst
Currently.. Component, Helper, and Behavior page titles are mixed in including their suffixes or not. This makes them consistent. I went with omitting the suffixes because they are already nested under their respective categories in the TOC, looks cleaner within the TOC, and removes redundancy.
> Remove Component/Helper/Behavior suffixes

- README.mdown
Right now the sphinx version installed through easy_install is 1.3 beta2 release, which is not supporting current documentation scripts.
> Fixing sphinx dependency reference

- en/views/helpers/form.rst
- fr/views/helpers/form.rst
The custom widget example does not completely satisfy the WidgetInterface, resulting in an error if one is to copy / paste it directly.
For the example of the secureFields method, I went with the one from the BasicWidget
I also updated the text above the example to add details about the other method that needs to be implemented by Widget classes implementing the interface.
> Update the custom widget example

- en/appendices/3-0-migration-guide.rst
- en/bake/usage.rst
- en/tutorials-and-examples/blog/part-three.rst
- fr/appendices/3-0-migration-guide.rst
- fr/bake/usage.rst
- fr/tutorials-and-examples/blog/part-three.rst
ref cakephp/bake#46
Feel free to add anything that better fits or close it if not relevant. I won't be able to modify it for the next weeks.
> 3.0 rename ``bake view`` to ``bake template``

- ja/tutorials-and-examples/blog-auth-example/auth.rst
This document describes how to use BlowfishPasswordHasher as a password hasher, but missing a setting 'passwordHasher'.
So I copied it from English one.
> [ja] Fix a mismatch of passwordHasher in auth.rst

- en/core-libraries/global-constants-and-functions.rst
- fr/core-libraries/global-constants-and-functions.rst
- ja/core-libraries/global-constants-and-functions.rst
- Remove `__c`, `__dc` and `__dcn` (see cakephp/cakephp#4086)
- Add `__dx`, `__dxn`, ` __x` and `__xn` (see cakephp/cakephp#3703 and cakephp/cakephp#4023)
- Format variables/values/constants with double-ticks
- Remove functions from Japanese version that no longer exist
> Update global functions

- en/views/helpers.rst
`StringTemplateTrait::initStringTemplates()` is gone since https://github.com/cakephp/cakephp/commit/34a4dfa95fe226425a6ace4055c4c6218be03e71
> Remove misleading example code

- en/views/helpers/form.rst
- fr/views/helpers/form.rst
Follow cakephp/cakephp#6115.
Corrects a wrong information along the way (saying that if a string is passed, it will be used as the fieldset class).
> Follow the recent modifications to the fieldset options

- en/plugins.rst
- fr/development/testing.rst
- fr/plugins.rst
The actual :doc: reference is not a link.
It works with a :ref: link
> [fr] follow and replace doc => ref

- en/core-libraries/form.rst
- en/development/configuration.rst
The Modelless Form Chapter was missing a part on how to add default data for the modelless Form,
which @dereuromark explained to me in IRC. I tried to add a section which explains how to do so,
I hope its alright regarding write style etc.
The other fix includes the change required in order to inherit the interface for Configure Classes.
> Added missing "array" for configure + Explanation how to set default data for the modelless Form

- en/orm/deleting-data.rst
If we use object $article without showing any assignment or instantiate it the codes gets confusing...
I think it's better to reference to model Article instead.
> adding correct reference to model Article

- en/contributing/documentation.rst
ref to #1713 
add a note on how translations works for docs
> add note for translations way of doing

- Makefile
When runing `make html`, `cp` overwrites all Makefile from all languages with the en Makefile.
It should copy only if the Makefile does not exists.
It's overwritten when runing the command the first time (when `build` folder does not exist)
> add -n to cp to avoid overwrites

- en/core-libraries/inflector.rst
Adds a note to clarify that pluralize and singularize while in general will work with most English nouns, it is possible for them to have issues around singularizing a singular noun and same with pluralizing a plural noun.
Related CakePHP Core Issue that brought forth this change: https://github.com/cakephp/cakephp/issues/6236#issuecomment-88313571
> Adds clarifying language around pluralize and singularize

- fr/models/virtual-fields.rst
hasField('nom', true) renvoie true puisqu'il y A un champ virtuel 'nom'.
> Correction de sens

- themes/cakephp/layout.html
- themes/cakephp/localtoc.html
- themes/cakephp/static/default.css
It was diffcult, even for myself that I know where the contents were,
to find information on the chapter I was reading. This has also been
the experience from many other users, specially for others comming for
the first time to the docs.
> Moving the Page Contents to the page itself instead of sidebar

- en/core-libraries/internationalization-and-localization.rst
- en/orm/database-basics.rst
- fr/core-libraries/internationalization-and-localization.rst
- fr/orm/database-basics.rst
The place it was before was very awkward, so putting it now inside
the i18n docs, where people looking to localize their apps would
probably start looking.
> Moving the "Parsing Localized Datetime Data" section

- en/orm.rst
- fr/orm.rst
Some people have trouble finding the docs for accessing the database
and it is totally unterstandable since it is not easy to associate
Models = ORM. Also we should move away from telling people that the Model
is reserved exclusively for database interaction.
> Renaming Models chapter to "ORM and Database Access"

- en/core-utility-libraries/hash.rst
There were a couple arguments documented for Hash as optional (in `combine` and `remove`) that are not optional in the source code
> Match documented optional args in Hash to source code

- en/installation.rst
Without `autoindex on` (non-default), serving a folder results in a 403 Forbidden error.
This change removes the "don't rewrite dir requests" part of the rule, as has been done for Apache.
Rational explained here: https://github.com/cakephp/app/pull/154
> Follow cakephp/app#154 for Nginx also

- en/orm/saving-data.rst
patchEntities was written as "patchEntitites"
> Updated patchEntities typo

- en/orm/saving-data.rst
Quite a few people didnt know how to access the newly created id after a save() call.
This is indeed not mentioned once yet in the docs :)
Should this be even more verbose? Or is that fine?
> Clarify docs about last insert id.

- en/console-and-shells.rst
- fr/console-and-shells.rst
Documents the new extra parameters that can be passed on the dispatched shell as well as the new ``Shell::dispatchShell()`` argument syntax.
Linked to cakephp/cakephp#6292
> Documents the modifications made to Shell::dispatchShell()

- en/contributing/cakephp-coding-conventions.rst
Changes the naming convention for object variables to use lowercase/camelCase as discussed at https://github.com/cakephp/migrations/pull/79
> Corrects variable naming convention

- en/orm/entities.rst
just a test to see if meta are impacting search result.
Currently, searching `Entity` will end up with the folowing which is not ideal : 
also @markstory do you know what version of elasticsearch is on the server because I don't get the same results in local with latest version ?
> try to improve search by adding meta

- en/views/helpers/form.rst
- fr/views/helpers/form.rst
While it's not true that the `error` option takes any sub-options, it might be nice to have it actually do that, not sure. Until then however, the docs are incorrect about that.
> Fix error option descriptions.

- en/core-libraries/time.rst
This is the only way I could get formatting to work with `timeAgoInWords`. I can create tests for the core if this behavior is or is not desired.
> Update time.rst to show new formatting

- en/core-libraries/logging.rst
Added non-mentioned CakeLog::error and CakeLog::warning to the list
> Containing all convenience methods

- en/controllers/components/csrf.rst
This made some users think it was required and saw their code failing for not having https
> Removing secure option from example

- en/core-libraries/time.rst
vSome people had trouble about finding the functionality underneath Time class, and the existing link goes the project overview, not the documentation. We should provide a direct link to the docs though.
> Add carbon docs link

- en/views/helpers/url.rst
As I can see in the other parts of the docs the controller names are capitalized (Routing, HtmlHelper::link, etc.).
> Controller names should be capitalized

- en/controllers/components/authentication.rst
Custom authentication objects must implement EventListenerInterface.
> Minor fix to "creating custom auth. objects"

- en/core-libraries/app.rst
- fr/core-libraries/app.rst
- ja/core-libraries/app.rst
App::pluginPath() doesn't exist anymore, use Plugin::path() instead.
> Fix for plugin path

- en/views/helpers/form.rst
The options for the radio buttons need to the the second parameter while attributes need to be defined in third parameter.
Ref - 
http://api.cakephp.org/3.0/class-Cake.View.Helper.FormHelper.html#_radio
http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-radio-buttons
> Radio buttons example change

- en/controllers/components/authentication.rst
I've set the same example for both the 'app authentication object' and 'plugin authentication object'. I think that can be better understand in this way, having the 'Creating Custom Authentication Objects' and 'Using Custom Authentication Objects' with the same class name.
Anyway I've also added a note to clarify this.
closes #2746
> [3.0] Updated 'Using Custom Authentication Objects'

- en/orm/associations.rst
- fr/orm/associations.rst
I tried to find how to not delete the join data of a belongsToMany association when deleting an entity, but didn't find anything in the documentation related to this.
I've tried `$this->belongsToMany('Table', ['dependent' => false])`, and it works. So I'm just stating this in the documentation.
> `dependent` key for belongsToMany association documented

- en/core-libraries/internationalization-and-localization.rst
"its respective locale directory" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> internationalization - fix Bad Apostrophe

- en/orm/retrieving-data-and-resultsets.rst
Importing an excellent quick-reference of how to debug information in a Query/ResultSet from @lorenzo's [CakeFest 2015 talk](https://github.com/lorenzo/cakephp3-advanced-examples/blob/1dad4d52e44a7fadca47dc84c355ca31b431c828/slides.pdf) (slide 21). Copying [with permission](https://cakesf.slack.com/archives/general/p1433084148001526).
This change is for the location that @lorenzo recommended ([Retrieving Data & Results Sets](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#namespace-Cake\ORM)). The alternative proposed by @markstory would be on the [Query Builder](http://book.cakephp.org/3.0/en/orm/query-builder.html) page somewhere. I will happily update the PR if there is a strong preference. Maybe a cross-reference link from the other spot?
> Add details on debug()ing Query and ResultSet objects.

- en/development/routing.rst
One of the routing examples was missing the `html` extension, causing the example to not work as expected.
> Add HTML extension to routing example

- en/console-and-shells.rst
"it's" as in "it is" needs an apostrophe because it's a contraction
> console-and-shells.rst - add needed apostrophe

- en/console-and-shells.rst
"A shell can also access it’s tasks" - A possessive belonging to an "it" doesn't need an apostrophe.
> console-and-shells.rst - remove bad apostrophe

- en/orm/database-basics.rst
I know there's a doc ref to the _initializeSchema for complex types with a code example, but I felt the section would flow better and be more helpful to users if it "finished" what it was talking about all on the same page. So right after showing how to create the custom type and then enable it, we can now see it in actual usage.
> added final json type code snippet

- en/development/routing.rst
from IRC today - someone was trying to use the same `_name` twice and thought that using the same name was OK if the names occurred inside different scopes (namely, inside a prefix scope).
Side note/discussion: _should_ names be scoped /discuss
> added note about named routes

- themes/cakephp/static/cake.css
because it's bigger right now when in a `<li>` tag.
before:
> fix code highlight font size

- en/views/helpers/form.rst
per a discussion in IRC today, there was no actual documentation for FormHelper::time in the docs. Additionally, there was confusion as to how to actually apply classes to the individual select boxes. This change addresses both issues.
> added doc for FormHelper::time

- en/migrations.rst
- fr/migrations.rst
Follow up on cakephp/migrations#92 where a note was added about dealing with collations with the migrations plugin.
> Add a note on migrations about collations

- fr/core-libraries/email.rst
Follows #2913 and translate the ``Mailers`` part of the doc.
> [fr] Translate the `Mailers` part and follow some examples fix

- en/controllers/components/authentication.rst
In most cases users will be using FallbackPasswordHasher when migrating from 2.x using it's default sha1 hashing. So better to provide an easy copy / paste example.
> Update example for FallbackPasswordHasher.

- en/console-and-shells/i18n-shell.rst
- fr/console-and-shells/i18n-shell.rst
There is no `i18n initdb` command anymore. I didn't add anything as the TranslateBehavior docs already include information on how to create the required schema.
Refs #2921
> Remove incorrect section.

- en/development/routing.rst
Line #1017 had a duplicated comma in the code sample, removed.
> Removing Duplicated Comma In Fallbacks Sample

- en/appendices/3-0-migration-guide.rst
This folder does not exist anymore in 3.0.0+
https://github.com/cakephp/app/tree/3.0.0/src/View
https://github.com/cakephp/app/tree/3.0.0/src/Template
> Remove lie about Scaffold folder

- en/orm/retrieving-data-and-resultsets.rst
In the example, the comment says "Select id & title from articles, but all fields off of Users." that's not what the autoFields do if performed on the main entity. autoFields must be specified in the contain().
> [en] Update retrieving-data-and-resultsets.rst

- fr/orm/retrieving-data-and-resultsets.rst
Dans l'example, le commentaire indique "// Select id & title de articles, mais tous les champs de Users." ce n'est pas ce que fait le autoFields(true) si celui-ci est fait sur la main entity. autoFields(true) doit être fait dans le contain().
> [fr] Update retrieving-data-and-resultsets.rst

- en/views.rst
A possessive belonging to an "it" doesn't need an apostrophe (even for acronyms). Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> Fix Bad Apostrophe in views.rst

- en/appendices/2-7-migration-guide.rst
- en/installation.rst
It's pretty bad we didn't remember stating this earlier.
> Mention the fact that CakePHP 2.7 new PHP 5.3 and above.

- en/orm/table-objects.rst
I think beforeRules  can get not checked value by Cake
End of this description is same as after rules.
It is contravertial thing.
> beforeRules return

- en/appendices/3-1-migration-guide.rst
- fr/appendices/3-1-migration-guide.rst
- fr/views/themes.rst
This was omitted when the docs for shell helpers were written.
> Add ShellHelpers to the migration guide.

- en/appendices/3-1-migration-guide.rst
- en/console-and-shells.rst
- en/console-and-shells/routes-shell.rst
- en/controllers/components/csrf.rst
- en/core-libraries/time.rst
- en/development/errors.rst
- en/orm/query-builder.rst
- en/views/helpers/form.rst
@markstory in addition to what we spoke earlier, this PR also tries to fill the gap between the implemented features and the docs.
This is all I had the time to do today and obviously, more docs will be needed for cakephp/cakephp#6850 for example but at least it's mentioned in the migration guide.
> add #6620, #6800, #6850, #6906 to migration guide

- en/orm/validation.rst
- fr/orm/validation.rst
The `table` provider uses tables, not entities.
> Fix validation providers explanation.

- en/orm/entities.rst
Documents https://github.com/cakephp/bake/pull/134
> no mass assignment protection on bake console

- en/development/routing.rst
"," makes   "in the order they are connected in"　clearly related to "matched" and "parsed"  both or not.
In google translation with "," , it outputs good Japanese.
> add ","  makes clear

- en/orm/database-basics.rst
- en/orm/query-builder.rst
- fr/orm/database-basics.rst
- fr/orm/query-builder.rst
Add links to the query builder docs for running complex queries. Sometimes the query builder just gets in the way, and SQL is the simplest solution.
> Add more information on complex queries.

- en/controllers/components/authentication.rst
PHP_AUTH_PW might be empty in case of Apache2 + FastCGI-PHP Setup.
See https://github.com/symfony/symfony/issues/1813
> Debug help on HTTP Basic Auth fails

- en/core-utility-libraries/email.rst
Log is not one of the configuration keys that can be accessed using the methods for all the other configuration keys in this section via CakeEmail::log() or $Email->log();  It can only be accessed through the CakeEmail::config() method as CakeEmail::config(array('log' => true));  I moved the log to a note in the section about using CakeEmail::config.  Maybe in the long run the log method should be added to the CakeEmail class?
> Configuration Keys - log

- en/controllers/components.rst
This one was an evil one.
After deployment from OS X (NFS shared to vagrant) to Debian (Host) it did not find the ControllerAuthorize adapter. Reason was I had it in small case as it used to be in 2.x I think. Fixing the documentation here. Also it works with a string only in case you don't supply any configuration options. So I dropped the array brackets here.
> lowercased Classname fix

- en/console-and-shells.rst
Fixes a reference to the Console directory, which was removed in 3.0 (http://book.cakephp.org/3.0/en/appendices/3-0-migration-guide.html#shell-task). Also cleans up the language a bit.
> Correct reference to removed directory

- en/views/themes.rst
viewBuilder() will throw an exception when being used with Cakephp below 3.1.
> Update for Cakephp before 3.1

- en/development/testing.rst
Update the install instructions for PHPUnit to match the recommended method for adding dependencies to composer. Replace the suggestion of editing the composer.json file, with the command line require method
> Change PHPUnit install instructions

- en/development/testing.rst
As per https://github.com/cakephp/docs/pull/3215#event-399241086 comment, this adds the double colon to the preceding line so that the composer install command is correctly formatted.
> Add double colon to correctly format command

- en/core-libraries/email.rst
After discussing a bit in cakephp/cakephp#7348 it turns out that the docs need a bit of tuning.
I added a clearer explanation of the fact that all the recepiend methods (to(), cc(), bcc()) overwrite what is already set.
> Upd email.rst - Clearer expl of recepient methods

- en/core-libraries/number.rst
- fr/core-libraries/number.rst
It caused a failure for the docs since https://github.com/cakephp/docs/commit/f77c91c6f7cc4693dfb79050f06d3acdb337e108
(jenkins ref http://ci.cakephp.org/job/CakePHP%203.0%20-%20Book/2073/)
> Remove unexpected char in Number which stopped latex build

- en/tutorials-and-examples/blog/part-two.rst
Having requirePresence() covers validation scenarios where people remove fields with browser tools or malicious intent. It also lets us show how to use another feature of the framework.
Refs cakephp/cakephp#7367
> Add requirePresence() to the blog article.

- en/core-libraries/validation.rst
For uniqueness rule 'uniqueTitle' is used which is not in the table provider code, Correct rule is 'validateUnique' as per latest CakePHP code.
> Correction in rule name

- config/all.py
- en/pdf-contents.rst
- es/pdf-contents.rst
- fr/pdf-contents.rst
- ja/pdf-contents.rst
- pt/pdf-contents.rst
- tr/pdf-contents.rst
- zh/pdf-contents.rst
This PR refers to #2068.
The option `latex_domain_indices` in config/all.py prints an index at the end of the docs.
The :ref:`genindex` & :ref:`modindex` are useless after this changes.
For the english version of the pdf:
- Before changes: pdf had 844 pages
- Now: pdf has 842 pages (the 2 pages missing are useless)
Here are some screenshots of the end of the pdfs:
> [all lang] #2068 remove indices & tables in PDF

- en/models/model-attributes.rst
Ref to  #885
This is similar to [3.x schema types](http://book.cakephp.org/3.0/en/orm/database-basics.html#data-types)
I created a schema with almost all Postgres types to check the types:
'smallint' => array('type' => 'integer', 'null' => false, 'default' => null),
'integer' => array('type' => 'integer', 'null' => false, 'default' => null),
'bigint' => array('type' => 'biginteger', 'null' => false, 'default' => null),
'boolean' => array('type' => 'boolean', 'null' => false, 'default' => null),
'numeric' => array('type' => 'decimal', 'null' => false, 'default' => null),
'real' => array('type' => 'float', 'null' => false, 'default' => null),
'double precision' => array('type' => 'float', 'null' => false, 'default' => null),
'money' => array('type' => 'text', 'null' => false, 'default' => …
> CakePHP schema columns types

- ja/core-libraries/toc-behaviors.rst
Because toctree is included by /models/behaviors.rst
and it set start-line 10.
> [ja] adjust toctree's start-line 10 for original.

- en/orm/behaviors/tree.rst
I thought it would be a good idea to add a note that the recoverOrder feature is available in version 3.0.14 (see cakephp/cakephp#7411 and cakephp/docs#3292).
> Add `addversion` to docs for recoverOrder

- en/development/sessions.rst
The wrong Sql statement:
CREATE TABLE `sessions` (
`id` varchar(255) NOT NULL DEFAULT '',
`data` VARBINARY, -- or BYTEA for PostgreSQL
`expires` int(11) DEFAULT NULL,
PRIMARY KEY (`id`)
);
The data type for 'data' field is wrong, and it's not working. Bellow is the right Sql statement
CREATE TABLE `sessions` (
`id` varchar(255) NOT NULL DEFAULT '',
`data` BLOB, -- or BYTEA for PostgreSQL
`expires` int(11) DEFAULT NULL,
PRIMARY KEY (`id`)
);
> Update session.rst - SQL statement correction.

- en/core-libraries/global-constants-and-functions.rst
- fr/core-libraries/global-constants-and-functions.rst
to avoid question about non-working functionality
> 3.1 add a note to specify from when ``$default`` is availlable in ``env()``

- en/core-libraries/collections.rst
* Cover why/when to use toList()
* Cover that {*} is the only supported wildcard.
* Cover that associations are different.
Refs #3332
> Add more context for extract()

- en/orm/table-objects.rst
with current example must use "namespace App\Model;" instead of "namespace App\Model\Entity;" in Entity class ,It is not recommended
With this change,You do not have to do it.
> repaire Entity class address

- ja/intro/conventions.rst
Translations in "Model and Database Conventions" were fixed.
モデルとデータベースの規約について誤りが何点かあるようでしたので、修正してみました。
① 修正した箇所の「モデルのクラス名」は複数形ではなく単数形のはずです。原文はTableでしたので「テーブルのクラス名」が正しいはずですので修正しました。
② また、categoryについてのtypoがありましたので修正しました。
> Modifications about typo and so on.

- en/orm/behaviors/translate.rst
I suggest to update the examples in the book chapter about the Translate Behaviour to use the same language abbreviations as in the chapter Internationalization and Localization thus it is consistent.
As I'm new to GitHub please have a closer look if the changes are done correctly. I don't know how to set a link to the chapter "Internationalization and Localization" so maybe someone want to add it in the new text snippet about the language abbreviations? Thanks.
> Language abbreviations in Translate Behaviour

- en/orm/behaviors/translate.rst
I'd like to suggest more optimations in the chapter "Translate Behaviour" (CakePHP 3.x):
- Added info about the location of sql schema file at "Initializing the i18n Database Table"
- Added background info about the column length of the field "locale"
- Moved the note about language abbreviations to the paragraph "Initializing the i18n Database Table"
- Formatted the recommended language abbreviation as tip
> Optimized text added in #3352

- en/tutorials-and-examples/blog/part-three.rst
The back slash in the "note" under "Generate skeleton code for categories" was not visible due to it not being escaped.
The sentenced read
"If you are on Windows remember to use instead of /."
Now fixed.
> Escaped back slash in Windows reminder

- en/models/saving-your-data.rst
- fr/models/saving-your-data.rst
- zh/models/saving-your-data.rst
This is simply wrong, the conditions don't need escaping, the fields do. Doing what the current example shows will generate:
UPDATE
bakers as Bakers
SET
Bakers.approved = 1
WHERE
Bakers.created <= '\'2015-10-14 14:23:55\''
> Fix updateAll example

- en/migrations.rst
- en/tutorials-and-examples/blog/part-three.rst
- fr/migrations.rst
- fr/tutorials-and-examples/blog/part-three.rst
- ja/migrations.rst
- ref to migrations change in https://github.com/cakephp/migrations/pull/140
- add `use Migrations\AbstractMigration;` to be consistent
> add example for bake field length

- en/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
If you just run git clone git://github.com/cakephp/cakephp.git you will get 3.0 as default and none of the tutorial will work unless you use the 2.0 version of cake.
> You need to use 2.0 for this tutorial to work

- en/migrations.rst
- fr/migrations.rst
Update the migrations plugin book with the recent changes made to the ``mark_migrated`` command.
I decided to leave the old way of doing things given the old behavior is still here for backward compatibility.
Refs https://github.com/cakephp/migrations/pull/137 and https://github.com/cakephp/migrations/pull/142
> Update the migrations plugin book with the recent changes

- en/development/dispatch-filters.rst
I found the sentence ambiguous (higher as in priority order, like 1 is higher in term of priority than 10 ? or higher as a numerical value ?), as opposed to the one from the Event system doc : 
http://book.cakephp.org/3.0/en/core-libraries/events.html#establishing-priorities
> Rephrase a sentence to avoid ambiguity

- en/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
Initialize the Db Acl tables
============================
Before we create any users or groups we will want to connect them
to the Acl. However, we do not at this time have any Acl tables and
if you try to view any pages right now, you will get a missing
table error ("Error: Database table acos for model Aco was not
found."). To remove these errors we need to run a schema file. In a
shell run the following::
I followed this step a few times in 2.6 and 
"However, we do not at this time have any Acl tables and
if you try to view any pages right now, you will get a missing
table error" 
Does not give me an error, I suspect that either 
1. A step is missing between line 115 "Preparing to Add Auth" and  line 223 "Initialize the Db Acl tables" OR
2. The cake bake all command builds scaffolding …
> Appears to be incorrect or missing a step

- Dockerfile
- README.mdown
I added a `Dockerfile` to the docs. I think this can ease the installation process as more and more people use docker.
We could also create an image in the [DockerHub](https://hub.docker.com/), allowing people to just run a command to run the docs building process, something like:
docker run -i -t -v /full-path-to-your-local-docs-cakephp/:/data cakephp/docs make html
With no need to build an image.
> 3.0 dockerfile

- README.mdown
To ease the use of docker, the best would be to create an official image on Dockerhub (from the Dockerfile of this repo). This would avoid the issues when building the image. For now, you can use my image without having to build an image:
docker run -it --rm -v $(pwd):/data cake17/cakephp:cakephp-docs make html
> add a --rm flag to rm container after run

- en/migrations.rst
The double dash had been converted to a single "m"-width-dash thus I escaped the two dashes so that they are displayed properly.
> Small readability improvement concerning --target parameter

- en/bake/development.rst
- fr/bake/development.rst
When baking a custom type class, tests files should only be created if the class type has been declared.
This gives an example of how to do it.
Refs to #3435
Linked to https://github.com/cakephp/bake/pull/170
> Add details about baking test files with custom bake command options

- en/tutorials-and-examples/bookmarks/intro.rst
just went true and recognized this note for windows, to start the internal server is missleading. The server arg is needed on windows too.
> miss leading note to start internal server

- en/development/testing.rst
> CakePHP uses the connection named ``test`` in your **config/datasources.php**
configuration file.
Is this still correct? In the manual's [configuration section](http://book.cakephp.org/3.0/en/orm/database-basics.html#database-configuration) there is no such file mentioned.
> Location of datasource configuration deprecated?

- Makefile
This will allow a jenkins job to be run whenever the indexes need to be rebuilt. This should reduce the amount of time it takes to get indexes rebuilt in the future.
> Add tools to rebuild indexes.

- en/controllers/components/authentication.rst
- fr/controllers/components/authentication.rst
Not sure whether the example should really use the `key` option, but if it should, then it should look more like this.
> Fix Flash component usage in Auth component login example.

- en/console-and-shells.rst
- es/console-and-shells.rst
- fr/console-and-shells.rst
- ja/console-and-shells.rst
- ja/core-libraries/security.rst
- ja/orm/database-basics.rst
- zh/console-and-shells.rst
ref to #3432.
The new title is `Shells, Tasks & Console Tools`, all terms are in the title now. I can change it if you prefer something else. I think we should let the term `Console` as it was used in previous versions of CakePHP.
I rebuilt locally the docs and the toc appeared nicely in my browser, but we might need a manual process to rebuild it on server (or with the new jenkins job?).
> 3.0 console and shell

- en/views/cells.rst
And not an associative array -- i.e. you can't pass named parameters
Ideally you *could* pass named parameters, of course. Then the way it was before would be great. That would take changes to CakePHP's code though ;)
> Made it clear that cell() $data argument is an indexed array

- en/core-libraries/internationalization-and-localization.rst
This incorrect example is probably copied from Gettext docs and it doesn't make any sense in Croatian language.
> Correct gettext example for multiple plural forms

- en/contributing/backwards-compatibility.rst
Adding a method to an interface breaks any existing implementation of that interface. Shouldn't doing this be considered a BC-break?
> New methods in interfaces is a BC-break

- en/tutorials-and-examples/bookmarks/intro.rst
The query builder now throws an error when IN conditions have no items. Avoid this issue with an explicit null check.
Refs #3494
> Include default routes & fix error.

- en/orm/behaviors.rst
added an example to demonstrate how to configure a behavior that was already previously loaded - i.e. added a `User.login` event to a table that extends an `AppTable`
> added example of configuring existing behavior

- en/core-libraries/hash.rst
Hash::remove sample code is wrong.
Code:
```php
$data = [
0 => ['clear' => true, 'Item' => ['id' => 1, 'title' => 'first']],
1 => ['Item' => ['id' => 2, 'title' => 'second']],
2 => ['Item' => ['id' => 3, 'title' => 'third']],
3 => ['clear' => true, 'Item' => ['id' => 4, 'title' => 'fourth']],
4 => ['Item' => ['id' => 5, 'title' => 'fifth']],
];
$result = Hash::remove($data, '{n}[clear].Item[id=4]');
print_r($result);
```
Result:
```
Array
(
[0] => Array
(
[clear] => 1
[Item] => Array
(
[id] => 1
[title] => first
)
)
[1] => Array
(
[Item] => Array
(
[id] => 2
[title] => second
)
)
[2] => Array
(
[Item] => Array
(
[id] => 3
[title] => third
)
)
[3] => Array
(
[clear] => 1
)
[4] => Array
(
[Item] => Array
(
[id] => 5
[title] => fifth
)
)
)
```
> Fix Hash::remove sample code results

- en/orm/validation.rst
The example for field length validation in "Combining Validators" is not valid code. The rule name is incorrect and the rule and its parameters need to be provided contained in an array.
> Fix example in validation.rst

- en/core-libraries/number.rst
before option is `before` the number .
after option is not `before` the number , change `after` .
> fix description of option for number

- en/core-utility-libraries/app.rst
- en/core-utility-libraries/string.rst
The String class has been deprecated in 2.7 and replaced with CakeText. Reflect that in the documentation.
> Rename String to CakeText.

- en/installation.rst
The `pygments` lexer is failing to automagically detect the correct language when lexing the code on the installation page. For the code blocks that it is failing on, the language should be specified explicitly.
> Specify highlight language explicitly in installation docs

- en/core-libraries/helpers/text.rst
Rename $htmlOptions to $options.
> [2.x] Fix the argument name of TextHelper.

- en/orm/validation.rst
fixes https://github.com/cakephp/docs/issues/3575
> Using the right method names

- en/orm/query-builder.rst
Calling `$query->newExpr()->func()` returns the error
BadMethodCallException with message 'Method func does not exist'
> Fix wrong example of the sql functions

- en/appendices/3-2-migration-guide.rst
- en/views/helpers/form.rst
Docs for https://github.com/cakephp/cakephp/pull/7887
> Add docs for deprecating action key in FormHelper::create()

- en/getting-started/cakephp-conventions.rst
Relaxed HABTM convention by making clear which part is mandatory (must use table names, joined by an underscore, order should be alphabetically but need not be). Changed example from apples/zebras (as that makes little sense as a HABTM) to apes/zoos (as that hopefully makes more sense).
Ref: https://github.com/cakephp/bake/issues/204#issuecomment-168046038
> Relaxed HABTM convention. Changed example.

- en/core-libraries/email.rst
The documentation has the name of the default app.php file incorrectly notated. Changing it to the correct filename.
> app.php.default to app.default.php

- es/appendices/glossary.rst
Translation of the file glossary.srt to spanish. Based on the english version in the folder en/appendices/glossary
> Translates glossary.srt to spanish

- en/appendices/3-2-migration-guide.rst
Consolidate deprecations into one place to make it easier to find.
> Reorganize the migration guide.

- en/appendices.rst
- en/appendices/3-x-migration-guide.rst
- en/contents.rst
to help people that are not familiar with the appendices to find the migration guide faster.
Then the top link in the menu will ink to all 3.x migration guides.
Comes in addition of #3621 
it will shows up like that:
and will still be available from appendices. I didn't move any pages so it won't break the search result and/or the google references.
> 3.2 moves the migration guide to separate page

- en/views.rst
second argument : return default The block content or $default if the block does not exist.
> default in second argument of fetch()

- en/core-utility-libraries/email.rst
Google has introduced a setting called "access for less secure apps" that needs to be enabled to be able to use SMTP/IMAP on gmail now.
People keep on asking on about password errors origination from this requirent.
> Added information about less secure apps

- en/core-utility-libraries/email.rst
Avoiding to display error message.
> Delete link's query string.

- en/core-libraries/events.rst
Added a list of core events to the events page, and also added a link to the more verbose documentation on the Tables manual page.
Looks like this once built on my machine.
> 3.0, List of events on the Events page. Resolves #3478

- README.md
We should do the same for 3.0 branch then.
This should clarify some beginners confusion on why cakephp/cakephp master does not match the docs one.
> Explain that master is not for 3.x

- en/development/errors.rst
- fr/development/errors.rst
The [exception list](http://book.cakephp.org/3.0/en/development/errors.html#built-in-exceptions-for-cakephp) starts to be really long and hard to navigate or at least hard to see when exception namespace change.
I first took the lazy way by just separating the HTTP from the others, but I think that it would be good to separated also View / Controller / ORM / Console.. etc
I can update the PR if you also think that it's a good idea
> Exceptions

- en/console-and-shells/completion-shell.rst
- fr/console-and-shells/completion-shell.rst
Improves the documentation on how to setup autocompletion for the CakePHP Console.
Can someone using MacOS tell me if the bash script is good as well for MacOS ?
Because I replaced the filesystem browsing part of the bash autocompletion script by the _filedir function that is bundled with the bash-completion lib, but I don't know if it's available on MacOS.
Linked to https://github.com/cakephp/cakephp/pull/7800 and https://github.com/cakephp/cakephp/pull/7784
> Improve autocompletion setup instructions

- en/orm/saving-data.rst
I believe the moved paragraph and code sample were out of place, and should be placed as in the change: directly under the section on Converting Multiple Records, rather than in the Changing Accessible Fields section.
> Change ordering

- en/orm/entities.rst
> [EN] might be typo: en/orm/entiry

- en/plugins/how-to-create-plugins.rst
Added a tip about not using `parseExtensions()` inside plugin routing files, which causes the `Router::extensions()` array to be overwritten.
> Plugin tip on extension routing

- en/appendices/3-2-migration-guide.rst
- en/contributing/cakephp-coding-conventions.rst
- en/orm/entities.rst
Use fields instead of properties. This makes the docs more consistent as other things like find(list) reference fields not properties.
Refs #3701
> Update nomenclature used for virtual fields.

- en/development/testing.rst
- fr/development/testing.rst
Passing an empty array to `getMock` throws an error:
Error: Argument 2 passed to Mock_Controller_XXXXXXX::modelFactory() must be callable
It should be null instead.
> getMock does not accept an empty array, it should be null instead

- en/orm/associations.rst
Corrected spelling and grammatical errors in content describing the Table::addAssociations() function.
> Improved grammar in content describing Table::addAssociations() function

- en/core-libraries/hash.rst
You shouldn't use an apostrophe when referring to a plural noun.
> remove Bad Apostrophe

- en/installation.rst
Repo 2.7 does not exist anymore, so executing the git glone in the docs won't clone the repo. Changed from 2.7 to 2.x
> git clone command changed

- en/migrations.rst
Currently, there are two places where you can find documentation about the migrations plugins : the cookbook and the README of the plugin.
There are a few problems with this :
- it's hard, cumbersome and time consuming to keep both in sync (they are currently not synced)
- they do not contain the same informations (some infos are in the README and not the doc and _vice-versa_)
This PR is an overhaul of the migrations docs : I reorganized some sections, added titles to some, rewrote sentences, added more examples, added sections from the README that were not in the docs.
Ultimately, my plan is to remove all documentation from the README (except for installation instructions and maybe a small paragraph about what the plugin can be used for) : kind of like what is already in place for …
> Migrations overhaul

- en/orm/saving-data.rst
The documentation falsely states that saving could not remove existing records in the case of hasMany associations. This is contradicting to:
http://book.cakephp.org/3.0/en/orm/associations.html#hasmany-associations
Also I tested the 'replace' saving strategy on hasMany with the expected result.
> Introduce saving strategy to hasMany associations

- en/intro.rst
it is about view templates here mostly not about views
> clarify view paragraph

- en/controllers/components/authentication.rst
"store" as a verb, not "storage" as a noun.
> Fix language error

- en/core-libraries/file-folder.rst
It wasn't clear to me if the filesize was in bit or in bytes. So I looked into the CORE-code. Now this won't be necessary.
> Added bytes

- en/plugins.rst
Imho it needs to be more clear that Plugin::loadAll() isn't really a completely lazy anymore in 3.x.   If you go through this tutorial there is a part that makes it sound like you can use loadAll() in place of load() and it will need no more configuration.  But actually you can't, and you have to specify routes is true, because it does not default to that with loadAll().
> Plugin::loadAll() doesn't work lazily

- en/migrations.rst
- fr/migrations.rst
Following https://github.com/cakephp/migrations/issues/199 and https://github.com/cakephp/migrations/pull/201
This adds a note about using the ORM cache shell to clear the metadata cache if the migrations plugin is used during a deployment process.
> Add a note about the migrations plugin, deployment and the orm cache

- en/controllers.rst
- en/core-libraries/events.rst
Returning a response doesn't stop other callbacks, you need to stop the event to do that.
Refs cakephp/cakephp#8372
> Clarify beforeFilter behavior.

- en/core-libraries/security.rst
The possessive "application's" needs an apostrophe.
> Add needed apostrophe

- en/orm/saving-data.rst
I had to dig through a bunch of cakedc plugins to try and find why my validation rules weren't being respected.  I think it will help other people to know that TableRegistry::get() works if you use the right convention for a table name, but that it won't find your plugin rules if you don't specify the correct path to the ArticlesTable.php file.
> give more TableRegistry::get() examples

- en/views/helpers/form.rst
Updated the templates section to include the default formats, which makes it so that you can copy and paste these easier when making customizations.
> more useful as copy pastable

- en/views/helpers/form.rst
Refs: https://github.com/cakephp/docs/pull/3791#issuecomment-192228516
Again, a URL endpoint for the last 3.x and 2.x API docs would help us to keep such links up to date.
But at least like this now, we only have to keep the link up to date.
> Replace default templates with link to API

- en/orm/behaviors.rst
- fr/orm/behaviors.rst
In the current documentation (http://book.cakephp.org/3.0/en/orm/behaviors.html#defining-event-listeners), there is a missing `use` for `EntityInterface`, which results in a PHP warning:
> Warning (4096): Argument 2 passed to App\Model\Behavior\SluggableBehavior::beforeSave() must be an instance of App\Model\Behavior\EntityInterface, instance of Cake\ORM\Entity given, called in /srv/www/typename.fr/public_html/vendor/cakephp/cakephp/src/Event/EventManager.php on line 390 and defined [APP/Model/Behavior/SluggableBehavior.php, line 27]
> Add use for EntityInterface in Behavior example.

- en/tutorials-and-examples/bookmarks/intro.rst
People usually forget to add that line and end up having errors during password hashing. So i just added a comment reminding the user to include that line.
> Updated to include a reminder as comment

- en/deployment.rst
- Encourage git clone or pull and composer install deployment over ftp.
- Add note about orm_cache clear
- Change wording that instructs to change your app.php (it does not need to be done when updating but rather when deploying the first time)
Ref: https://github.com/cakephp/app/pull/349#issue-139592358
> Encourage git/composer deployment, add orm_cache

- en/core-libraries/validation.rst
This is such a great feature and it's completely undocumented!
* Am I referring to the correct thing when saying 'custom dynamic provider'?
* Does this need it's own heading to better explain how it works?
* Does there need to be an example of a callable validation method? (Would be new PR)
* Are the parameters of the call to `validator()` going to be clear enough to readers? So they know which validator they're getting.
> Passing data via provider into validation methods

- en/controllers/request-response.rst
allowAuthentication() isn't a method on the class.
> Fixed cors documentation

- en/appendices/3-3-migration-guide.rst
- en/development/routing.rst
> Add docs for nested resource routing.

- en/orm/query-builder.rst
At line 603: the query return "gte('view_count', 10)".
But at line 613: the condition is "view_count > 10".
It should be "view_count >= 10", i think.
> Lack equal symbol

- en/core-libraries/events.rst
There are situations where an event has not been implemented, specially in the case of a 3rd party plugin, one can still listen to default events fired by CakePHP, but be very specific to what is really needed.
> Adding an example to listen to events not dispatched

- en/core-libraries/global-constants-and-functions.rst
3.x -> 3.3 https://github.com/cakephp/docs/pull/3860
Also changed order of debug/pr/pj so that debug/pr/pj are close to each other as they do the same thing and there was no order by alphabet before, either.
>  debug,pr,pj return submitted var #3860

- en/controllers/components/security.rst
Adds improved docblock for blackHole method call.
Adds information about the exception that is included in 3.2.6 when returned.
> Update BlackHole Callback For Cake 3.2.6

- en/migrations.rst
While getting migration statuses in json there should be a status keyword, which was missing.
> get status results

- en/development/debugging.rst
Target 3.3 instead of 3.x https://github.com/cakephp/docs/pull/3861
>  educate about 'chaining' debug() #3861

- fr/core-libraries/helpers/session.rst
Fixes a little typo error in french translation for SessionHelper.
> Fixed a typo error

- pt/core-libraries/inflector.rst
I've translated this file the best I could. For some reason, the first ".. note::" translates into a message warning the user that the portuguese version isn't available and I couldn't get rid of it.
Also it would be nice to translate "Note:" into "Nota:" but I couldn't figure out a way to do it.
> inflector.rst translation to portuguese

- en/core-libraries/logging.rst
Now is like 2.x fixed one: https://github.com/cakephp/docs/blob/master/en/core-libraries/logging.rst
> Fix 3.0 branch of logging

- en/appendices/3-3-migration-guide.rst
- en/core-libraries/validation.rst
> Document array form of requirePresence()

- en/orm/associations.rst
Related: These need type hint updates to match:
http://api.cakephp.org/3.2/source-class-Cake.ORM.Association.BelongsToMany.html#110
http://api.cakephp.org/3.2/source-class-Cake.ORM.Association.BelongsToMany.html#156
> targetForeignKey and foreignKey can take lists

- en/core-libraries/helpers/form.rst
`$attributes['empty'] = false;` is not passed
> Empty option would be printed

- en/bake/development.rst
The pre-processed template file is generated to tmp/bake folder instead of tmp.
> fix the folder of the pre-processed template file.

- en/development/testing.rst
We started having failures on our CI server that I eventually traced down to [these lines][1] not being happy about our test environment not having `'debug' => true`. 
Let me know if these changes explain the issue well enough.
[1]: https://github.com/cakephp/cakephp/blob/3.2.6/src/Controller/Component/SecurityComponent.php#L361-L366
> Added note about turning debug on for tests with tokens

- en/views/helpers/form.rst
Unlike in 2.x datetime/time/date fields must use 'default'.
Refs #3974
> Datetime fields should use default.

- en/contributing/cakephp-coding-conventions.rst
- en/orm/query-builder.rst
*  Document using locking statements with epilog() #3981
*  Add section on avoiding empty(). cakephp/cakephp#8397
* Reorder query builder post-processing section and wrap long lines.
> Add docs for epilog() and empty() recommendations

- en/core-libraries/logging.rst
To make a custom logger, you need to add the parent::__construct($options) call. 
Otherwise everything borks.  At least it fixed the problem for me.
> Fixed custom logger info

- themes/cakephp/static/css/default.css
- themes/cakephp/static/css/responsive.css
- themes/cakephp/static/css/style.css
Remove the CSS that came in the big asset bundle to reduce how much unused CSS we ship across the wire.
The design firm originally provided us merged assets, this removes the CSS that isn't used for the book.
> Remove unused styles that don't get used in the book

- en/controllers/request-response.rst
I found out the hard way that Etags do not play well with most proxies and I now feel are very understandable reasons. Hope this helps people out wondering why e.g. etags and nginx proxy don't work when developing.
> Adds note about Etag alternative for (most) proxy users

- en/core-libraries/events.rst
- en/development/testing.rst
Documentation for https://github.com/cakephp/cakephp/pull/8985 and https://github.com/cakephp/cakephp/pull/8853.
I created a new main section on the testing docs because I didn't know quite where to fit it. I was going to stick it under testing models, but it can test other event managers as well.
Let me know if anything needs moved or if I need to write better examples. I piggybacked on the "OrdersTable" example on the event system docs but can write something completely new if it makes more sense to.
> Added docs for event tracking and asserting events

- en/migrations.rst
This feature is being introduced in cakephp/migrations v1.6.3.
Reference: Issue cakephp/migrations#203 / PR cakephp/migrations#249
> Documents nullable columns in baked migrations

- en/core-libraries/validation.rst
The return statement is required. If there is no "return $validator" an error is thrown.
> Add a missing return statement

- en/index.rst
3.x is now the primary release branch of CakePHP, we shouldn't greet people with a warning.
> Remove warning from 3.x docs.

- en/index.rst
Warn people who end up on the landing page of the 2.x docs that they might be in the wrong place.
> Add warning to the 2.x docs.

- en/core-libraries/httpclient.rst
The multipart request is required to contain a valid boundary within its `Content-Type` header.
Otherwise, overwriting request header using a fixed content type without a boundary makes the whole request payload to be non-parseable.
A valid boundary can be retrieve from `FormData->contentType()`, so the example code have to indicate that.
> Cake\Network\Http\Client API documentation contains a broken example

- en/index.rst
- themes/cakephp/layout.html
- themes/cakephp/static/css/default.css
Add a bolder warning that the 1.3 docs are for an unsupported version. If people are 🆗 with this, I'll apply it to the 1.2 and 1.1 docs as well.
The banner is sticky with the grey nav bar.
> Add a warning to the 1.3 docs

- en/appendices/3-3-migration-guide.rst
- en/controllers/components/pagination.rst
- en/views/helpers/paginator.rst
Add documentation using the proposed `requestScope` option name, instead of the more ambiguous `prefix` option.
Refs cakephp/cakephp#8488
> Add documentation for multiple pagination.

- pt/index.rst
O texto inicial foi acrescentado, onde explica que o CakePHP 3 funciona com a versão do php 7.
> Texto Acrescentado

- en/controllers.rst
- en/controllers/request-response.rst
- en/development/routing.rst
- en/views/cells.rst
It's best that new users are not aware of this feature.
> Remove all references to requestAction().

- en/orm/query-builder.rst
The existing formatting makes it look like all the arguments are part of the call to add() until you follow through the brackets. This formatting is the same style as is used for the more complex example below.
> Restructure example code in 'Case statements' section of Query Builder

- fr/controllers/components/authentication.rst
`'nom d'utilisateurs [...]'` to `"nom d'utilisateurs [...]"`
> [Typo] fixing bad string wrapping

- README.md
- config/cakebranch.py
- config/cakei18n.py
- en/core-libraries/helpers/paginator.rst
- fr/core-libraries/helpers/js.rst
- fr/core-libraries/helpers/paginator.rst
- ja/core-libraries/helpers/paginator.rst
- requirements.txt
This refers to https://github.com/cakephp/docs/issues/921.
Update sphinx to the latest 1.4.5 needs the following steps for the master branch (2.x) for now (3.x will follow):
- the [phpDomain](https://github.com/markstory/sphinxcontrib-phpdomain) need some fixes made on [branch sphinx-1.4.5](https://github.com/cakephp-fr/sphinxcontrib-phpdomain/tree/sphinx-1.4.5). I made this PR https://github.com/markstory/sphinxcontrib-phpdomain/pull/1 to solve this
- Then it should be updated on the [python package website](https://pypi.python.org/pypi) with new tag 0.2.0
- This PR needs to apply
- docker images in cakephpfr/docs will need some changes made on [branch sphinx-1.4.5](https://github.com/cakephp-fr/docker/tree/sphinx-1.4.5)
Travis build fails because sphinxcontrib-phpdomain needs the update …
> Update Sphinx to 1.4.5

- config/all.py
- en/404.rst
- es/404.rst
- fr/404.rst
- ja/404.rst
- nginx.conf
- pt/404.rst
- tr/404.rst
- zh/404.rst
The previous attempt at error pages didn't entirely work. Paths were wrong, and more importantly all languages would get english error pages with english nav. This wasn't great, but by making the nginx
configuration a bit more verbose we can redirect users to 404 pages in their language.
The `:orphan:` tags suppress the TOC warnings while still letting the pages be built.
> Add i18n error pages.

- en/core-libraries/hash.rst
Added a use-case for `Hash::combine` showing the (missing, imho) step of mapping a key to single value. The docs show how to get just the key and how to map the key to an array, but not to a single value. Might be obvious in hindsight but it cost me a few minutes and a slack chat today.
> added `Hash::combine` use-case

- en/core-libraries/logging.rst
I found it misleading, where the doc states that LogTrait is used almost everywhere. It is not available from Tables and Behaviours, which are one of the most popular classes.
> Loggin documentation mislead a bit about popularity of the LogTrait

- en/core-libraries/components/pagination.rst
- en/core-libraries/helpers/form.rst
example should stay together with the output below, instead of be mixed up with the note above
> [en] correct original text

- en/core-libraries/events.rst
If the Event Model.Order.afterPlace is also passing the order entity, does it not make sense that the updateBuyStatistics also receive it?
> Updated updateBuyStatistic example function

- themes/cakephp/static/css/default.css
While browsing the documentation, one is unable to locate current page in TOC. Highlighting the current page will help that. I have used CakePHP default colour for highlighting. Designers can put in their inputs.
> Added style for current page in TOC

- fr/orm/database-basics.rst
```php
public static function parse($value)
{
// Parse the data from MySQL.
-            return new static($part[0],$part[1]);
+            return new static($value[0], $value[1]);
}
```
> bad variable name

- en/core-libraries/validation.rst
Unique values should be enforced using application rules instead.
> Remove examples using validator for unique values.

- en/core-libraries/time.rst
for locales and date time strings.
Ref: https://github.com/cakephp/cakephp/issues/9329
> Make it more obvious how to set format defaults

- themes/cakephp/static/css/default.css
> Fix download link alignment

- en/development/routing.rst
- en/plugins.rst
- en/tutorials-and-examples/bookmarks/intro.rst
Since PHP5.5 is a requirement we can use this optimization and should also promote it.
> Use ::class consistently in routes config.

- en/core-libraries/text.rst
Tolist has three params but in document it describes two. Third one is for changing separator which is by default comma.
> Tolist has three params

- en/appendices/3-3-migration-guide.rst
Not entirely sure about the wording on this, let me know if you want me to change it.
Refs https://github.com/cakephp/cakephp/issues/9411
> Add note about losing original values on save

- en/views/helpers/form.rst
The code block after the next was identical to this code block, could be confusing. Not sure this is the best improvement, but it's certainly better than having the same code twice.
> Removing redundant doc section

- en/bake/development.rst
The text states you need to define 4 methods, whereas the description and code example only show 3.
> Fixed typo in Creating New Bake Command Options text

- en/core-libraries/helpers/text.rst
Same issue as this one https://github.com/cakephp/docs/pull/4322 for CakePHP 3.
> Fixed markup typo in autoParagraph example (CakePHP 2.x)

- en/views/helpers/text.rst
The HTML tags in the example code weren't closing.
> Fixed markup typo in autoParagraph example

- en/orm/saving-data.rst
Note: I will still have to dig for the Sphinx syntax to reference that given link + chapter
Ref: https://github.com/cakephp/cakephp/issues/9457#issuecomment-247206577
> Disable marshalling of nested data docs + link

- en/core-libraries/inflector.rst
The output is the CamelCased singular form, not plural
> correct example output of classify()

- en/core-libraries/global-constants-and-functions.rst
Unless I'm missing something, we used to use sprintf with translate functions - but then we switched to using Aura and sprintf placeholders in translation strings are then treated as plain text.
> Fix docs for translation placeholders

- en/orm/retrieving-data-and-resultsets.rst
Following a comment https://github.com/cakephp/cakephp/issues/9509#issuecomment-249405661
Remove a suggestion that subquery strategy would enable result buffering for hasMany and belongsToMany association types.
> Results buffering update

- en/console-and-shells/i18n-shell.rst
- fr/console-and-shells/i18n-shell.rst
The I18N extract task has a useful ``--paths`` parameter that is not documented.
> Document the `--paths` option of the i18n extract shell

- en/orm/saving-data.rst
The doc was using $data, instead of $this->request->data in the context of talking about $this->request->data, and added a note and a link to more information about the note regarding the use of newEntity() and the _accessible property.
> helpful note, and variable name update

- en/intro/conventions.rst
* Use terms consistently throughout the document. This requires the
reader to remember fewer terms and see how the conventions apply more
holistically.
* Improve formatting to match current patterns around strong/code
formatting.
Refs #4375
> Make conventions chapter more consistent.

- es/index.rst
- tr/index.rst
- zh/index.rst
The index page of the English translation (and most of the other translations as well) don't have the  "This version of the documentation is for CakePHP 3.0." anymore.  This PR brings the remaining translations in line with this.
> Remove warning message for consistency with English translation

- en/core-utility-libraries/security.rst
* Mention that mcrypt is going away, and that a pecl extension will be
required.
* Remove documentation for deprecated/non-existant methods.
Refs cakephp/cakephp#8834
> Update documentation for security

- en/controllers/components/authentication.rst
- en/controllers/components/pagination.rst
- en/controllers/components/request-handling.rst
- en/controllers/components/security.rst
- en/controllers/request-response.rst
- en/core-libraries/form.rst
- en/development/dispatch-filters.rst
- en/development/rest.rst
- en/development/routing.rst
- en/development/testing.rst
- en/elasticsearch.rst
- en/intro.rst
- en/orm/behaviors/translate.rst
- en/orm/saving-data.rst
- en/orm/validation.rst
- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/blog/part-three.rst
- en/tutorials-and-examples/blog/part-two.rst
- en/tutorials-and-examples/bookmarks/intro.rst
- en/tutorials-and-examples/bookmarks/part-two.rst
- en/views/helpers.rst
- en/views/helpers/form.rst
* Stop using deprecated properties/methods in the examples.
* Document new methods.
* Remove outdated information about Apache.
Refs cakephp/cakephp#9325
> Update documentation for PSR7 requests

- en/installation.rst
- es/installation.rst
- fr/installation.rst
- ja/installation.rst
- pt/installation.rst
- tr/installation.rst
Apple recently changed the name of his operating system. It is officially named macOS. https://www.apple.com/macos/sierra/
Update: added translations
> Change Mac OS X to macOS

- en/orm/associations.rst
- fr/orm/associations.rst
Detailling that the association must be defined in both models can be useful for newcomers.
> Add more details about how to setup a HABTM relationship

- en/core-libraries/text.rst
Prefix is what appears **before**, suffix is what appears **after**.
> Swap prefix and suffix

- en/orm/validation.rst
Multiple fields in an isUnique call creates a constraint across the fields, not a new constraint per field.
Closes cakephp/cakephp#9675
> Clarify usage of isUnique when passing in multiple fields

- en/contributing/cakephp-coding-conventions.rst
The standards appear to enforce a blank line before a function `return`, so I've updated the method definition examples to show this correctly.
> Added blank line before return

- themes/cakephp/static/css/style.css
related pull request: #4430 
0.5s delay hide submenu for unintentional mouseout.
(JavaScript Library's Behavior re-implement.)
> dropdown menu improvement: delay hide submenu on mouseout.

- themes/cakephp/static/css/responsive.css
- themes/cakephp/static/css/style.css
1.x book can't access nav menu if short window width.
(masked by version warning)
Tune padding.
I'll extract to 1.1, 1.2 branch if merged.
> Fix can't access navigation menu if short width (1.x book)

- themes/cakephp/static/css/style.css
Navigation menu doesn't display if short width that caused by #4442 's change.
Fixed Enable effect only work if width > 991px.
sorry.
> Fix navigation menu doesn't display if short width

- en/development/testing.rst
[Testing Components](http://book.cakephp.org/3.0/en/development/testing.html#testing-components)'s TestCase didn't pass to phpunit.
I find two problems in the `PagematronComponentTest` class.
* `PHPUnit_Framework_TestCase::getMock()` is deprecated PHPUnit >= 5.4.0([Release Announcement for PHPUnit 5.4.0](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.4.0#changes)), then echo warning. replaced to `getMockBuilder()`.
* `component->startup()` didn't call. then `testAdjust()` fail.
fixed code passed follow environments.
* PHP 5.6.27 + CakePHP 3.3.8 + PHPUnit 5.6.2
* PHP 5.5.38 + CakePHP 3.3.8 + PHPUnit 4.8.27
> Fix component testing example code

- jenkins.groovy
Our existing jenkins is full of bespoke job definitions. Rebuilding and using job-dsl will make our jenkins less 'precious' as we can more easily rebuild.
:warning: This is just a draft and I've not done any testing in a real jenkins and was primarily trying to capture the existing build definitions.
cc @josegonzalez
> Add Jenkins DSL

- en/models/associations-linking-models-together.rst
Normally I do not use extra 'id' primary key column in hasOne relating model.
> Make sure cascade deletes work, when using hasOne relation.

- en/orm/associations.rst
- fr/orm/associations.rst
The `select` strategy uses a separate querey, and `belongsTo` associations support the `strategy` option too.
> Fix strategy option description and add missing ones.

- en/orm/retrieving-data-and-resultsets.rst
$articles and $articlesTable are the same Table Object
> unnecessary declaration of other $articlesTable object

- en/orm/retrieving-data-and-resultsets.rst
Using $results variable in previous case with all() method call, we did not have the actual data
> resolve ambiguity of returning result set or data

- themes/cakephp/static/css/default.css
A recent sphinx/docutils upgrade has resulted in inline code blocks being marked up as `code` instead of `tt`. This has resulted in the book being ugly. Restore the book to its former glory.
> Restore formatting of code blocks.

- themes/cakephp/static/css/default.css
A recent sphinx/docutils upgrade has resulted in inline code blocks being marked up as `code` instead of `tt`. This has resulted in the book being ugly. Restore the book to its former glory.
> 2.x - Restore formatting of code blocks.

- en/controllers/components/flash.rst
- en/views/helpers/flash.rst
> Clarify where/how escaping is done in flash templates.

- en/orm/associations.rst
- Fixed incorrect explanations about the foreignKey option and the targetForeignKey option.
- Added missing colons after `**sort**` and `**through**`
- Added a sentence to the explanation about the belongsToMany association. It was on the [2.x Cookbook](http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html#belongsto), and I think it would well explain what the belongsToMany is.
@markstory Please fix my English grammar mistakes 🙇
> Fix incorrect explanation / Add missing colons

- en/core-libraries/inflector.rst
The second line of the humanize() method, in the table, was a bit broken as it had the reST cell border markups slightly misaligned.
Fixed now.
> Align Inflector table cell

- en/chronos.rst
Added $time->endOfDay(), $time->startOfYear() method calls to documentation.
> updated chronos with missing method calls

- en/tutorials-and-examples/bookmarks/intro.rst
added a clarification note for the error that can be caused by any case change to the database field which will/can cause issues to new comers to cakephp while they create the setter function
> extra note to clarify the importance of setter function member name Case

- en/views/helpers/form.rst
Correct description of default value of 'empty' attribute in Select Picker; in current API version it defaults to *false*.
Modify immediately following example by including the 'empty' attribute in order to match the output shown below it on the page.
> Correct Select default 'empty' attribute value

- en/console-and-shells.rst
I had the worst time recently trying to figure out how to exit with zero or non-zero status from my shells. The effect of `return` was to exit 0, the effect of `return 0` was to exit 1, the effect of `return 1` was to exit 1, the effect of `return 2` was it exit 1. I finally tracked down the `dispatch` method and got it sorted in my code! Here's some documentation to help the next person.
This is the Cake `dispatch` method defined in `src/Console/ShellDispatcher.php` to be clear, this is not my code, it's the thing that I'm documenting:
public function dispatch($extra = [])
{
try {
$result = $this->_dispatch($extra);
} catch (StopException $e) {
return $e->getCode();
}
if ($result === null || $result === true) {
return 0;
}
return 1;
}
> Document exit codes from Shell scripts

- en/installation.rst
Now it should be more clear that the default value means only bugfixes and changing to ~ is required to get minor version updates. Also updated previous mention of 3.2 to 3.3 to be in sync with the current cakephp version and the version snippet mentioned just above the text.
> Updated composer update explanation

- en/plugins.rst
- fr/plugins.rst
Plugins in vendor are prefixed with the vendor name, and we should have this name in the path to override it.
(I spent an hour figuring why `src/Template/Plugin/Users/Users/<view>.ctp` wasn't working for plugin CakeDC/Users)
> Note on overriding plugins views in vendor

- en/controllers/request-response.rst
* Document new interfaces.
* Include section on common mistakes with immutable objects.
Refs cakephp/cakephp#9636
> Update response chapter.

- en/controllers/request-response.rst
Refs: https://github.com/cakephp/docs/pull/4537/files#r93230226
> Improved getter examples by adding assignments

- en/core-libraries/caching.rst
Callbacks always get an event now.
Refs cakephp/cakephp#9897
> Fix afterSave examples in caching docs.

- en/contents.rst
- es/contents.rst
- fr/contents.rst
- ja/contents.rst
- pt/contents.rst
- themes/cakephp/static/css/default.css
- tr/contents.rst
- zh/contents.rst
Remove the CSS hacks we've been relying on thus far to make menu sections. By using the `:caption:` feature we can keep sections with their menus.
I've also made a few small adjustments to the sectioning. Splitting out the core plugins from reference material (appendices and global functions) felt like a good choice.
> Rebuild the left nav menus to use captions

- en/contributing/documentation.rst
I don't think there is much value in exposing our jenkins server to the world so I'm removing it from here.
Refs #4555
> Remove links to jenkins

- en/orm/associations.rst
Docs changes for https://github.com/cakephp/cakephp/pull/9676
This will switch to fluent interface but contains a note for arrays still.
Also the table of possible array keys might have to be switched to setters.
Can we maybe use a table here?
| Setter | Array key | Description |
etc?
Or how can we do it?
> Fluent interface for associations.

- config/all.py
- jenkins.groovy
- themes/cakephp/layout.html
- themes/cakephp/static/css/default.css
My thinking is that we can use the `3.next` branch in the docs as a longer-lived branch that contains docs for the 'next' version of 3.x.
I'd like to deploy these changes to `http://book.cakephp.org/3.next/en`. This will make it easier to host and link to docs for beta/rc versions that contain dramatic changes from the current 3.x release.
When we merge `3.next` into `3.0` we'll need to update `config/all.py` but as its a 1 line change I don't see this as being a big hurdle.
* I've left 3.next out of the menu. I'm not confident this is the best option, but I didn't want people 'accidentally' getting to docs for unreleased versions.
* I'm not confident I have the wording of the warning right, any help is welcome.
> Add edge version warnings to 3.next

- en/contributing/cakephp-coding-conventions.rst
Our coding standard no longer forces use of  undersore prefix for protected, private methods & properties. Refs cakephp/cakephp#9940
> Removing text dictating use of undersore prefix.

- en/orm/associations.rst
- fr/orm/associations.rst
I also fix some updated some sentences referring to the "array-way" of doing things when there were setters in the examples below.
> [fr] Follows #4437

- en/controllers/request-response.rst
- fr/controllers/request-response.rst
Follows #4537 for the French docs.
I modified some things I think were missed in the original version, be sure to check it out before merging.
> [fr] 3.4 response docs update (follow #4537)

- en/appendices/3-4-migration-guide.rst
- fr/appendices/3-4-migration-guide.rst
- fr/development/routing.rst
I removed a duplicate item in the original version.
@cake17 @antograssiot I did not translate "match" / "matching" when translating the Router parts : I did not find a suitable word. So I "frenched it up" instead. I'm open to suggestions.
Follows #4585 & #4592.
> [fr] 3.next sync

- en/orm/query-builder.rst
- fr/orm/query-builder.rst
Use an example that matches the utilization of the single
condition/value usage of the `addCase` method. Using `COUNT` will
ensure that no `NULL` value can be returned. Grouping is being removed
so that the results would be returned in a single row.
JA modifications missing (due to weird git problems).
> Fix `CASE` statement examples.

- en/tutorials-and-examples/bookmarks/intro.rst
- fr/tutorials-and-examples/bookmarks/intro.rst
- ja/tutorials-and-examples/bookmarks/intro.rst
- pt/tutorials-and-examples/bookmarks/intro.rst
This issue was raised #4165.
The problem instead of disabling `ONLY_FULL_GROUP_BY` is to solve the query. In the documentations files I changed the query for `findTagged()`. I can confirm that works on MySQL 5.6 and MySQL 5.7.
More information on how group by works in this blogpost: [GROUP BY, are you sure you know it?](https://blog.gabriela.io/2016/03/03/group-by-are-you-sure-you-know-it/).
> Fixing group by problem on Bookmark tutorial for MySQL 5.7

- en/orm/behaviors/counter-cache.rst
- fr/orm/behaviors/counter-cache.rst
In a previous PR #4605 I forgot to add a single quote. Just found out while browsing the cookbook.
> Add missing single quote - CounterCache Behavior

- en/core-libraries/text.rst
> Fix grammar

- en/views/helpers/form.rst
- en/views/helpers/number.rst
- en/views/helpers/paginator.rst
- en/views/helpers/rss.rst
- en/views/helpers/session.rst
- en/views/helpers/text.rst
- en/views/helpers/time.rst
Many of the helper's documents helper by class name, so I unified them by class name (except meta keywords)
> uniform helper name to class name in helper pages 

- en/views/helpers/html.rst
1. DOCTYPE(document type declaration) is not a tag.
2. Translated value to strict description
> improve docType in helpers/html.rst

- en/appendices/3-4-migration-guide.rst
Follows:
https://github.com/cakephp/cakephp/pull/9996
https://github.com/cakephp/cakephp/pull/9979
https://github.com/cakephp/cakephp/pull/9676
https://github.com/cakephp/cakephp/commit/945ff040408273986b27f773563c0cf4856e443d
Also, I moved deprecation notes of FormHelper into the Other Deprecations section.
> [3.4] Add more deprecations

- en/development/errors.rst
In the `BaseErrorHandler` these methods are doc block'd with `@return void`, so they should not be returning anything.
> Change method output

- en/core-libraries/internationalization-and-localization.rst
https://book.cakephp.org/2.0/en/core-libraries/internationalization-and-localization.html#translating-model-validation-errors should llink to https://book.cakephp.org/2.0/en/console-and-shells/i18n-shell.html instead of https://book.cakephp.org/2.0/en/console-and-shells.html
> Link to correct page

- en/appendices/3-4-migration-guide.rst
as in
https://github.com/cakephp/cakephp/blob/master/src/Http/ServerRequest.php#L923
> here() is also deprecated

- themes/cakephp/static/app.js
`3-next` is a temporary change, is not it?
> Cookbook search query "version" revert to 3-0

- en/appendices/orm-migration.rst
- en/orm/query-builder.rst
- fr/appendices/orm-migration.rst
- fr/orm/query-builder.rst
- ja/appendices/orm-migration.rst
- ja/orm/query-builder.rst
I've changed all uses of ```formatResults``` in all languages. Please, let me know if I shouldn't have changed some. All examples where assuming the argument implements CollectionInterface so I think it makes sense.
Related to cakephp/cakephp#10236.
> Change formatResults argument type hinting

- en/installation.rst
> Change CakePHP version installation.rst

- en/development/errors.rst
- en/orm/deleting-data.rst
- en/orm/saving-data.rst
As promised in cakephp/cakephp#10164, here are the docs for `Cake\ORM\Table::saveOrFail()` and `Cake\ORM\Table::deleteOrFail()`.
I hope I covered everything necessary.
On a site note, using the provided Dockerfile worked like a charme 👍
> Add docs for saveOrFail and deleteOrFail

- themes/cakephp/static/app.js
- themes/cakephp/static/css/default.css
- themes/cakephp/static/search.js
It is an improvement proposal of search function. Please review.
* Display "searching..." message during loading. (search bar and /search.html)
* "No matches found" is displayed when /search.html
It solves the problem that it can not be determined whether the search page is loading or 0 search results.
These behaviors work as follows:
* Scroll to the top of the page when clicking the page link.
If merged, it will also backport to other branches.
> Improve Docs Search

- en/plugins.rst
Going through the doc I noticed that this notation is missing.
> Add $this->loadModel() notation

- en/appendices/3-4-migration-guide.rst
Request::getParam() does not work that way
> [en] Update 3.4 migration guide

- en/controllers/request-response.rst
> Document how to use streaming responses.

- ja/controllers/request-response.rst
> [ja] update request-response.rst

- en/installation.rst
> Add reference to Oven

- en/controllers/request-response.rst
I tried to clarify the use of `withBody()`.
I also fixed some mistakes and restructured the response section a bit.
> Clarify how to handle response bodies and add withStringBody docs

- es/tutorials-and-examples/blog-auth-example/auth.rst
- es/tutorials-and-examples/blog/blog.rst
- es/tutorials-and-examples/blog/part-three.rst
- es/tutorials-and-examples/blog/part-two.rst
- es/tutorials-and-examples/bookmarks/intro.rst
- es/tutorials-and-examples/bookmarks/part-two.rst
I propose this change in the titles of the tutorials in the spanish
translation to follow the same name structure of the english version
And add the meta title in some pages that didn't have it
> [es] Fix the tutorials titles

- en/development/configuration.rst
Ref: https://github.com/cakephp/cakephp/issues/10302
> 3.x How to disable auto-tables

- en/core-libraries/form.rst
- en/elasticsearch.rst
- en/orm/behaviors/translate.rst
- en/orm/behaviors/tree.rst
> [en]Replaced FormHelper's "input" with "control" throughout the document.

- en/controllers/components/pagination.rst
Include information that the paginate property must be correctly configured when paginating multiple queries. Fixes #4769.
> Update pagination.rst to fix #4769

- en/core-utility-libraries/string.rst
For some reason prefix and suffixed are used backwards while explaining truncate and tail
> Prefix and suffix are backwards

- en/controllers/components.rst
While reading the documentation i stumbled upon this example on how to use components and it confused me a little since the cookie component is mentioned and initialized but never used. So I figured we should either change the example to use the cookie component or just remove it. Since I could not think of a use case (in this context) for the cookie component I removed it.
> Remove unused component in the example

- en/appendices/glossary.rst
- en/intro/conventions.rst
The new ORM conventions section has confused a few people. The feedback I've received about this section is that it belongs better in the glossary.
> Reorganize the glossary and move ORM conventions in.

- .travis.yml
By not building the PDFs we shouldn't run into as many build failures on pull requests. This does mean that we might have some surprise failures when building the docs, but I'd rather not have many false negatives in pull requests.
> Make build run faster.

- en/development/routing.rst
While the heading refers to the `Router::extensions()` method, the
description only covered the `RouteBuilder::extensions()` method.
Needs FR and JA translations.
> More complete extension routing description.

- en/orm/saving-data.rst
the two blocks related to associations were not following each other under title "Converting Request Data into Entities"
> fix the order of text blocks

- en/core-libraries/collections.rst
sortBy method default order is actually descending, not ascending.
Actually, It may be better to change the default order to ascending, as I see it more natural and also more standard (as SQL works, for example), but if we do that we make break lots of applications that use the default order in the current way.
> Fix default sortBy order that is descending not ascending

- en/views/helpers/form.rst
Was helping someone out in Slack today who was stuck on widgets. The only thing that was missing seemed to be creating the custom string template for the example widget.
> Include note about string template in Widget example

- en/appendices/3-5-migration-guide.rst
- en/orm/database-basics.rst
> Add migration docs for small/tinyint

- en/core-libraries/validation.rst
- fr/core-libraries/validation.rst
- ja/core-libraries/validation.rst
Validator is already provided as an argument to the function.
The docs mention that you can combine validators. In that case it seems like these lines can break the chain.
> Don't show creation of validators on the fly

- en/controllers/request-response.rst
> Add examples for pre 3.4.0

- en/core-utility-libraries/hash.rst
{*} is found in the docstring of ``Hash::extract()`` but not in the docs.
```php
/**
* Gets the values from an array matching the $path expression.
* The path expression is a dot separated expression, that can contain a set
* of patterns and expressions:
*
* - `{n}` Matches any numeric key, or integer.
* - `{s}` Matches any string key.
* - `{*}` Matches any value.
* - `Foo` Matches any key with the exact same value.
* ...
*/
public static function extract(array $data, $path) {
...
}
```
> Add documentation for {*}

- en/core-libraries/validation.rst
Updated to reflect changes made in the latest release of the framework with accessor methods.
> Use the new accessor methods

- en/core-libraries/internationalization-and-localization.rst
> Update locale filter docs to include middleware example.

- en/appendices/3-5-migration-guide.rst
@markstory Sorry, I saw your commit only when I fetched and merged the upstream changes after I've already written the notes :)
I've pushed it anyways, as the "_Previously all but the last record would be removed_" bit could be a little confusing, given that empty arrays already previously wiped everything as expected, and other "empty" values would have caused an exception...
Might be a little long for a single bullet point, it feels like a hybrid of behavior change and new feature.
> 3.next - Clarify changes made in cakephp/cakephp#10479

- en/development/routing.rst
> Fix copy-paste example for resource route URL inflection

- en/installation.rst
I made the Url rewrite setting of nginx simple.
The following trouble was reported on Slack Japanese channel. (Reported by @shinderuman )
> [Installation](https://book.cakephp.org/3.0/en/installation.html#nginx)
> ```
> rewrite 301 http://www.example.com$request_uri permanent;
> ```
> In this setting, redirects if '301' is included in the URL such as 'http: //my.domain/foo/edit/10301'
But trying to fix it will cause a redirect all.
Initially, in this alternate configuration, the server directive is put together into one, but in the [linked nginx document](http://nginx.org/en/docs/http/converting_rewrite_rules.html), it is said that it is the right way to divide by domain.
I want to improve as follows
* Lose alternative configuration and make it universal config.
* Specify configurations …
> Improve url rewrite by nginx

- en/tutorials-and-examples/bookmarks/intro.rst
- es/tutorials-and-examples/bookmarks/intro.rst
- fr/tutorials-and-examples/bookmarks/intro.rst
- ja/tutorials-and-examples/bookmarks/intro.rst
- pt/tutorials-and-examples/bookmarks/intro.rst
- ru/tutorials-and-examples/bookmarks/intro.rst
- tr/tutorials-and-examples/bookmarks/intro.rst
- There is a bug in the exising findTagged function.  When calling the
function without any tags specified all bookmarks are returned, rather
than the bookmarks that have no associated tags.
- The alternative query (tags specified) was also adjusted to use a
similar approach - specifying the conditional after the join, rather
than in it, IMHO making the logic a little clearer.
> Fix findTagged "no tags" query in bookmarks tutorial.

- en/tutorials-and-examples/bookmarks/intro.rst
- fr/tutorials-and-examples/bookmarks/intro.rst
- The function has been changed several times without adjusting
the descriptive paragraph.
- Fixed now in English and French.
A follow up to the recent fixes to the findTagged function in PR https://github.com/cakephp/docs/pull/4920.
> Fix description of findTagged function in bookmarks tutorial.

- en/appendices/3-5-migration-guide.rst
- en/console-and-shells.rst
Document the deprecations merged last night.
> More deprecations

- themes/cakephp/static/app.js
It is a PR to fix bug in Cookbook site.
If the width of the browser is narrow, the following links will not work.
Similar bugs exist in other branches and bakery, api site too, so if you merge it will also request that.
> Enable anchor of submenu(When the width is narrow).

- en/appendices/3-5-migration-guide.rst
- en/views/helpers/paginator.rst
> Add documentation for limitControl()

- en/core-libraries/email.rst
Restore backwards compatible examples and use deprecated annotations to indicate deprecated methods where methods have specific sections.
Refs cakephp/cakephp#10605
> Restore 3.3 compatible examples.

- en/views/helpers/form.rst
- en/views/helpers/html.rst
- fr/views/helpers/html.rst
- ja/views/helpers/html.rst
Filenames must be passed without extension.
Needs JA translation.
> 3.x - Fix/clarify templates config file referencing.

- en/orm/database-basics.rst
- en/orm/saving-data.rst
update _initializeSchema() example to not use deprecated class name
> update _initializeSchema() example

- en/core-libraries/email.rst
@chinpei215 let me know that I had made a mistake in my previous changes as there wasn't a layout() method in previous versions.
> Fix email methods.

- fr/controllers/request-response.rst
The first code block under the "Accéder aux Paramètres Querystring" section is not correctly formatted
> Fix the code block layout

- en/development/testing.rst
Refers: https://github.com/cakephp/cakephp/issues/10518#issuecomment-294317455
Opted for a warning instead of just a note, as it would break tests in newer PHPUnit versions, if one misses this bit.
> Add warning about staticExcepts() not being present in PHPUnit anymore 

- en/appendices/3-5-migration-guide.rst
- en/controllers/components/cookie.rst
- en/controllers/components/csrf.rst
- en/controllers/middleware.rst
> Document CSRF middleware.

- en/controllers.rst
- en/controllers/components/csrf.rst
- en/controllers/components/security.rst
- en/core-libraries/httpclient.rst
- en/development/dispatch-filters.rst
- en/development/testing.rst
- en/tutorials-and-examples/blog/part-two.rst
- en/tutorials-and-examples/cms/articles-controller.rst
- Cake\Network\Request is renamed to Cake\Http\ServerRequest.
- Cake\Network\Response is renamed to Cake\Http\Response.
- Cake\Network\Http\Client is renamed to Cake\Http\Client.
- Cake\Network\Http\FormData is renamed to Cake\Http\Client\FormData.
> [en] fix the class name and the namespace.

- en/controllers/middleware.rst
- en/development/routing.rst
I've not documented the Application class hook yet, as I want to think more about how to document that class more holistically.
Refs: cakephp/cakephp#10646
> 3.next - Scoped middleware docs

- en/development/testing.rst
> Add docs for testing flash messages.

- ja/development/testing.rst
> [ja] update testing.rst

- en/models/saving-your-data.rst
These headings were missing `:php:meth:` and therefore mis-rendered the navigation. I removed the code fence entirely to make it similar with other areas of the docs (e.g., retrieving your data, which has several unfenced code headers).
before:
after:
> Fixed navigation on models: saving your data

- en/development/testing.rst
> `phpdbg` is generally faster at generating coverage
Is this too opinionated? I mean, it *is* faster, but perhaps not in all cases.
Here's my app's performance, for example (had to reinstall xdebug, forgot how fast `phpdbg` actually was 😄 ):
> Added note about generating coverage with phpdbg

- en/console-and-shells/cron-jobs.rst
I recently solved a issue with cron jobs on my shared hosted server. By following these docs, I could not solve the problem. In this PR I have added a description that might work for some developers on shared hosting.
If you like whats added, I hope the position of what is added and the formatting looks okay.
> Adding a guide for cron jobs on shared hosting

- en/core-libraries/hash.rst
- fr/core-libraries/hash.rst
- ja/core-libraries/hash.rst
the $keyPath of Hash::combine() has no default argument value.
https://api.cakephp.org/3.4/class-Cake.Utility.Hash.html#_combine
> [en][fr][ja] fix the method definition.

- ja/console-and-shells/cron-jobs.rst
- ja/development/testing.rst
> [ja] sync 3.0 docs.

- en/tutorials-and-examples/cms/tags-and-users.rst
This is probably unnecessary but it's neat, and uses a lesser knowing feature that is cooler than just grabbing the passed args 😎 
Optional of course, just thought I'd suggest.
> CMS Tutorial alternate edit method

- en/tutorials-and-examples/cms/database.rst
I started going through the tutorial from scratch but couldn't insert the tables with the provided SQL
> Error Code: 1071. Specified key was too long; max key length is 767 bytes
Updated the length on columns used as keys to meet length requirements as utfmb8 uses 4 bytes per char not 3.
see: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes#comment69153099_16820166
> Using varchar(191) on unique key columns

- en/orm/database-basics.rst
Some minor improvements to the custom db type example.
- clarified what type methods do (copy/paste)
- fixed incorrect reference when mapping custom type
- added note about json type in 3.3
> JsonType example updates

- en/orm/database-basics.rst
Without this change the user will get an "Call to a member function types() on float" (or string or whatever).
The Values must be passed as array to the second parameter of FunctionExpression; 
until now they are passed in the example as second and third, which lead to interpreting the second value as "type".
> Fixed Example for custom Point Type

- en/orm/entities.rst
change to use getError, getErrors, setError, setErrors
> Update Validation Errors section for 3.4.0 deprecation

- en/appendices/3-5-migration-guide.rst
- en/development/routing.rst
Update the documentation for the new fluent methods on Route. I've also broken the new features section up by package as it was becoming a wall of un-scanable text.
I've tried to follow the latest decisions on documenting the most recent version, and including previous version compatibility in follow up examples or in comments.
> Document fluent route changes.

- themes/cakephp/static/css/style.css
Fixes https://github.com/cakephp/docs/issues/4024
Tested in Chrome 59 Mobile Inspector
> Autobreak too long words on direct p children of .section

- en/controllers/components/authentication.rst
> Add link to awesome Authentication & Authorization

- en/bake/usage.rst
I deliberately changed from a specific command help to all command help., as this output also shows this option, anyway:
> To see help on a subcommand use `cake bake.bake [subcommand] --help`
> Update console output for bake command

- en/appendices/3-5-migration-guide.rst
- en/development/routing.rst
- en/plugins.rst
> Add documentation for loadPlugin()

- en/development/testing.rst
- en/orm/deleting-data.rst
- en/orm/saving-data.rst
- fr/appendices/3-4-migration-guide.rst
- fr/chronos.rst
- fr/contributing/code.rst
- fr/core-libraries/email.rst
- fr/development/errors.rst
- fr/development/testing.rst
- fr/index.rst
- fr/installation.rst
- fr/orm/associations.rst
- fr/orm/deleting-data.rst
- fr/orm/saving-data.rst
- fr/orm/validation.rst
- fr/plugins.rst
- fr/views/helpers/paginator.rst
Only a small 100 PR to catch up with (and that's for 3.0 only :smile:)
I took the liberty of modifying some formatting when it felt better on the original version.
Feel free to revert them if you feel those modifications are useless.
Follows #4694, #4703, #4704, #4706, #4712, #4718, #4720, #4721, #4722, #4734, #4742, #4744, #4749, #4750, #4751, #4752
> [fr] First batch of French translation

- en/core-libraries/email.rst
Mark first example with deprecated for 3.4.0.
> .. deprecated:: 3.4.0

- en/development/configuration.rst
- fr/controllers/request-response.rst
- fr/core-libraries/email.rst
- fr/development/configuration.rst
- fr/installation.rst
- fr/orm/table-objects.rst
- fr/views/json-and-xml-views.rst
Follows #4755, #4762, #4746, #4771, #4773, #4777, #4779 and add missing translations.
> [fr] Another translations batch

- en/models/model-attributes.rst
Small fix to make it more readable that Domain is a model.
This came up on the forum:
http://discourse.cakephp.org/t/what-does-domain-mean-in-model-context-cakephp-2/2711
> Capitalize classname

- en/appendices/3-5-migration-guide.rst
- en/views/cells.rst
Include an example of usage in View Cells. Does this look reasonable @ADmad?
Refs cakephp/cakephp#10718
> Document standalone paginator.

- en/orm/behaviors.rst
References to deprecated \Cake\Utility\Inflector::slug() updated to current \Cake\Utility\Text::slug().
Missing closing parenthesis added to last code example.
> Code examples corrections

- en/appendices/glossary.rst
- en/tutorials-and-examples/bookmarks/part-two.rst
- fr/appendices/glossary.rst
- fr/controllers/components.rst
- fr/controllers/components/authentication.rst
- fr/controllers/components/pagination.rst
- fr/core-libraries/collections.rst
- fr/core-libraries/form.rst
- fr/core-libraries/hash.rst
- fr/development/routing.rst
- fr/elasticsearch.rst
- fr/intro/conventions.rst
- fr/orm/behaviors/translate.rst
- fr/orm/behaviors/tree.rst
- fr/orm/entities.rst
- fr/orm/saving-data.rst
- fr/tutorials-and-examples/blog-auth-example/auth.rst
- fr/tutorials-and-examples/blog/part-three.rst
- fr/tutorials-and-examples/blog/part-two.rst
- fr/tutorials-and-examples/bookmarks/part-two.rst
- fr/views/helpers/paginator.rst
Follows #4787, #4784, #4790, #4794, #4795, #4796, #4803, #4807, #4810, #4812, #4821, #4824, #4826, #4822 
There are some modifications on the english versions as well.
> [fr] Another batch of French translations

- en/orm/validation.rst
It is intolerant against non existing keys.
Aka such a check is **not** inside class ValidCount:
```php
if (!$entity->has($this->_field) && array_key_exists('allowNulls', $options) && $options['allowNulls'] === true) { return true; }
```
> Clarify validCount

- en/orm/query-builder.rst
@lorenzo when writing this I thought that there should possibly be Query::PREPEND and Query::APPEND (latter is default behavior) to control Order building...
> Overwrite Order By

- en/controllers/components/authentication.rst
Since internally `$this->Flash->set($message, $this->_config['flash'])` is used, element is also an option to customize the authError flash message.
> Element option for authError flash messages

- en/appendices/3-5-migration-guide.rst
- en/core-libraries/caching.rst
Since engines now default to falling back to the `NullEngine`, I felt it important to document in the Behavior Changes section of the migration docs.
> Documenting cache fallback

- en/appendices/3-5-migration-guide.rst
- en/development/testing.rst
Document a few more new features from 3.5.
> 3.next - New features

- en/appendices/2-10-migration-guide.rst
In the [CakePHP 2.10 migration guide](https://book.cakephp.org/2.0/en/appendices/2-10-migration-guide.html), "abstract types" are used. It can't be found on other pages.
I thought that it would be better to unify it to "internal data types" used on the [Testing](https://book.cakephp.org/2.0/en/development/testing.html#creating-fixtures) page.
How is it?
> [2.x] Use "internal data types" instead of "abstract types"

- en/views/helpers/form.rst
- fr/views/helpers/form.rst
This is a full sync of the gigantus PR #4598.
Also deals with #4745, #4834, #4856, #4859, #4862, #4913 and #4959.
Best wishes of luck to the one / those that will review this :smile:
> [fr] Full sync of #4598

- en/appendices/3-5-migration-guide.rst
- fr/appendices/3-5-migration-guide.rst
Full translation of the 3.5 migration guide.
I voluntarily left the references to next section out for the moment as they are not translated yet.
I'll update the migration guide as I translate the rest of the 3.next doc.
> [fr] Full 3.5 migration guide translation

- en/console-and-shells.rst
- en/core-libraries/validation.rst
- en/views/cells.rst
- fr/console-and-shells.rst
- fr/core-libraries/validation.rst
- fr/development/routing.rst
- fr/development/testing.rst
- fr/orm/database-basics.rst
- fr/orm/validation.rst
- fr/views/cells.rst
- fr/views/helpers/paginator.rst
- fr/views/helpers/rss.rst
Follows #4801, #4831, #4904, #4927, #4948, #4951, #4999, #5003, #5040, #5060.
As usual, I did some minor edition in the original version of the doc.
> [fr] First round of 3.next translations

- en/console-and-shells/schema-management-and-migrations.rst
I wasted a little bit of time because I could not do it even with the ``--dry-run`` option.
> [2.x] specify --dry option in schema shells create/update section

- en/controllers/middleware.rst
- en/core-libraries/httpclient.rst
- fr/controllers/components/cookie.rst
- fr/controllers/components/csrf.rst
- fr/controllers/middleware.rst
- fr/core-libraries/httpclient.rst
- fr/core-libraries/internationalization-and-localization.rst
- fr/development/routing.rst
> [fr] A few new 3.next translations

- en/plugins.rst
- fr/appendices/3-5-migration-guide.rst
- fr/core-libraries/caching.rst
- fr/development/routing.rst
- fr/plugins.rst
> [fr] Last sync for 3.next

- en/development/testing.rst
Closes #5071 
This PR expects https://github.com/cakephp/cakephp/pull/10850 to be merged.
> Added section on Console Integration Testing

- en/appendices/3-5-migration-guide.rst
- en/console-and-shells.rst
Add brief documentation on the console() hook. I plan on adding a more holistic section for the application class. Just not sure where to put it just yet.
Refs cakephp/cakephp#10716
> Add console hook documentation.

- en/core-libraries/internationalization-and-localization.rst
- fr/core-libraries/internationalization-and-localization.rst
Follows #5098.
While at it, I fixed "he read" to "he reads" in the original translation.
Note to my fellow french reviewers : J'ai volontairement traduit "first letter" par "premier courrier". Même si "lettre" aurait été valable, ça aurait un peu rendu l'exemple creux (parce qu'en Français, c'est comme en anglais). Je me suis dit que "courrier" collait bien ici.
> [fr] Follows #5098

- en/orm/behaviors/tree.rst
Previous pull request was misleading. Keeping the docs to make passing conditions obvious, but refactoring to encourage better code. https://github.com/cakephp/docs/pull/5102#issuecomment-316052886
references: https://github.com/cakephp/docs/pull/5102#issuecomment-316052886 and https://github.com/cakephp/cakephp/issues/10919
> Update tree.rst - previous update was misleading

- en/tutorials-and-examples/cms/authentication.rst
I haven't forgotten about this. One day I might even be finished it.
> Add another chunk to the CMS tutorial.

- en/core-libraries/internationalization-and-localization.rst
"read" is a past tense in the English sentence.
> Fix a German sentence in a .po file example

- en/orm/saving-data.rst
I think this section is duplicated and a bit outdated. At least the second example doesn't work in the latest versions.
> Remove duplicated and outdated section

- en/appendices/3-5-migration-guide.rst
- en/development/routing.rst
Add deprecations added in cakephp/cakephp#10943
> Update 3.5 migration guide for routebuilder.

- en/orm/table-objects.rst
I added an example on how to stop the event, as I saw/got that question a few times lately.
> Add examples to showcase how to stop events

- en/appendices/3-5-migration-guide.rst
Refs cakephp/cakephp#10691.
Also, `Query::valueBinder()` and `QueryTrait::eagerLoaded()` are half-deprecated methods.
> Updated deprecation notes for 3.5

- en/appendices/3-5-migration-guide.rst
- en/development/testing.rst
I noticed this was missing when I was perusing the docs last night.
> Added 3.5 migration note on ConsoleIntegrationTestCase

- en/appendices/3-5-migration-guide.rst
- en/core-libraries/collections.rst
> Add docs for collection avg & median.

- en/appendices/3-5-migration-guide.rst
- en/development/configuration.rst
Shuffle sections around so environment variables are higher up.
> Add documentation for environment variables.

- themes/cakephp/static/css/default.css
I found this border added visual noise and didn't make the book easier to read.
New style looks like:
> Remove border from definition lists.

- en/elasticsearch.rst
The example code for a `Cake\ElasticSearch\Type` was missing a `use` statement
> Added missing use statement

- en/appendices/3-5-migration-guide.rst
- fr/appendices/3-5-migration-guide.rst
- fr/core-libraries/collections.rst
- fr/development/configuration.rst
- fr/development/routing.rst
Follows #5121, #5124, #5126, #5127, #5128.
> [fr] 3.next - Follows #5121, #5124, #5126, #5127, #5128

- en/orm/validation.rst
The doc says, "use two rules", but three rules are written actually. Since the third rule is not related to the range rules, it should be written separately.
Refs #5002
> Separate a code example of validCount rule

- en/core-libraries/collections.rst
I changed the directive to `csv-table` as it's much easier to maintain, although the source isn't as easy to read. `csv-table` comes with the caveat that the number of columns per row isn't immediately visible nor enforced. If that's a deal killer we can close this PR.
> Alphabetized collection methods table

- en/console-and-shells/cron-jobs.rst
to the cron line by adding the -d parameter instead of (the need to) specify a whole php.ini path and file.
> Make it easier to add the setting

- en/orm/entities.rst
Ref: https://github.com/cakephp/cakephp/issues/10993#issuecomment-319984886
@markstory Let me know if this is not 100% correct... then I will fix it.
> Educate bout accessors being run before persisting

- en/development/configuration.rst
I doubt custom configuration engines are used often enough to take up this much space in the book. Push most of these examples in to the API docs.
Refs cakephp/cakephp#11034
> Remove fluff from configuration chapter.

- en/plugins.rst
I found this was missing from the documentation today. I've tried to guess because I don't have the time or inclination to install, configure and learn Docker.
I tried to build it using `make`, but it seems to be missing all the stylesheets, so I can only hope that it'll look right.
> Added a note about plugins with prefix templates

- en/controllers/middleware.rst
... everything else breaks copy+paste in horrible ways.
> Use correct single-quotes

- en/console-and-shells.rst
I'm always looking this up, and it appears to be missing from the documentation. I've not included all the tags present in the `ConsoleOutput` class, as many are the same colour, so it would duplication.
Let me know if you think it's worth linking to the relevant api section from the docs, and I can add that link.
> Added success

- en/tutorials-and-examples/bookmarks/part-two.rst
At the end of the 'Add Login" section the tutorial rightfully suggests that "you should now be able to login." This is followed by a note about how to create a user with a hashed password if one was not previously created. This note is followed by another line about being able to log in that is redundant to the first. As a reader I would expect to be able to login after completing the proposed fix.
An alternative would be to move the second recommendation into the note itself and say something to the effect of "After creating a user with a hashed password you can uncomment the auth code and you should now be able to log in with the newly created hashed password user," however, this may be excessive and unnecessary for a concise tutorial on beginning CakePHP
> Remove redundant login suggestion

- ja/tutorials-and-examples/blog/part-two.rst
Fixed Japanese explanation.　日本語の説明文を修正しました。
Validation::notEmpty() is deprecated. Use Validation::notBlank() instead.
> [ja] Update part-two.rst

- en/development/configuration.rst
We are now throwing an exception when persistent is set to true with the SqlServer driver.  This update explains the change.
> Update information about persistent and Sqlserver

- en/orm/database-basics.rst
CakePHP now throws an exception when persistent is set to true with SQL Server.  This update explains that fact.
> Note about SQL Server not supporting persistent

- en/models/datasources.rst
PDO drivers for SQL Server are now available on both Windows and *nix operating systems.  Also added a link to the driver's github page, which is the best source of information about the driver IMHO.
> Update information about PDO driver for SQL Server

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
Just a minor fix to the flow of the tutorial where `user_id` was previously hardcoded in the table's `beforeSave`. This changes lines up the code with what the tutorial is telling the user.
> Moved hardcoded user_id to articles controller add method

- en/phinx/migrations.rst
Reading through docs I noticed a typo and thought, why not PR?
Thanks for what you're doing!
> Fixed create and drop typo in the index fields

- en/orm/associations.rst
I got caught out here, and thought 'name' meant a FQCN, so I used `ExamplesTable::class` which produced a broken query. So just wanted to try and clarify that it's the registry alias, so would be `Examples` in this instance.
> Try to clarify 'through' table expectation

- en/orm/retrieving-data-and-resultsets.rst
I've tried passing a condition to contain, like it was shown in the manual, but I didn't got it to work. The manual said I had to pass contain('myModel', function($q){...}), but instead I had to use an array like contain(['myModel' => function($q){...}]);
I'm using cake 3.4.13
> Passing conditions to contain()

- en/controllers/middleware.rst
httpOnly is an option to set and should be described here.
> Add httpOnly option to CSRF options

- en/intro/cakephp-folder-structure.rst
We should link to Composer's website as people reading this page could not have visited the installation guide yet where they would have learned about Composer already.
> Link to Composer

- en/phinx/migrations.rst
I'm not sure if this is right, I was reading the documentation and the statement that 'up' methods migrate down automatically seemed wrong to me, since this paragraph is about the change method. And it makes much more sense that change migrates down automatically, I guess. :)
> Clarification of migration documentation

- en/installation.rst
Core PR: https://github.com/cakephp/cakephp/pull/11328
RDBMS Docs:
- https://mariadb.com/kb/en/library/unicode/ (utf8mb3 utf8mb4)
- https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html
- MariaDB Versions: https://mariadb.org/feedback_plugin/stats/major_version_breakdown/
p.s.: I am also okay with setting MariaDB version a lot higher, aka to 10.0 or 10.1 as we did not support it "officially" so far.
> Up MySQL min version, add MariaDB version

- en/models/associations-linking-models-together.rst
In the detailed example, Recipe HABTM Ingredient, not Tag.
> HATBM example has erroneous Model mentioned

- ja/controllers/components.rst
:bow:
https://github.com/cakephp/docs/blob/3.0/en/controllers/components.rst#configuring-components
```
Configuration for these components,
and for components in general, is usually done via ``loadComponent()`` in your
Controller's ``initialize()`` method or via the ``$components`` array::
```
> [ja] Fix translation configuring Components

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/database.rst
- en/tutorials-and-examples/cms/installation.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
The following warning is displayed in the latest build log and the build failed in Travis.
https://travis-ci.org/cakephp/docs/builds/288987425
```
tutorials-and-examples/cms/installation.rst:117: WARNING: unknown document: database
tutorials-and-examples/cms/database.rst:170: WARNING: unknown document: articles-controller
tutorials-and-examples/cms/articles-controller.rst:551: WARNING: unknown document: tags-and-users
```
It seems to be caused by the relative reference link in the cms tutorial. So I fix it.
(However, the relative reference link will work... 😕 )
> Remove build warnings with relative references.

- en/views/helpers/breadcrumbs.rst
:bow:
https://github.com/cakephp/cakephp/blob/master/src/View/Helper/BreadcrumbsHelper.php#L43
```php
protected $_defaultConfig = [
'templates' => [
'wrapper' => '<ul{{attrs}}>{{content}}</ul>',
'item' => '<li{{attrs}}><a href="{{url}}"{{innerAttrs}}>{{title}}</a></li>{{separator}}',
'itemWithoutLink' => '<li{{attrs}}><span{{innerAttrs}}>{{title}}</span></li>{{separator}}',
'separator' => '<li{{attrs}}><span{{innerAttrs}}>{{separator}}</span></li>'
]
];
```
> Fix breadcrumbs default declaration code

- en/orm/associations.rst
Add comment to explain that setForeignKey() is only for Cake 3.4
I can also modify french version if you want.
> [EN] Update setForeignKey() method for non 3.4 cake version users

- en/orm/saving-data.rst
Just wanted to amend the tags examples so they both use the same fields, for clarity, and to avoid the possible thought that the key of the array is the name of the entity.
> Fixed consistency

- en/core-libraries/components/authentication.rst
- fr/core-libraries/components/authentication.rst
- ja/core-libraries/components/authentication.rst
According to [this comment](https://github.com/cakephp/cakephp/blob/24e4acf9a38dc6a3a96fa5bebf9939988e715d77/lib/Cake/Controller/Component/Auth/DigestAuthenticate.php#L47), `env('SCRIPT_NAME')` should become `env('SERVER_NAME')` but [here](https://github.com/cakephp/cakephp/blob/24e4acf9a38dc6a3a96fa5bebf9939988e715d77/lib/Cake/Controller/Component/Auth/DigestAuthenticate.php#L203) there is not default value.
> - Correct the DigestAuthenticate::password() default third parameter

- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/blog/part-three.rst
- en/tutorials-and-examples/blog/part-two.rst
The blog tutorial referenced methods only available to CakePHP greater than or equal to 3.4.0.
Added notes to the tutorial to aid in debugging when calling methods from < 3.4 Installations.
Since the code was referenced in a tutorial for copy-pastable code, I put them in a comment. I followed syntactical and verbiage examples from https://book.cakephp.org/3.0/en/controllers/request-response.html.
> Added Notes for Request & Response Changes

- fr/tutorials-and-examples/cms/authentication.rst
Strange that the french translation has this extra line:
`$this->loadComponent('Flash')`
It is already present in the original code and referred to by the commentary
`// Code existant [Existing code]`
A distracted beginner might end up with the same statement twice.
> Update authentication.rst french translation

- fr/tutorials-and-examples/cms/articles-controller.rst
Missing statement in the french translation.
`echo $this->Form->control('user_id', ['type' => 'hidden']);`
This line is referred to at the end of the tutorial as we're asked to remove it.
French users might be confused if they don't find it in the template file _edit.ctp_.
Regarding this issue, japanese translation is ok.
> Update articles-controller.rst french translation

- en/appendices/3-6-migration-guide.rst
- en/core-libraries/caching.rst
- en/development/sessions.rst
Don't document/endorse the usage of a cache backend that will be removed.
Refs cakephp/cakephp#11421
> Remove xcache from documentation.

- en/orm/behaviors/counter-cache.rst
As in `CounterCacheBehaviorTest::testLambdaSubquery()`, the return value actually does not _need_ to be a 'count value'.
Added a note about the $table parameter as well.
> Clarifications on callback method

- en/appendices/3-6-migration-guide.rst
- en/controllers/components/pagination.rst
- en/development/configuration.rst
- en/development/errors.rst
- en/tutorials-and-examples/blog/part-three.rst
- en/views/json-and-xml-views.rst
- es/tutorials-and-examples/blog-auth-example/auth.rst
- es/tutorials-and-examples/blog/part-three.rst
- fr/controllers/components/pagination.rst
- fr/development/configuration.rst
- fr/development/errors.rst
- fr/tutorials-and-examples/blog/part-three.rst
- fr/views/json-and-xml-views.rst
- ja/controllers/components/pagination.rst
- ja/development/configuration.rst
- ja/development/errors.rst
- ja/tutorials-and-examples/blog/part-three.rst
- ja/views/json-and-xml-views.rst
- pt/development/configuration.rst
- pt/tutorials-and-examples/blog/part-three.rst
- ru/tutorials-and-examples/blog/part-three.rst
I've updated usage of http exception to reflect new classnames. I could use some help on the translations.
Refs cakephp/cakephp#11464
> 3.next - Document network exception moves

- en/controllers.rst
Not highlighted variable name without dollar sign and missing dot at the end of the paragraph.
> [en] small typo corrections

- ja/plugins.rst
Japanese translation file `plugins.rst` has typo. Using `bootstrap` instead of `bootstarp`.
> modify: Type mistake of `ja/plugins.rst`

- en/tutorials-and-examples/cms/authentication.rst
The list of tags becomes unnecessary after [Improving the Tagging Experience](https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/tags-and-users.html#improving-the-tagging-experience).
Since has been deleted from the add action, it has been deleted from the edit action.
> CMS Tutorial - Delete unnecessary codes

- ja/core-libraries/global-constants-and-functions.rst
Japanese translation file global-constants-and-functions.rst has typo. Unify `デバッグ` translation text of `debug`.
> modify: Type mistake of `ja/global-constants-and-functions.rst`

- en/controllers/components/authentication.rst
Text::uuid is not cryptographically secure.
> Change api_key_plain generation

- en/development/errors.rst
Based on the feedback in #5539 I've made a few changes
* Reorganized the docs so that exception listing is at the bottom as I feel it is less frequently used.
* Give more context on why one might use each extension point in the error handling process.
* Give more information on view template context.
* Use clearer headings.
Refs #5539
> Improve the error handling docs.

- en/development/errors.rst
There is a warning when `make html-en`:
``
/path/to/docs/en/development/errors.rst:87: WARNING: Unknown directive type "info".
``
> Fix warning when make html-en

- en/core-libraries/helpers/form.rst
There was an [attribute option in the API docs](https://api.cakephp.org/2.10/class-FormHelper.html#_select) which was missing from the documentation.
> Added a missing attribute for showParents

- en/views/helpers/form.rst
The example of customize nestingLabel template is ambiguous: lacks the placeholder {{hidden}}.
> Fix nestingLabel template example

- en/orm/saving-data.rst
I found the use of the same field name and value in both the fields array and conditions array confusing. I have sought to improve this by clarifying that the fields are an array of `'field' => $newValue` and the conditions are an ORM conditions array.
> Clarified the language

- en/core-libraries/validation.rst
I wanted to capture that if you return a string in your closure that becomes your validation message. It wasn't documented. Took me a good while to find in the code. Hope this helps others who are looking to provide a more context specific error message.
> Return types for custom validation

- es/tutorials-and-examples/blog/blog.rst
Borrado de un párrafo repetido. Estos eran los párrafos, se ha borrado el segundo: 
Echa un vistazo a :doc:`las convencionnes </intro/conventions>` para más información, pero basta decir que nombrando nuestra tabla 'articles' automáticamente lo vincula a nuestro modelo Articles y que campos llamados modified y created serán gestionados automáticamente por CakePHP.
Al llamar 'articles' a nuestra tabla de artículos, estamos diciendo a CakePHP que vincule esta tabla por defecto al Modelo 'Articles', e incluiya los campos 'modified' y 'created' con ese nombre, los cuáles serán automáticamente administrados por CakePHP.
> Párrafo repetido. (Deleting a repeated paragraph)

- en/controllers/components/cookie.rst
I had no idea that Cookies were now part of the Request instance, and this part of the docs lead me to believe that I had to encrypt my cookies, when really all I wanted was to read them.
Hopefully this edit will go some way to clarifying the two use-cases for the Cookies.
> Added a link for regular cookies as well as encrypted ones

- en/plugins.rst
Without them newbies might copy / paste the example and keep scratching their
heads as to why boostrap and/or routes file are not loaded by default as
the comments claim.
> Add parent method calls.

- en/appendices/3-6-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/11821
> Deprecation docs for QueryTrait mapReduce and formatResults.

- en/core-libraries/file-folder.rst
Folder::inPath() description writing reverse meant.
> modify: Folder::inPath() description.

- en/core-libraries/collections.rst
`toArray()` has many annoying issues, better show our users that `toList()` is preferred.
> de-emphasize the usage of Collection::toArray()

- en/core-libraries/form.rst
Ref: [#11109](https://github.com/cakephp/cakephp/pull/11109)
> setErrors doesn't have to be defined anymore

- en/core-libraries/email.rst
I consider that it is necessary either to remove the mention of only one language or to add a mention of Russian language, because when using Russian (**Cyrillic**) mail, there are the same problems with validation.
For example email: **пример@письмапрезиденту.рф**
> Update email.rst (it is necessary to remove the clarification)

- en/core-libraries/form.rst
In order to make the default validator works in CakePHP 3.7, the name of the function should be _buildValidator instead of validationDefault
> Fix wrong name on function

- en/console-and-shells.rst
Spent a bit of time discussing this in #support before discovering this was the intended behavior.
> Added note about adding multiple commands that share a class

- en/orm.rst
Just noticed this code example and wanted to see the deprecated calls removed. Hope you like the edit.
Replacing TableRegistry::get() calls with TableRegistry::getTableLocator()->get('Model')
> Replacing TableRegistry::get()

- en/plugins.rst
Plugins don't have a events hook.
> Remove lies.

- en/development/routing.rst
There is a trailing comma in $routes->connect('/:lang/articles/:slug', ['controller' => 'Articles', 'action' => 'view'],) which would lead to an error. The comma is removed in this proposed change.
> Code error in Route Options Example

- en/plugins.rst
Plugin short names use forward slash not back slash.
> Fix example.

- en/development/errors.rst
The paragraph in "Changing Exception Handling" says "3 ways", but the list under it shows 4 ways.
> Correct the count of exception handling ways

- en/appendices/4-0-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/12232
also included a note about migration path of auth and RSS functionality.
> 4.x folder

- fr/controllers/request-response.rst
getHeader('Accept') only return the value with the Accept key, to return all values in array, must use getHeaders()
> Update lire les en-têtes PHP

- en/migrations.rst
- en/phinx/migrations.rst
Update for Phinx 0.10.3 and Migrations 2.0.0. I didn't leave old ways. Since `rename()`, `removeIndex()` and `removeIndexByName()` returns `$this` also in the legacy versions, I think there aren't side-effects of calling `save()`.
> Update code examples

- ja/docutils.conf
After upgrading Sphinx, quotation marks are now converted to language-specific styles. However in Japanese, I think that quotation marks in English style match when surrounding English words. Also, if necessary, we will already use "「", "」" at the time of translation, so I propose converting to English style.
https://book.cakephp.org/3.0/ja/intro/conventions.html#id6
> [ja]Restore quote style to English.

- en/development/configuration.rst
``$merge`` value is true by default, in the documentation I fixed it from true to false when a user wants to not overwrite existing configuration. When merge = true we should overwrite when merge = false we shouldn't overwrite, or am I missing a point?
> Fix Loading configuration files section

- en/orm/associations.rst
I spent a couple of hours figuring out why I got 
> Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'label' in on clause is ambiguous
The note added in this PR solved my issue, obviously to most people, and now also to me. But adding this piece of text might save time for other newbies scratching their head.
> Added more examples and a note for multiple associations

- en/orm/entities.rst
Clarifying that accessor methods are run each time the entity's property are called.
> Added note about accessor methods.

- en/core-libraries/caching.rst
CacheEnging::write() does not define optional $config parameter, removed from docs.
> CacheEngine::write() param list fix

- en/views/helpers/form.rst
Using the Collection classes power to create options for select elements is missing from the documentation.
This pull request also shows that you can add extra data to the array, to produce extra attributes in the option tags created by the helper.
I have been unable to check the rendering of this change, because I can't build the documentation locally. I don't have Docker installed, and the `make html` fails.
> Added a section about using Collections to build select options

- ja/migrations.rst
In English Document, `->save()` method was added on the example code, though not in Japanese one.
It causes `[RuntimeException] Migration has pending actions after execution!`, and should be modified.
> missing save method around `removeColumn`

- en/orm/retrieving-data-and-resultsets.rst
In the section "Passing Conditions" under Associations I added  some sections so that the type-hint Query would appear uniformly through the section.
> Update Adds Type Hinting Uniformly

- en/core-libraries/caching.rst
Even though it mentions a second parameter to read() and third parameter to write(), an example code with config was missing and it took me a while to notice that. So, I thought it might be useful to have same example with a different key
> added an example of read and write with config

- en/phinx/migrations.rst
This pull request aims to try and clarify the two different decimal parts, and what they are for. As precision refers to the whole integer part before the decimal point, and scale refers to the fractional part after the decimal point.
However this wasn't very clear, at least to me, from the way the documentation was worded.
Reference, https://math.stackexchange.com/questions/64042/what-are-the-numbers-before-and-after-the-decimal-point-referred-to-in-mathemati
> Clarify decimal type

- en/development/routing.rst
Wildcard was lost during 3.5 fluent route conversion
> Fix routing wildcard example

- en/orm/database-basics.rst
Added use statements at the top of examples to guide reader to proper handling of core functions. I added a couple to the beginning of the document only as to not clutter up the entire page. Once they've done it a couple of times, they shouldn't need to keep seeing the guidance
Replaces PR #5877.
> Add use statement for core functions

- en/appendices/3-7-migration-guide.rst
Refs: https://github.com/cakephp/cakephp/pull/12673
> Add previous exception logging to migration guide

- en/controllers/components/security.rst
Add the missing second parameter to the signature.
Closes cakephp/cakephp#12637
> Show how to handle a blackholed request

- en/controllers/components/security.rst
If folks simply copy & paste this, they could end up breaking their app because the ``beforeFilter()`` method of the super classes of their controllers won't get called anymore.
> Add call to parent beforeFilter()

- en/orm/query-builder.rst
`Query::hydrate()` is deprecated.  `Query::enableHydration()` should be used instead.
> Update hydration for CakePHP 3.6+

- en/orm/table-objects.rst
TreeBehavior has a beforeDelete, so making your beforeDelte to work wirk children in the table might end up you up working wirth the next root-nodes in the mptt-tree.
> Added a note to save others the same bad experiance

- en/appendices/4-0-migration-guide.rst
after revert to `string|false` and `string|bool` , this line is not valid anymore
> 4.x remove invalid text about return values

- en/appendices/3-7-migration-guide.rst
> Change Cake\Email\ to Cake\Mailer\

- en/appendices/4-0-migration-guide.rst
> Cake\Http\Client now follows PSR-18.

- en/appendices/4-0-migration-guide.rst
- en/views/helpers/paginator.rst
- en/views/helpers/url.rst
Refs cakephp/cakephp#12802.
I couldn't find examples for the defunct style of usage which is nice.
> Always use "?" to specify query string params in URL array.

- en/development/testing.rst
Current example test code returned an error 
```
Deprecated Error: EventDispatcherTrait::eventManager() is deprecated. Use EventDispatcherTrait::setEventManager()/getEventManager() instead. - /var/www/html/tests/TestCase/Model/Table/BatchesTableTest.php, line: 44
You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [/var/www/html/vendor/cakephp/cakephp/src/Core/functions.php, line 311]
```
This change fixes the example code to use getEventManager() which removes the error.
> Update testing.rst with deprecation fix

- en/appendices/4-0-migration-guide.rst
> Document Request::body() removal.

- en/development/testing.rst
- ja/development/testing.rst
fix testing fixture from snake case to camel case to follow migration guide of CakePHP3.7.
https://book.cakephp.org/3.0/en/appendices/3-7-migration-guide.html
> Using underscored fixtures names in TestCase::$fixtures is deprecated. Use CamelCased names instead. For e.g. app.FooBar, plugin.MyPlugin.FooBar.
> update testing.rst "fix testing fixture from snake case to camel case"

- ja/console-and-shells/commands.rst
The ConsoleIntegrationTestCase class was moved into the ConsoleIntegrationTestTrait trait in 3.7. 
Then cosole testing chapter in English is already rewrite to use ConsoleIntegrationTestTrait.
https://book.cakephp.org/3.0/en/console-and-shells/commands.html#testing-commands
So, fix the Japanese document to follow English document.
> [ja] fix console-and-shells testing chapter (use ConsoleIntegrationTestTrait)

- pt/migrations.rst
Translates the following pieces of the _Migrations_ page to Portuguese:
- _"Generating a diff between two database states"_ section  (added in version 1.6.0)
- New `bake seed` options `--data`, `--limit` and `--fields` (added in version 1.6.4)
> [pt] Translates missing Migrations page sections to Portuguese

- en/development/testing.rst
- ja/development/testing.rst
- ja/plugins.rst
- fix deprecated method
`hydrate` is already deprecated in 3.4.x, so replace to `enableHydration`
refs: https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#deprecated-combined-get-set-methods
- add translate in plugins.rst
refs: https://github.com/cakephp/docs/pull/5927/files
> fix deprecated method and add translate in plugins.rst

- en/tutorials-and-examples/cms/articles-controller.rst
- ja/tutorials-and-examples/cms/articles-controller.rst
In validation doc, it is recommended not to use `notEmpty`, Then I think `notEmpty` should not be used in cms tutorial.
Therefore, I fixed to use `allowEmptyString` instead of `notEmpty`.
ref: https://book.cakephp.org/3.0/en/core-libraries/validation.html#allowing-empty-fields
> You can also use notEmpty() to mark a field invalid if any ‘empty’ value is used. In general, it is recommended that you do not use notEmpty() and use more specific validators instead.
> tutorial code use allowEmptyString instead of notEmpty

- en/development/testing.rst
- ja/development/testing.rst
fix testing.rst because after 3.6.0 it is recommended that to use `TableRegistry::getTableLocator()->get()` instead of `TableRegistry::get()`.
refs: https://book.cakephp.org/3.0/en/orm/table-objects.html#getting-instances-of-a-table-class
> use TableRegistry::getTableLocator()->get() in testing.rst

- en/appendices/4-0-migration-guide.rst
- en/controllers/middleware.rst
> Update docs regarding PSR-15 support.

- en/debug-kit.rst
Refs https://github.com/cakephp/debug_kit/pull/623 and should be used instead of dangerous god-mode (force-enable true).
> Add TLD whitelisting as preferred debugkit enable.

- en/appendices/orm-migration.rst
- en/orm/entities.rst
- en/orm/retrieving-data-and-resultsets.rst
- en/views/helpers/rss.rst
When writing https://www.dereuromark.de/2019/02/05/virtual-entity-fields-in-cakephp/ I stumpled upon a wild mix and unclear usage of the names in the docs.
> By default virtual fields are not exported when converting entities to arrays or JSON
in one place, but then virtual properties on other places.
Fields are what entities contain (from DB fields to entity fields and vice versa). Fields can be set and read using the getter - or can be accessed using "property" access.
I therefore think property is the technical term only, when you explain how the `$entity->property_name` is used to access the `property_name` field.
We should be a bit more clear here to avoid technical terms leaking into normal documentation.
PS: I applied a similar naming concept for the …
> Improve wording of entity property to field where applicable.

- en/appendices/4-0-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/12952
soft deprecations for now, no need to trigger warnings IMO.
> Docs for entity deprecations.

- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
Changes to two files in the CMS tutorial:
authentication.rst
------------------
- 58: Note was added because not enough import was given to the fact that a hashed password was needed.  If the student doesn't do it at this point, then they will be locked out of any accounts they created, and will need to confusingly comment out portions of code to access again.
- 95: 'authorize' option was removed because it was causing a system error that no isAuthorized() functions were present, and the instructions do not mention it.  This 'authorize' is added later in the tutorials.  I believe it was inserted here by mistake
- 131: Instruction was changed because login.ctp doesn't exist at this point.
tags-and-users.rst
-------------------
- 377: Added because tag strings will not be see in the article …
> Cleanup of CMS tutorial

- en/appendices/4-0-migration-guide.rst
Small note as follow up for https://github.com/cakephp/docs/pull/5964
on
https://github.com/dereuromark/cakephp-shim/blob/4.x/src/View/Helper/FormHelper.php
usage.
> Link to 4.x shim FormHelper.

- ja/orm/query-builder.rst
Added key word `use($subquery)` in Japanese Document.
I also checked the English Document, and it was correct.
> `use($subquery)` was missing on 

- en/orm/saving-data.rst
The fieldList option has been deprecated since 3.4.
Use the `fields` option instead.
https://github.com/cakephp/cakephp/commit/bfc93253e23a605f8e6ab6c521c2036bc1f290dc
https://github.com/cakephp/cakephp/blob/9258019c6544f67ea49cb882e08aa8c3e3bbe95f/src/ORM/Marshaller.php#L276
> The fieldList option has been deprecated since 3.4.

- en/debug-kit.rst
- fixes layout
- fixes typo `TDLs` -> `TLDs`
refs: https://book.cakephp.org/3.0/en/debug-kit.html#configuration
> fixes broken example code layout in debug-kit.rst

- en/core-libraries/caching.rst
Some options spanning multiple lines were incorrectly indented using 3 spaces instead of 2, causing messed up display.
> Fix indentation causing invalid display

- en/development/testing.rst
Adding explanations from https://github.com/cakephp/cakephp/issues/12682
> Point to method to load plugins in non-integration tests.

- en/bake/development.rst
- en/controllers.rst
- en/controllers/components.rst
- en/controllers/components/authentication.rst
- en/controllers/components/security.rst
- en/core-libraries/email.rst
- en/core-libraries/events.rst
- en/debug-kit.rst
- en/development/errors.rst
- en/development/routing.rst
- en/development/testing.rst
- en/elasticsearch.rst
- en/orm/behaviors.rst
- en/orm/saving-data.rst
- en/orm/table-objects.rst
- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/views/helpers.rst
- en/views/themes.rst
* Use EventInterface typehint.
* Fix view usage
* Remove a few more 'before' examples.
> 4.x Update Beforefilter and other event listeners

- en/plugins.rst
It isn't clear that plugins can use classes from other plugins or the application so add an example to that effect.
Refs #5989
> Add more context on using app code in plugins

- en/contents.rst
The authorization plugin is the first plugin to have its own documentation mini-site. If this is well received I'll migrate other existing plugin docs to this style.
> Add link to authorization docs

- en/controllers/middleware.rst
I have see too many newbies on slack/IRC waste time trying to get CSRF tokens for their stateless API URLs.
> Note about CSRF protection and stateless requests

- en/appendices/3-6-migration-guide.rst
- en/console-and-shells.rst
- en/console-and-shells/commands.rst
I almost overlooked when ``Shell`` would be removed. This should make it more clear.
> Improve Shell deprecation/replacement visiblity

- en/intro/cakephp-folder-structure.rst
I always thought this should be added as it's really not clear.
> Add note about the non-pre-exiting folders in src

- config/all.py
- en/appendices/4-0-migration-guide.rst
- en/console-and-shells.rst
- en/contributing/code.rst
- en/controllers/middleware.rst
- en/controllers/request-response.rst
- en/core-libraries/httpclient.rst
- en/development/application.rst
- en/development/configuration.rst
- en/development/routing.rst
- en/development/testing.rst
- en/installation.rst
- en/intro/cakephp-folder-structure.rst
- en/tutorials-and-examples/cms/installation.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
* Fix version numbers.
* Remove duplicate content for requests/responses.
* Fix middleware() hook signatures.
* Fix plugin middleware example.
* Remove outdated warning for http/client.
> Clean up some docs for 4.x

- en/controllers.rst
- en/controllers/components.rst
- en/controllers/components/authentication.rst
- en/controllers/components/flash.rst
- en/controllers/components/pagination.rst
- en/controllers/components/request-handling.rst
- en/controllers/components/security.rst
- en/core-libraries/caching.rst
- en/core-libraries/email.rst
- en/core-libraries/logging.rst
- en/core-libraries/number.rst
- en/debug-kit.rst
- en/development/configuration.rst
- en/development/sessions.rst
- en/orm/behaviors.rst
- en/orm/behaviors/tree.rst
- en/orm/database-basics.rst
- en/orm/table-objects.rst
- en/views.rst
- en/views/helpers.rst
- en/views/helpers/flash.rst
- en/views/helpers/form.rst
- en/views/helpers/html.rst
- en/views/json-and-xml-views.rst
* Fix element directory name.
* Fix formatting.
* Fix link names.
> Cleanup 4.x docs more

- en/core-libraries/logging.rst
Just changing the order moving debug as the highest level instead info as it was in the list. [rfc3164](https://tools.ietf.org/html/rfc3164)
> Debug has a higher level

- ja/views/json-and-xml-views.rst
add missing xml view example in json-and-xml-views.rst
refs: https://github.com/cakephp/docs/blob/f0ace7131cba1faffe0a50fdca2a3eaed09b3e37/en/views/json-and-xml-views.rst#L152
> [ja] add missing xml view example in json-and-xml-views.rst

- en/core-libraries/file-folder.rst
According to the migration guide the [Filesystem package will be deprecated from version 4.0](https://book.cakephp.org/4.0/en/appendices/4-0-migration-guide.html#filesystem), but in the guide it is showing as deprecated since 5.0.
> Update deprecated since version for Filesystem

- en/appendices/3-6-migration-guide.rst
Some calls of ``Cake\Database\Type::map()`` has been deprecated at CakePHP 3.6.2 and above, but documented not yet.
https://github.com/cakephp/cakephp/commit/ea567d9cadd0289c213706a5ec94e37320025a5f
> Add info Type::map() changes, into 3.6 Migration Guide.

- en/appendices/4-0-migration-guide.rst
> Add info about DecimalType changes.

- en/orm/retrieving-data-and-resultsets.rst
This is very powerful when you have hasMany associations and you need data from both but applying using distinct only in the main query. In my humble opinion, this can be very useful in docs
> Add info about combine innerJoinWith + Contain

- .travis.yml
CI build is broken from Apr 17, 2019 10:24 PM.
The default version of python used for building has changed:
https://changelog.travis-ci.com/upcoming-python-default-version-update-96873
> [3.x]Specify the version of python to use for the build

- en/views/helpers/form.rst
The login action context does not match to the article object.
Changed login to publish instead.
> Update 'Setting a URL for the Form' section

- en/views/helpers/form.rst
Today, I was asked whether it is possible to not show the day field of a date input. I couldn't find it at first. After some search, I did, though.
This hopefully improves the discoverablity of these keys.
> Improve date & time parts keys discoverability

- ja/development/testing.rst
- ja/views/helpers/form.rst
This PR contains following
- add an example of assertFileResponse in testing.rst
- https://github.com/cakephp/docs/pull/6040
- change 'publish' from 'login' in helpers/form.rst
- https://github.com/cakephp/docs/pull/6038
> [ja] add an example of assertFileResponse and change example in helpers/form.rst

- en/contents.rst
- en/controllers/components/authentication.rst
While it still has a long life, communicate the change early and link to the newly published docs.
> Mark authcomponent as deprecated

- en/core-libraries/caching.rst
There's a couple of examples of `Cache::remember()` being used without a space after the closure's `function` keyword which is required by the CakePHP coding standards (pointing this out as it has tripped a few of my colleagues up).
> Update examples to conform to coding standards

- en/appendices/3-8-migration-guide.rst
fix styles in 3.8 migration guide.
- sub title Collection
- delete duplicated "now"
- fix build error as below
```
/data/en/appendices/3-8-migration-guide.rst:46: WARNING: Bullet list ends without a blank line; unexpected unindent.
```
> fix 3.8 migration guide style

- en/plugins.rst
you should use  lower case when overriding Plugin Templates
> 4.x - use lower case

- fr/console-and-shells/repl.rst
This fixes an issue from https://github.com/cakephp/docs/pull/6065.  I didn't make the change earlier as I was waiting for feedback, but the full pull request was merged.
This aligns the change with the other languages.
> Fixed typo in fr/console-and-shells/repl.rst

- en/orm.rst
I guess only en version of orm.rst was updated when TableRegistry::get() was deprecated.  Since all the other versions have been been updated to include both prior and new example, re-adding here.
This seems important since this is the first place you'll read about ORM the TableRegistry::get() deprecation is relatively new for 3.x.
> Added prior TableRegistry::get() example back to en

- fr/chronos.rst
- ja/chronos.rst
The other pull request was sloppy.  This is smaller and cleaner.
You shouldn't find this page unless you're switching documentation languages while on chronos.html, but fixing it anyway.
> Fixed chronos documentation moved link.

- ja/bake.rst
- ja/bake/development.rst
- ja/bake/usage.rst
- ja/contents.rst
- ja/debug-kit.rst
fixes Bake plugin's documentation link in sidebar and moved document link.
> [ja] Fixes documentation links

- en/orm/query-builder.rst
https://github.com/cakephp/docs/issues/6077
I added 2 subsections: 'Function Arguments' and 'Custom Functions' to the 'Using SQL Functions' section.
I also changed the layout of the wrapped functions list so it's easier to read and not crammed together.
https://pasteboard.co/Ife0vRJ.png
I updated the wording for function arguments and custom functions so it is more direct and easier to read.
I made the function arguments example show passing an expression as well as literal, identifier and bound arguments.  I also updated the example formatting so it doesn't make you scroll to read it.
> Made 'Using SQL Functions' a little easier to read

- Dockerfile
Updated Dockerfile to match deploy.Dockerfile.  As explained in the comment, jessie is deprecated and the package server moved which can cause issues.
https://github.com/cakephp/docs/issues/6063#issuecomment-491132106
This should have no functional difference since it's already used in deploy.Dockerfile. Did not notice any new errors/failures.
> Updated Dockerfile to debian:stretch

- en/views/helpers/paginator.rst
The docs show that a `<span>` tag is output by default, but the [current](https://github.com/cakephp/cakephp/blob/1cb44d4ba4675332248bc53af2729c5083529374/src/View/Helper/PaginatorHelper.php#L70) version of the helper uses an `<a>` tag instead.
> Fix example output of PaginatorHelper::prev()

- en/orm/associations.rst
In cakephp/cakephp#13286 I found out we did not document how to use finder with additional options. This rectifies that omission.
> Document finder options

- ja/core-utility-libraries/security.rst
To use the useOepnSsl option.
```
Configure::write('Security.useOpenSsl', true);
```
> [ja][2.x] add Security.useOpenSsl

- en/orm/retrieving-data-and-resultsets.rst
In the section "Modifying Results with Map/Reduce" the Query function "enableHydration()" was called "enableHydrate()"
> Fixed typos in retrieving-data-and-resultsets.rst

- en/appendices/4-0-migration-guide.rst
Use full namespace for ServerRequest.
> Use full namespace for ServerRequest. in 4-0-migration-guide

- en/phinx/configuration.rst
Resolves #6135
Refers to [issue 351 at migrations](https://github.com/cakephp/migrations/issues/351) where a developer could have had the assistance in finding the socket file to use `unix_socket`.
> Added instructions to retrieve socket file path

- en/tutorials-and-examples/cms/articles-controller.rst
When trying to run the CMS tutorial on 4.x-dev I was getting a compatibility error with `ValidationAwareTrait::validationDefault()` Added the return type declaration to match, and my small woes were gone. :)
> Add return type declaration to validationDefault

- en/tutorials-and-examples/cms/tags-and-users.rst
The tag_string needs to be declared as accessible for the code in the tutorial to correctly save the newly created comma separated list of tags for the article. The example code in the 'Adding a Computed Field' section has been updated to demonstrate this.
> Added code to make tag_string accessible

- en/appendices/4-0-migration-guide.rst
- en/views/helpers/html.rst
Update the tableheader example to use undeprecated usage. Doing this in 4.x as I feel it is simpler than having to put a `// prior to` flag in the 3.next docs.
Fixes #6162
> Update tableheader example

- en/appendices.rst
Forward compatible shimming can prepare a 3.x app for the next major release (4.x).
> Add info for FC shimming

- en/appendices/3-9-migration-guide.rst
- en/controllers/components/pagination.rst
I've also rewritten the top half of the paginator docs as they dove into complex scenarios before covering the simple ones. It also was showing to many different ways to use Pagination that I would rather not show to new people.
> Add documentation for SimplePaginator

- en/core-libraries/validation.rst
Hello, I'm now a novice developer who has used CakePHP for two months.
When i see Cake\Validation\Validator.php about allowEmptyString method, the order of parameters was $field, $message, $when.
So the above document looked a little wrong and made a suggestion.
Please check this document.
> Update validation.rst (allowEmptyString method part)

- en/core-utility-libraries/hash.rst
It's not clear how matchers are used in conjunction with {n} etc.  Have added a simple example
> Add example for use of 'matchers'

- en/orm/associations.rst
Some of this was written in loose, friendly way but certain things like options read better when direct and uniform.  I also updated a couple random things like what is quoted, italicized and capitalized to be consistent.
The joinType option does not technically restrict the value like strategy does, but made it clear what the two useful values are.
This is only for the hasOne association to see if it makes sense.
> Updated phrasing and grammar used in hasOne associations.

- en/plugins.rst
Updating Plugin.php example to call parent function on middleware and commands to prevent users from not having middleware and/or commands being loaded correctly.
> Updating Plugin.php example

- Dockerfile
- Makefile
This adds a Makefile target to run the W3C EPUB spec validation tool against any of the generated .epub files.
https://github.com/w3c/epubcheck
There is a validator website where you can upload files, but it is slow.
> Added support for validating generated epub files

- README.md
I found the extra information about Docker confusing in the README.  This simply states how to build and run without talking about unusual edge cases in the build system.
The image information listed won't match a user's local image list so if they are truly that unable to find out if the image exists this will probably just confuse them.
> Simplified README steps on building with Docker container

- en/orm.rst
- en/orm/entities.rst
- en/orm/query-builder.rst
- en/orm/saving-data.rst
- en/orm/table-objects.rst
I made the original change to update the deprecated TableRegistry::get() example earlier this year for my team.  But, I followed an example that kept the full source code for the deprecated statement.
I think this looks weird and makes the code awkward to read and copy.  This changes it to use a comment which is less obtrusive and keeps the code cleaner.
Hopefully people find the database intro pages easier to read with this.
> Updated TableRegistry::get() deprecation examples

- en/orm/retrieving-data-and-resultsets.rst
I cleaned up an old review I had to clarify how innerJoinWith, select, contain and matching can collide.
https://github.com/cakephp/cakephp/issues/12771
https://github.com/cakephp/cakephp/pull/12772
I basically tried to state things directly so people aren't lost trying to interpret scenarios.
> Clarified use of innerJoinWith with select, contain and matching

- deploy.Dockerfile
- nginx.conf
#5891
#4832
I'm not sure what the nginx setup is for routing to the version-specific books, but this will handle any /4.0/* and /4.x/* requests. I assume the top-level router is redirecting to /4.0/en/ and don't try to handle any special cases.
Disabled special 404 page as they have not rendered properly in a long time. Use default 404 page just like CakePHP 2 docs.
I disabled elasti-search and and ran the full container locally.
> Updated nginx config to use /4/ instead of /4.0/

- Dockerfile
- deploy.Dockerfile
- nginx.conf
https://github.com/cakephp/docs/issues/5891
I'm not sure what the nginx setup is for routing to the version-specific books, but this will handle any `/2.0/*` and `/2.x/*` requests.  I assume the top-level router is redirecting to `/2.0/en/` and don't try to handle any special cases.
I disabled elasti-search and and ran the full container locally.
> Updated nginx config to use /2/ instead of /2.0/

- deploy.Dockerfile
- nginx.conf
#5891
https://github.com/cakephp/docs/issues/4832
I'm not sure what the nginx setup is for routing to the version-specific books, but this will handle any /3.0/* and /3.x/* requests. I assume the top-level router is redirecting to /3.0/en/ and don't try to handle any special cases.
Disabled special 404 page as they have not rendered properly in a long time.  Use default 404 page just like CakePHP 2 docs.
I disabled elasti-search and and ran the full container locally.
> Updated nginx config to use /3/ instead of /3.0/

- en/console-and-shells/commands.rst
The instructions say "create **HelloCommand.php**. Put the following code inside it::"  but the code below does not include a <?php headder so when you run it it just echoes the contents of the file to the console rather than executing it.   As someone who is well out of practice with php, it took me several hours to work out why and I only solved it by using cake/bake to create the skeleton.   I appreciate that to those familiar with php it is probably obvious that you need that though!
> Added <?php

- en/core-libraries/validation.rst
- en/orm/table-objects.rst
Moved deprecation notice up to first use of TableRegistry and made it a proper notice.  Fixed formatting errors in names.
> Updated TableRegistry description to TableLocator

- en/development/routing.rst
https://book.cakephp.org/3/en/development/routing.html#prefix-routing
is not clear on the subject of multi-word prefixes.
This also adds proper typehints to understand the available methods inside each callable as already done in app template etc.
I also cleaned up the remaining examples of legacy underscores for generated URLs, as the default is now dashed and we shouldnt have outdated docs showcasing a mix here.
> Clarify prefix routing and better examples.

- en/orm/behaviors.rst
- en/orm/table-objects.rst
Resolves https://github.com/cakephp/docs/issues/6242
The normal stop of event propagation is not completely true for Table scope, where also the false value must be returned in order to properly stop the following action.
> Clarify event propagation abort in Table scope.

- en/appendices/4-0-upgrade-guide.rst
The commands for rector are incorrect and need to be `bin/cake upgrade rector` instead of `bin/cake rector`
Also during upgrade it maybe better to use the /src path or /tests path as just using the app results in rector running from the whole project and trying to correct packages in the /vendor dir.
> Fixing commands for rector

- en/appendices/4-0-migration-guide.rst
Ran into this recently upgrading a prod app to RC1.
> 4.x - Added Table::newEntity() behavior change to Breaking Changes

- en/development/errors.rst
- fr/development/errors.rst
- ja/development/errors.rst
- pt/development/errors.rst
- tl/development/errors.rst
Fixes https://github.com/cakephp/docs/issues/4543.
> Fixed handleFatalError() example

- en/appendices/3-9-migration-guide.rst
Added migration notes for https://github.com/cakephp/cakephp/pull/13958.
> 3.9 - Added migration notes for Text::uuid() random_int() in PHP 5.6

- en/appendices/4-0-upgrade-guide.rst
As a discussion in slack/irc came up It was determined that the `cd ~/code/upgrade` is very specific and not where the user would have done the initial clone. Plus when following the directions and running `composer install --no-dev` the user is already in the directory needed to run the commands later in the docs.
cc @niel
> Upgrade Docs 4.x Removing duplicate cd command.

- en/orm/retrieving-data-and-resultsets.rst
https://github.com/cakephp/docs/issues/4552
This example produces confusing and unclear results.  Removed in favor of the subquery example below.
> 4.x - Removed useless example of queryBuilder with limit().

- en/appendices/4-0-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14018
https://github.com/cakephp/cakephp/pull/14017
Added migration notes in case these are merged.
> 4.x - Added migration notes for primaryKey() deprecations

- en/installation.rst
This can trip newbies. Experienced devs would be already aware how to use appropriate branche if they need to.
Refs cakephp/cakephp#14023
> Remove information regarding use of "dev-master".

- en/orm/behaviors/translate.rst
Without the ::class it will give an invalid constant error.
> Add ::class to ShadowTableStrategy reference

- en/console-commands.rst
Fix some minor typos in the console commands section.
> Fix typos on console commands

- en/controllers/middleware.rst
The name "changed" from the underscore prefixed variant. Maybe that's something that should also be mentioned in the migration guide?
The whitespace removal slipped in there by accident.
> Fix CSRF token attribute name and add some details about JS usage.

- en/appendices/4-0-migration-guide.rst
At 4.0 Migration guide, there are two explanations about RequestHandlerComponent in Component section.
1st one is ...
https://github.com/cakephp/docs/pull/6382/files#diff-2571a7d175dfd78b02353be306cdbfd8L113
(deleted line in this PR)
2nd one is ...
> * The request body parsing features of ``RequestHandlerComponent`` have been
removed and now emit a deprecation warning. You should use the
:ref:`body-parser-middleware` instead.
https://github.com/cakephp/docs/pull/6382/files#diff-2571a7d175dfd78b02353be306cdbfd8R116
I think the 2nd one is better because it contains the link to body-parser-middleware. That's why this PR deletes 1st line.
ref: https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html
> Delete duplicated explanation about RequestHandlerComponent in 4.0 migration guide

- en/tutorials-and-examples/cms/database.rst
Update notes of the database setting of 4.x CMS tutorial :
https://book.cakephp.org/4/en/tutorials-and-examples/cms/database.html#database-configuration
* I think it's kind to have note of app_local.php. Since it exists by default, it overrides the app.php configuration even if we modified app.php Datasources section following your guidline.
* Delete the note of app.default.php because it seems it's no longer exists by default.
> Update database.rst on 4.x CMS tutorial

- en/appendices/4-0-migration-guide.rst
We might as well add migration notes for this since the user won't know the behavior was always wrong.
https://github.com/cakephp/cakephp/pull/14086
> Add migration notes for alias truncation exception

- en/installation.rst
- en/tutorials-and-examples/blog/blog.rst
- en/tutorials-and-examples/bookmarks/intro.rst
- en/tutorials-and-examples/cms/installation.rst
- es/installation.rst
- es/tutorials-and-examples/blog/blog.rst
- es/tutorials-and-examples/bookmarks/intro.rst
- es/tutorials-and-examples/cms/installation.rst
- fr/installation.rst
- fr/tutorials-and-examples/blog/blog.rst
- fr/tutorials-and-examples/bookmarks/intro.rst
- fr/tutorials-and-examples/cms/installation.rst
- ja/installation.rst
- ja/tutorials-and-examples/blog/blog.rst
- ja/tutorials-and-examples/bookmarks/intro.rst
- ja/tutorials-and-examples/cms/installation.rst
- pt/installation.rst
- pt/tutorials-and-examples/blog/blog.rst
- pt/tutorials-and-examples/bookmarks/intro.rst
- ru/installation.rst
- ru/tutorials-and-examples/blog/blog.rst
- ru/tutorials-and-examples/bookmarks/intro.rst
- tl/installation.rst
- tl/tutorials-and-examples/blog/blog.rst
- tl/tutorials-and-examples/bookmarks/intro.rst
- tl/tutorials-and-examples/cms/installation.rst
- tr/installation.rst
- tr/tutorials-and-examples/bookmarks/intro.rst
- zh/tutorials-and-examples/cms/installation.rst
On the Windows command line the caret is an escape character, thus
composer would not receive the literal character and always install
version 4.0.0
> Ensure Windows compatibility in project creation command.

- en/appendices/4-0-migration-guide.rst
- ja/appendices/4-0-migration-guide.rst
The deprecation warning is not being triggered anymore.
refs cakephp/cakephp#14093
> Remove note about RequestHandlerComponent triggering deprecation warning

- en/deployment.rst
- en/development/configuration.rst
- en/development/testing.rst
Without this the whole Network >  Http class aliasing breaks.
Also unified the command to the one used predominantly already (dashed version).
> Cmposer dump autoload warning.

- en/controllers/middleware.rst
Corrections:
1. method name typo: `getParsedData` -> `getParsedBody`
2. the parser callback expects one argument, not two
> Update middleware.rst - fixed typos in method name and callback arguments

- en/tutorials-and-examples/cms/database.rst
The goal of this tutorial is to give CakePHP a try fast, using copy and paste.
Unfortunately for PostgreSQL users those SQL statements differ considerably and require manual intervention.
In the MySQL part, in the last insert statement, now() has been changed in NOW() to be consistent with the insert above.
> Be nice to PostgreSQL users in the CMS tutorial

- en/contributing/tickets.rst
Written that way currently points to https://book.cakephp.org/4/en/contributing/discourse.cakephp.org, fixed to the correct one
> Fix forum link

- en/tutorials-and-examples/cms/authorization.rst
The instructions on running the policy shell command will fail if Authorization plugin is not loaded.
> Add info about loading the plugin

- ja/core-libraries/global-constants-and-functions.rst
replaced more native word
インデクス→インデックス
> Fix: Japanese typo

- en/development/configuration.rst
APP was replaced by ROOT. But in contrast to APP, ROOT does not contain trailing slash.
> fix: missing DS after ROOT in example

- en/views/helpers.rst
Since https://github.com/cakephp/cakephp/commit/3d2900 it is not possible to declare $helpers variable directly in controllers anymore.
> Remove obsolete helper section.

- en/core-libraries/caching.rst
Updated sections involving Cache::read to use isset() and is_null() instead of strict boolean comparison, reflecting the change from returning null instead of false when failing to read value.
> Cache::read() returning null on non-existing values

- en/console-commands/commands.rst
The buildOptionParser method was missing the return type ConsoleOptionParser, giving the error:
Declaration of App\Command\AppCommand::buildOptionParser(Cake\Console\ConsoleOptionParser $parser) must be compatible with Cake\Console\BaseCommand::buildOptionParser(Cake\Console\ConsoleOptionParser $parser)
> Added missing return type to buildOptionParser

- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/cms/authentication.rst
I've removed the authorization aspects to keep the tutorial simpler and not create overlap with the CMS tutorial which includes authorization.
> Update blog tutorial to use authentication plugin

- en/development/routing.rst
Added a Note to the example for the usage of $routes->resources as doing this wrong may lead to time consuming and frustrating error search
> RESTful Routing: clarify usage of id option with $routes->resources

- Makefile
- scripts/populate_search_index.php
I'm planning on upgrading elasticsearch for the book and plugin sites. That will require a different index structure as es6 only allows one type per index and recommends that the mapping be called _doc. This updates the indexing script to allow both an es6 mode and the `--compat` mode will work with our current elasticsearch version.
Once I have he new elasticsearch instance working the index script will run twice.
> Prepare indexing script for elasticsearch upgrade

- en/contents.rst
Chronos isn't a CakePHP plugin but a standalone library.
See
https://github.com/cakephp/chronos/blob/aca7c4fdcdbbf40513c2fdc0c2b33040721cdd21/composer.json#L3
> Move Chronos to Standalone Packages

- en/plugins.rst
I just stumbled about this problem while developing a plugin. 
I couldn't find any solutions to load another CakePHP from your plugin, but it was that simple.
Note for others that might have this issue:
```php
// in src/Plugin.php
class Plugin extends BasePlugin
{
public function bootstrap(PluginApplicationInterface $app)
{
parent::bootstrap($app);
$app->addPlugin(\BootstrapUI\Plugin::class);
}
}
```
> Add example for loading another plugin

- en/development/application.rst
As @ashleypinner pointed out in Slack that the Github links point to master and a person upgrading their 3.x app could accidentally bring in 4.x code.
> [3.x] Fixing Github links to point to 3.x instead of master

- en/orm/database-basics.rst
>  [3.x] Use spelled out variable names in DB basics

- en/orm/database-basics.rst
- fr/orm/database-basics.rst
- ja/orm/database-basics.rst
- pt/orm/database-basics.rst
- ru/orm/database-basics.rst
- tl/orm/database-basics.rst
> [4.x] Use spelled out variable names in DB basics

- en/controllers/request-response.rst
I noticed during Japanese translation.
https://github.com/cakephp/docs/pull/6554
I actually tried file upload and confirmed it.
```
object(Laminas\Diactoros\UploadedFile) {
[private] clientFilename => 'test.csv'
[private] clientMediaType => 'application/vnd.ms-excel'
[private] error => (int) 0
[private] file => '/tmp/php9mTDKH'
[private] moved => false
[private] size => (int) 14112
[private] stream => null
}
```
> fix: Zend -> Laminas

- en/appendices/4-1-migration-guide.rst
- en/orm/saving-data.rst
- en/orm/table-objects.rst
> Add docs for afterMarshal event.

- en/core-libraries/validation.rst
Corrected namespace for localized class
With `Localized\Validation\FrValidation` `ValidationRule` class return error 'Unable to call method "%s" in "%s" provider for field "%s"'
That classes located under the `Cake\Localized\Validation` namespace
> corrected namespace

- en/appendices/4-1-migration-guide.rst
- en/controllers.rst
- en/plugins.rst
- en/views/helpers.rst
Docs for https://github.com/cakephp/cakephp/pull/14436
> addHelper() migration docs.

- ja/controllers/components/form-protection.rst
https://book.cakephp.org/4/en/controllers/components/form-protection.html
There is no Japanese page yet. This is the first translation.
https://book.cakephp.org/4/ja/controllers/components/form-protection.html
I thought it would be a good idea to add a description of 
deprecated to the Security Component page.
https://book.cakephp.org/4/en/controllers/components/security.html
> [ja][4.x] orm/controllers/components/form-protection.rst

- en/core-libraries/global-constants-and-functions.rst
I had to use
__d('plugin_name', 'A simple string.'))
here
Refs https://book.cakephp.org/4/en/core-libraries/internationalization-and-localization.html#language-files
What I don't know yet, is now plugins with namespacing work:
-  `ADmad/SocialAuth` etc
> Fix __d() domain docs.

- en/controllers/middleware.rst
With the boolean value, Laminas\Diactoros fires an exception. It has to be of type string or numeric.
> invalid header value type

- en/installation.rst
wildcard operator causes issues on some CLI systems when not quoted.
> Update Composer install command

- fr/views/helpers/form.rst
There was an error in the documentation, the third parameter can't be a string, it throws an error.
> Correction for the label function

- fr/views/helpers/form.rst
There was an error in the documentation, the third parameter can't be a string, it throws an error. I also proposed a patch for the version 3.x of the manual.
> Correction for label function

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14522
> Added notes for disabling lenient parsing

- en/views/helpers/form.rst
As of Cake 4, it seems that ``Form::create()``'s first argument can no longer be ``false``. We must use ``null`` to create a model-less form.
> Form::create() - $context argument cannot be false

- en/views/helpers/breadcrumbs.rst
- fr/views/helpers/breadcrumbs.rst
- ja/views/helpers/breadcrumbs.rst
- ru/views/helpers/breadcrumbs.rst
- tl/views/helpers/breadcrumbs.rst
> Fix inline usages of removed `templates()` method.

- en/controllers.rst
If we don't use return keyword with render method it throws below error:
> Return value of App\Controller\PagesController::home() must be an instance of Cake\Http\Response or null, none returned
> Returns "none returned" error without 'return' keyword

- en/tutorials-and-examples/blog/part-two.rst
Blog tutorial part 2, replaced notEmpty() with notEmptyString()
> Tutorial using deprecated validation function

- en/core-libraries/email.rst
Hoping to clarify that the new "setXXX()" methods in 3.4+ are replacing the "XXX()" methods and that the "addXXX()" methods should still to be used for multiple recipients, senders etc.
> Clarify use of "setTo(), setCc(), setBcc()"

- en/controllers/request-response.rst
CookieInterface for argument, updated example to reflect this.
> Correct documentation for Response::withExpiredCookie

- en/appendices/4-1-migration-guide.rst
- en/console-commands/commands.rst
- en/console-commands/repl.rst
- en/controllers.rst
- en/controllers/components/pagination.rst
- en/core-libraries/events.rst
- en/development/testing.rst
- en/intro.rst
- en/orm.rst
- en/orm/behaviors/tree.rst
- en/orm/entities.rst
- en/orm/query-builder.rst
- en/orm/saving-data.rst
- en/orm/table-objects.rst
- en/plugins.rst
> Deprecate TableRegistry.

- en/orm/table-objects.rst
Must declare return type `string`
> Fixes incorrect example for defaultConnectionName()

- en/console-commands/commands.rst
Must declare return type `void`
> Add return type to Testing Commands example

- en/development/routing.rst
- en/intro/conventions.rst
Refs https://api.cakephp.org/4.0/class-Cake.Utility.Inflector.html#camelize
We shouldnt use a word, that has no good meaning and is not in line with the current API and how people use the casings.
Most people don't know what Pascal case means or is supposed to be. CamelCase and camelBacked is an agnostic and visual way to describe it and thus a good default anyway.
It makes sense to not confuse people already used to those very good default style names.
https://en.wikipedia.org/wiki/Camel_case lists PascalCase as well, but as I said: It has less visual and thus less useful meaning.
> Docs of CamelCase

- en/development/routing.rst
The default inflection is dashed not underscore. There was no difference at the shown examples. Now it makes more sense.
> Fix error describing default behavior

- en/development/testing.rst
CakePHP 4 is always PSR-7 compliance and method not exists ( https://github.com/cakephp/cakephp/pull/12530 )
> Remove mentions to useHttpServer()

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/issues/14770
This calls out the behavior change more clearly for users scanning the migration notes.
> Explain case-sensitive association name change

- en/orm/associations.rst
There is no info on this on https://book.cakephp.org/4/en/intro/conventions.html or even https://book.cakephp.org/4/en/orm/associations.html
It is true that many people are confused by the association names vs field names on the resulting find results.
Maybe these examples help?
Resolves doc issues mentioned in https://github.com/cakephp/cakephp/issues/14770
> Clarify Association conventions.

- en/contents.rst
- es/contents.rst
- fr/contents.rst
- ja/contents.rst
- pt/contents.rst
- ru/contents.rst
- zh/contents.rst
Reorder the TOC entries to get better forward and back buttons at the bottom of each page.
Refs #6707
> Re-order TOC entries to create better fwd/back links

- en/views/helpers.rst
I suggest to improve this part of docs because in `/src/View/Helper.php` we already have `getView()` method:
[Cakephp Code Reference](https://github.com/cakephp/cakephp/blob/master/src/View/Helper.php#L121-L129)
```php
/**
* Get the view instance this helper is bound to.
*
* @return \Cake\View\View The bound view instance.
*/
public function getView(): View
{
return $this->_View;
}
```
I think it's better to use `getView()` method as part of **best practices**.
Please correct me if I'm wrong.
Thank you.
> Improve Docs: Update helpers.rst to utilize existing method

- en/orm/query-builder.rst
This section isn't a child of the "Using SQL Functions" section, causing
it to act as a parent for the following "Custom Functions" section.
Also there are two "Window Functions" headings, causing the second one
to generate a not overly descriptive link anchor named `id0`.
> Properly nest window functions heading, rename to avoid duplicates.

- en/installation.rst
Since @othercorey [released version](https://github.com/cakephp/app/releases/tag/3.9.0) 3.9.0 for cakephp/app, we should update installation steps to use that version.
> Update installation.rst to specify cakephp/app to install ^3.9 version

- en/development/errors.rst
Use the correct method to access the $response object, which cannot be accessed directly.
> use getResponse() method, $response is protected.

- en/development/configuration.rst
Some new users don't seem to realize that the config changes are in memory.
> Add note about Configure::write()

- en/core-libraries/validation.rst
Please correct me if I'm wrong.
This method expects the **second parameter to be a _string_ error message**, while **_callable_ is passed at the third parameter**.
Original code reference: https://github.com/cakephp/cakephp/blob/master/src/Validation/Validator.php#L850-L866
```php 
/**
* Allows a field to be an empty string.
*
* This method is equivalent to calling allowEmptyFor() with EMPTY_STRING flag.
*
* @param string $field The name of the field.
* @param string|null $message The message to show if the field is not
* @param bool|string|callable $when Indicates when the field is allowed to be empty
* Valid values are true, false, 'create', 'update'. If a callable is passed then
* the field will allowed to be empty only when the callback returns true.
* @return $this
* @see …
```
> Update validation.rst 

- ja/orm/schema-system.rst
> Update doc (ja)

- en/core-libraries/events.rst
Return type of `array` must be set for `EventListenerInterface::implementedEvents`
> implementedEvents must return array

- en/controllers/middleware.rst
- en/development/routing.rst
- en/plugins.rst
- en/tutorials-and-examples/bookmarks/intro.rst
Routes connection/setup should be using the `RouterBuilder` instance.
Static methods of `Router` should only be used for URL generation.
> Remove references to methods of `Router` related to routes setup.
