cakephp/docs

- en/development/sessions.rst
- fr/controllers/components/authentication.rst
- fr/controllers/components/security.rst
- fr/core-libraries/global-constants-and-functions.rst
- fr/core-libraries/text.rst
- fr/development/sessions.rst
- fr/orm/database-basics.rst
- fr/orm/retrieving-data-and-resultsets.rst
- fr/orm/saving-data.rst
- fr/views.rst
- fr/views/helpers/url.rst
Catch up for the French translation.
First PR of several to come, there is still work to do.
> 3.0 - French catch up

- en/controllers/components/request-handling.rst
- fr/controllers/components/request-handling.rst
@antograssiot I need someone to go through this
> [fr] #4297

- fr/appendices/3-4-migration-guide.rst
- fr/controllers/components/authentication.rst
> [fr] #4325

- en/chronos.rst
I think I got all formatting methods.
Refs #4340
> Document most of the other datetime formatting methods.

- fr/appendices/orm-migration.rst
- fr/chronos.rst
- fr/orm/entities.rst
- ja/appendices/orm-migration.rst
- ja/orm/entities.rst
For two of the PR I'm doing the sync from, I updated the japanese translation as well since it only involved code examples.
[fr/jp] Follow #4362
[fr/jp] Follow #4360
[fr] Follow #4345
> Sync french translation

- Makefile
- themes/cakephp/static/css/fonts.css
- themes/cakephp/static/css/style.css
`@import` statements need to be the first lines in a file or they don't
work.
Refs #4365
> Add fonts to be the first lines. (2.x)

- Makefile
- themes/cakephp/static/css/fonts.css
- themes/cakephp/static/css/style.css
`@import` statements need to be the first lines in a file or they don't work.
Refs #4365
> Add fonts to be the first lines. (3x)

- en/core-libraries/helpers/form.rst
It says to create a multiple select but does not pass the multiple option.
> Multiple Select

- en/intro/conventions.rst
- ja/intro/conventions.rst
> [ja] update conventions.rst

- en/views/helpers.rst
Added a documentation about view variable usage in helper.
> Add view variable usage example

- en/core-libraries/helpers/form.rst
- fr/core-libraries/helpers/form.rst
- ja/core-libraries/helpers/form.rst
http://book.cakephp.org/2.0/en/core-libraries/helpers/form.html#updates
The method list is wrapped with a `<blockquote>` tag incorrectly.
> Fix incorrect markup in form.rst

- en/appendices/3-4-migration-guide.rst
- en/controllers/components/authentication.rst
- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/bookmarks/part-two.rst
- fr/appendices/3-4-migration-guide.rst
- fr/controllers/components/authentication.rst
- fr/tutorials-and-examples/blog-auth-example/auth.rst
- fr/tutorials-and-examples/bookmarks/part-two.rst
> Update documentation for auth flash message change.

- en/development/testing.rst
change "you can not" to "it's possible to not" to avoid misunderstanding
> Update testing.rst to avoid misunderstanding

- ja/core-utility-libraries/security.rst
> [ja] update security.rst

- en/core-utility-libraries/number.rst
- fr/core-utility-libraries/number.rst
- ja/core-utility-libraries/number.rst
http://book.cakephp.org/2.0/en/core-libraries/helpers/number.html#NumberHelper::formatDelta
http://book.cakephp.org/2.0/fr/core-libraries/helpers/number.html#NumberHelper::formatDelta
http://book.cakephp.org/2.0/ja/core-libraries/helpers/number.html#NumberHelper::formatDelta
Thanks to **holywise**.
> Fix incorrect markup in number.rst

- en/orm/validation.rst
Fix syntax error in Foreign Key Rules
> Fix syntax in Foreign Key Rules

- en/appendices/3-4-migration-guide.rst
- en/views/helpers/paginator.rst
- fr/appendices/3-4-migration-guide.rst
- fr/views/helpers/paginator.rst
Follow #4412. I also removed a redundant "now" in the english translation and followed the convention for a `versionadded`.
> [fr] Follow #4412

- ja/views/helpers/number.rst
Hi, there.
I've translated the NumberHelper document.
> [ja]translation views/helpers/number.rst

- en/appendices/2-10-migration-guide.rst
- en/core-libraries/components/flash.rst
- en/core-libraries/helpers/flash.rst
> Add docs for stacked flash messages.

- en/orm/schema-system.rst
Docs for https://github.com/cakephp/cakephp/pull/9690
> Table to TableSchema

- en/orm/schema-system.rst
- fr/orm/schema-system.rst
Follows #4436.
I also changed a couple of the old class name that was missed in the original text.
> [fr] Follow #4436

- en/tutorials-and-examples/bookmarks/part-two.rst
This appeared magically in the second example but wasn't explicitly added. If you don't do it will direct you to home screen and you also won't see flash.
> Added unauthorizedRedirect to first Auth example

- themes/cakephp/static/css/style.css
> Fix navigation menu doesn't display if short width (for 1.3 branch)

- themes/cakephp/static/css/style.css
> Fix navigation menu doesn't display if short width (for 1.2 branch)

- themes/cakephp/static/css/style.css
> Fix navigation menu doesn't display if short width (for 1.1 branch)

- themes/cakephp/static/css/style.css
> Fix navigation menu doesn't display if short width (for 2.x branch)

- themes/cakephp/static/css/responsive.css
- themes/cakephp/static/css/style.css
> Backport: Fix can't access navigation if short width (1.1 book)

- themes/cakephp/static/css/responsive.css
- themes/cakephp/static/css/style.css
> Backport: Fix can't access navigation if short width (1.2 book)

- fr/contributing/cakephp-coding-conventions.rst
- ja/contributing/cakephp-coding-conventions.rst
- pt/contributing/cakephp-coding-conventions.rst
follows 2e3abe5b8dd63d3a7d49814a9de98437babbeffd
> [fr][ja][pt] follows en version

- en/views/helpers.rst
- en/views/helpers/breadcrumbs.rst
- fr/views/helpers.rst
- fr/views/helpers/breadcrumbs.rst
This is a first draft for the BreadcrumbsHelper documentation.
There is most certainly room for improvements (and probably build fixes :smile:)
Once we have something approved in English, I'll take care of the French translation.
Refs https://github.com/cakephp/cakephp/pull/9562
> BreadcrumbsHelper documentation

- en/orm/entities.rst
I hope I did it right. It was always confusing to me what was the accessor and what was the mutator.
/cc @davidyell
> Restructure accessor / mutator chapter

- en/models/associations-linking-models-together.rst
- fr/models/associations-linking-models-together.rst
I also completely rewritten the english sentence as I found it really confusing. Feel free to give me your opinion on it.
> [fr] Follow #4467

- en/orm/saving-data.rst
Mention that associations need to be hydrated first before patching.
Refs cakephp/cakephp#9739
> Update Documentation for Converting HasMany Associations

- en/orm/associations.rst
This option was missing, although it works just like in the other cases.
> Add bindingKey option to belongsToMany

- en/core-libraries/email.rst
Jokes are specific to a particular culture or language.
> Change `Magic inside!` to `Do something.`

- es/tutorials-and-examples/blog/part-two.rst
Solamente corregí la palabra ritas por rutas
> Actualización Archivo part-two.rst

- en/orm/entities.rst
Using both fields and properties can be confusing.
Refs cakephp/cakephp#8246
> Use properties consistently.

- en/console-and-shells.rst
- en/views/helpers/html.rst
- fr/appendices/3-4-migration-guide.rst
- fr/console-and-shells.rst
- fr/controllers/request-response.rst
- fr/views/helpers/form.rst
- fr/views/helpers/html.rst
I also modified some things on the original version
> [fr] Follow #4464

- en/migrations.rst
- fr/migrations.rst
Refs #4503 and cakephp/migrations#260
> Migrations : document how to bake a seed with data from the db

- en/appendices/3-4-migration-guide.rst
- en/console-and-shells/plugin-shell.rst
> Update docs for --cli option of plugin shell

- ja/orm/behaviors/counter-cache.rst
[ja]translation orm/behavior/counter-cache
> [ja]translation orm/behavior/counter-cache.rst

- ja/core-libraries/caching.rst
> [ja]translation core-libralies/caching.rst

- es/controllers/components.rst
I only add the missing right parenthesis
> right parenthesis was missing in the if

- ja/core-libraries/text.rst
Please don't yet merge this. Now translating.
> [ja] Translating core-libraries/text.

- en/bake/development.rst
- en/development/testing.rst
- fr/bake/development.rst
- fr/development/testing.rst
Remove test suite content as it is all wrong. Also fixup syntax highlighting that was previously wrong.
Refs #4519
> Remove outdated content & formatting

- fr/tutorials-and-examples/bookmarks/intro.rst
adding french translation to the note detailing the need to follow the case of the password member of the user class branch #4526
> adding french translation of the note in branch #4526

- en/bake/development.rst
- fr/bake/development.rst
- ja/bake/development.rst
- ja/development/testing.rst
> [ja] update translation.

- en/development/configuration.rst
- en/development/testing.rst
- en/plugins.rst
Explain how to use Application::bootstrap() better.
Refs cakephp/cakephp#9763
> Document using Application::bootstrap() better.

- en/appendices/3-4-migration-guide.rst
Missing docs for https://github.com/cakephp/cakephp/pull/9701
> Note the deprecations for ORM.

- en/appendices/3-4-migration-guide.rst
- en/views/helpers/form.rst
Refs cakephp/cakephp#9944
If I have missed references to FormHelper::input() on other pages please add commits on top of this.
> Update docs for FormHelper method changes.

- en/orm/associations.rst
.. _has-one-associations:
.. _belongs-to-associations:
.. _has-many-associations:
.. _belongs-to-many-associations
To be used by another PR.
> Add Ref Anchors/Labels

- en/orm/saving-data.rst
Requires https://github.com/cakephp/docs/pull/4567 to be merged ahead.
> Ref on how to setup saveStrategy

- en/orm/saving-data.rst
...which I introduced in the last PR. Sorry.
> fix typo saveStategy -> saveStrategy

- en/console-and-shells/cron-jobs.rst
People seem to not know the obvious way to silence for cronjobs.
> Note -q for cronjobs

- en/appendices/3-4-migration-guide.rst
- en/core-libraries/email.rst
Docs for https://github.com/cakephp/cakephp/pull/9921/
> 3.next email api

- en/appendices/3-4-migration-guide.rst
- fr/appendices/3-4-migration-guide.rst
Complete sync of the 3.4 migration guide in French.
> [fr] Update the 3.4 migrations guide

- themes/cakephp/layout.html
- themes/cakephp/static/css/responsive.css
Also fix the alignment of the book header as the indent was off.
> Update the top-menu to match cakephp.org

- en/core-libraries/validation.rst
> Attempt to clarify intent for allowEmpty()

- en/controllers/middleware.rst
Added note about updated `tests/bootstrap.php` when updating from an existing application.
> Further instructions for updating existing app to use middleware

- en/appendices/3-4-migration-guide.rst
- en/development/routing.rst
> Add documentation for routing improvments.

- fr/core-libraries/validation.rst
@cake17 @antograssiot Do the changes clarify things ?
> [fr] Follows #4586

- en/appendices/3-3-migration-guide.rst
- en/core-libraries/global-constants-and-functions.rst
- en/deployment.rst
- en/development/debugging.rst
Docs for https://github.com/cakephp/cakephp/pull/9989
> Add dd() docs.

- en/appendices/3-4-migration-guide.rst
> Add info about change in default behavior of HtmlHelper::scriptBlock().

- en/appendices/3-4-migration-guide.rst
refers to cakephp/cakephp#10000
> Add a note on setMatching Behavior and fix listing

- en/controllers/middleware.rst
- fr/appendices/3-3-migration-guide.rst
- fr/controllers/middleware.rst
- fr/core-libraries/global-constants-and-functions.rst
- fr/deployment.rst
> [fr] 3.0 sync

- en/appendices/3-4-migration-guide.rst
> Add the Visibility Changes section to 3.4 migration guide

- en/appendices/3-4-migration-guide.rst
Following cakephp/cakephp#9999
> Added translationField() to migration guide.

- en/orm/behaviors/translate.rst
Following cakephp/cakephp#9999
> Added an example for translationField() method

- en/orm/behaviors/counter-cache.rst
I added the missing CounterCache ignoreDirty doc. As I wasn't able to run the docs locally, I hope it's fine this way.
> Add CounterCache ignoreDirty option doc

- en/orm/behaviors/counter-cache.rst
- fr/orm/behaviors/counter-cache.rst
I also rephrased the original sentence and wrapped the long lines. Feel free to comment on it.
> [fr] Follows #4605

- en/migrations.rst
- fr/migrations.rst
> Update the docs with the recent additions to the Migrations plugin

- en/views/json-and-xml-views.rst
Hi,
Add Code Example use XmlView and JsonView in Doc
> Add Code Example use XmlView and JsonView in Doc

- en/orm/database-basics.rst
In https://github.com/cakephp/app/pull/473 , 
I added a new configuration on config/bootstrap.php
so, I think that we have to update the document.
I added a line in the doc.
> follow https://github.com/cakephp/app/pull/473

- fr/orm/database-basics.rst
- fr/views/json-and-xml-views.rst
Let me know if this needs some corrections
> [fr] #4618, e5d768b612ab6ec9eba092f21da08f694809b066

- en/appendices/3-4-migration-guide.rst
Ref: https://github.com/cakephp/cakephp/pull/9996
@markstory I hope that's correct and was just missing. In case it is not, just close this PR. I didn't want to ask if to PR for such a small change.
> 3.4 migration getEvent/getData

- en/controllers/components.rst
- fr/console-and-shells/helpers.rst
- fr/controllers/components.rst
- fr/models/data-validation.rst
I slightly modified some sentences for max/min length.
> [fr] Sync 2.x docs

- en/console-and-shells.rst
Might very well be the smallest change ever in a PR.
> Minor typo fix

- ja/views/helpers/breadcrumbs.rst
> [Ja] mod Breadcrumbs title.

- en/contributing/code.rst
Remove the obvious falsehoods and outdated workflow from the 2.x docs.
Refs #4629
> Remove obvious misinformation in 2.x contribution docs.

- en/appendices/3-4-migration-guide.rst
For https://github.com/cakephp/cakephp/pull/9769
> 3.4 config deprecations

- fr/appendices/3-4-migration-guide.rst
- fr/views/helpers/breadcrumbs.rst
Refs #4548 - f51eea379582f6de29c1066c85576b5d5e58e29e
> [fr] 3.next sync

- en/orm/retrieving-data-and-resultsets.rst
- Mark chapters that are mostly about contain
- Mark chapters that are mostly about matching/join
- Change chapter depth/levels
Ref: https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html
> add contain keyword to eager loading chapter name

- pt/tutorials-and-examples/blog/part-three.rst
> Blog Tutorial [pt-br]

- ja/core-libraries/global-constants-and-functions.rst
- ja/orm/retrieving-data-and-resultsets.rst
- ja/views/json-and-xml-views.rst
Refs: #4639, #4640, #4652, #4653
> [ja] update translations.

- en/appendices/3-4-migration-guide.rst
- en/core-libraries/email.rst
For https://github.com/cakephp/cakephp/pull/10156
> Add docs for Email priority.

- en/orm/retrieving-data-and-resultsets.rst
Ref: https://book.cakephp.org/3.0/en/orm/entities.html#accessors-mutators
Ref: https://github.com/cakephp/cakephp/issues/10175#issuecomment-277534228
> virtualFields for custom displayField + Accessor != Mutator

- en/intro/conventions.rst
To be consistent with
- https://github.com/cakephp/docs/commit/1fdd9c64426ff04361753fbc723466e525246ead#diff-0f25022039cd5cf199f45ba8c741dd69R60
- https://github.com/cakephp/docs/commit/7303c1d2f6d9ca8fe2fd1e6ea8e1db659262b930#diff-776d15e4ce222db911060ce80ec83e50R345
- https://github.com/cakephp/docs/commit/a9989512622eac5eb71da1ed266ec15d30b4362b#diff-6da22e08cc7ff0c3e63087e7a531b063R15
> Table class names should end in Table

- ja/core-libraries/helpers/flash.rst
- ja/core-libraries/helpers/paginator.rst
- ja/models/data-validation.rst
> [ja] Sync 2.x docs

- en/orm/query-builder.rst
The original way it was written there i got the "title-id" as result.
> Correcting use of $query->func()->concat()

- en/development/testing.rst
> Use phpunit <6.0

- requirements.txt
> Use latest phpdomain to fix default array issues.

- ja/development/errors.rst
- ja/development/testing.rst
- ja/views/helpers/flash.rst
> [ja] improve translations and sync 3.0 docs.

- en/index.rst
How/where to set `|maxphpversion|`
> Up phpmaxversion

- en/orm/associations.rst
> Remove reference to a method that doesn't exist.

- en/controllers/middleware.rst
Adding a middleware to middleware doesnt make much sense.
That just confuses people, especially the ones new to that PSR concept.
> Better not to use the queue as middleware variable.

- themes/cakephp/layout.html
This problem exists only in the 3.0 docs.
> Restore "improve this doc" button

- themes/cakephp/static/app.js
- themes/cakephp/static/css/default.css
- themes/cakephp/static/search.js
> Improve Docs Search (for 1.1 branch)

- themes/cakephp/static/app.js
- themes/cakephp/static/css/default.css
- themes/cakephp/static/search.js
> Improve Docs Search (for 1.2 branch)

- themes/cakephp/static/app.js
- themes/cakephp/static/css/default.css
- themes/cakephp/static/search.js
> Improve Docs Search (for 1.3 branch)

- themes/cakephp/static/app.js
- themes/cakephp/static/css/default.css
- themes/cakephp/static/search.js
> Improve Docs Search (for 2.x branch)

- en/orm/saving-data.rst
> Small typo on Saving Multiple Entities

- en/views/helpers/form.rst
- fr/views/helpers/form.rst
- ja/views/helpers/form.rst
> Update param name of FormHelper::create().

- es/404.rst
- es/tutorials-and-examples/bookmarks/intro.rst
This is a proposal of spanish translation for de 1st part of the Bookmarker Tutorial.
> Update intro.rst & 404.rst - Spanish translation

- es/appendices/glossary.rst
Proposal of corrections for the spanish translation of glossary.rst
> Update glossary.rst - [es] translation

- es/bake.rst
Proposal of sapanish translation for bake.srt
> Update bake.srt - [es] Spanish translation

- es/bake/usage.rst
Proposal of corrections for the spanish translation of usage.rst
> Update usage.rst - [es] corrections

- es/appendices/3-x-migration-guide.rst
Proposal of corrections for the spanish translation of 3-x-migration-guide.rst
> Update 3-x-migration-guide.rst - [es] translation

- ja/orm/query-builder.rst
Remove  
Remove duplicate from sample code.
> Clean up query-builder.rst

- en/installation.rst
I think the minimum PHP version also should be corrected
> [en] Installation corrected PHP version  info

- es/tutorials-and-examples/bookmarks/part-two.rst
Proposal for the spanish translation of part-two.rst
> Update part-two.rst - Spanish translation

- ja/tutorials-and-examples/blog-auth-example/auth.rst
- ja/tutorials-and-examples/blog/part-three.rst
- ja/tutorials-and-examples/blog/part-two.rst
- ja/tutorials-and-examples/bookmarks/part-two.rst
> [ja] update tutorials-and-examples

- en/development/configuration.rst
Ref: https://github.com/cakephp/docs/pull/4779
> 3.x Don't recommend to disable generic tables for cake bake

- ja/development/configuration.rst
> [ja] update configuration.rst

- en/orm/entities.rst
Ref Feature Issue: https://github.com/cakephp/cakephp/issues/10292
Ref Feature PR: https://github.com/cakephp/cakephp/pull/10366
> 3.4.3 Add docs for EntityTrait::getDirty()

- en/orm/entities.rst
Ref: https://github.com/cakephp/docs/pull/4796
> Note that getDirty was added in 3.4.3

- en/core-libraries/security.rst
- en/core-libraries/validation.rst
- en/development/testing.rst
- en/views/helpers/form.rst
- en/views/helpers/paginator.rst
- en/views/helpers/time.rst
- en/views/helpers/url.rst
- fr/core-libraries/security.rst
- fr/core-libraries/validation.rst
- fr/development/testing.rst
- fr/views/helpers/form.rst
- fr/views/helpers/paginator.rst
- fr/views/helpers/time.rst
- fr/views/helpers/url.rst
- ja/core-libraries/security.rst
- ja/core-libraries/validation.rst
- ja/development/testing.rst
- ja/views/helpers/form.rst
- ja/views/helpers/paginator.rst
- ja/views/helpers/time.rst
- ja/views/helpers/url.rst
I added PR cakephp/cakephp-api-docs#82 ( https://api.cakephp.org repos ) and it was merged.
This PR applies that function.
> [en][fr][ja]3.x The link to the API document is always the latest version.

- en/tutorials-and-examples.rst
- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/database.rst
- en/tutorials-and-examples/cms/installation.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
In the discussion of #3806 and some additional discussion in slack, building a new tutorial that combines the best elements of the blog tutorial and the more advanced topics from the bookmarker into a single tutorial was determined to be a good course of action. This is the start of that new tutorial. Long term we'd be dropping the blog and bookmarker tutorials from the documentation to streamline the experience for new developers.
> Start adding new tutorial

- en/tutorials-and-examples/cms/database.rst
Fill out another section for the new tutorial.
> Add the model section to the CMS tutorial.

- es/contributing/code.rst
> [ES] contributing\code.rst

- es/contributing/tickets.rst
Spanish translation of contributing\tickets.rst
> [ES] tickets

- es/contributing/documentation.rst
Spanish translation of contributing\documentation.rst
> [ES] documentation

- es/contributing/cakephp-coding-conventions.rst
Spanish translation of contributing\cakephp-coding-conventions
> [ES] cakephp-coding-conventions

- es/contributing/backwards-compatibility.rst
Spanish translation of contributing\backwards-compatibility.rst
> [ES] backwars-compatibility

- es/contributing/code.rst
> [ES] Update code.rst

- es/index.rst
Indentations fixed trying to fix the use of the image
> [ES] Update index.rst

- es/contributing/backwards-compatibility.rst
> [ES] Update backwards-compatibility.rst

- en/views/helpers/form.rst
Fix the links and the first argument name of create().
> Link to the API documents of the current version.

- es/intro/where-to-get-help.rst
Spanish translation of where-to-get-help.rst
> [ES] where-to-get-help.rst

- es/intro.rst
- es/views.rst
Spanish translation of intro.rst and tags in view.rst needed for references
> [ES] intro.rst

- es/intro/where-to-get-help.rst
> Fix CI Failed: Title underline too short.

- en/tutorials-and-examples/cms/articles-controller.rst
Another small section for the new tutorial
> Start the controller chapter of the CMS tutorial.

- en/core-libraries/behaviors/tree.rst
> Fix code typo in Node Level (Depth)

- en/appendices/3-4-migration-guide.rst
- en/controllers/components/authentication.rst
> Update the documentation around redirectUrl()

- en/appendices/glossary.rst
Relates to cakephp/cakephp#10476
> Add a more complex router array example

- en/appendices/3-4-migration-guide.rst
> Update migration guide for possible variadic issue.

- fr/controllers/request-response.rst
Some typo fix and fix some words order to make the sentences more understandable for french speaking users.
> Some typo fix and fix some words order

- en/appendices/3-5-migration-guide.rst
> 3.next Update Deprecations

- en/tutorials-and-examples/cms/tags-and-users.rst
Another small section for the CMS tutorial.
> Add user code creation and password hashing.

- en/views/helpers/form.rst
> [en] update form.rst

- en/appendices/3-5-migration-guide.rst
- en/controllers/middleware.rst
- en/controllers/request-response.rst
> Add docs for new Cookie features.

- fr/controllers/request-response.rst
I think GTranslate was used too much on this part :D
> [FR] Request-response - correct some nonsense

- ja/views/helpers/form.rst
follows #4598, #4829, #4834, #4913
> [ja] update form.rst.

- en/controllers/pages-controller.rst
> Revert "Update pages-controller.rst"

- en/controllers/request-response.rst
> Document how to use param() in older CakePHP.

- en/controllers/request-response.rst
references still to `query()` and it should be `getQuery()`
> Update changed method

- en/orm/query-builder.rst
- fr/orm/query-builder.rst
- ja/orm/query-builder.rst
> 3.x - Update examples to reflect order change of generated conditions.

- en/orm/retrieving-data-and-resultsets.rst
- fr/orm/retrieving-data-and-resultsets.rst
> Add note on aliases in contain() fields.

- en/appendices/3-5-migration-guide.rst
Document the changes made in cakephp/cakephp#10593
> Document changes in cakephp/cakephp#10593

- themes/cakephp/static/app.js
> Enable anchor of submenu and megamenu. (for 1.2)

- themes/cakephp/static/app.js
> Enable anchor of submenu and megamenu. (for 1.1)

- themes/cakephp/static/app.js
> Enable anchor of submenu and megamenu. (for 1.3)

- themes/cakephp/static/app.js
> Enable anchor of submenu and megamenu. (for 2.0)

- es/core-libraries/text.rst
- es/intro/conventions.rst
Spanish translation of Conventions.rst
> [ES] conventions.rst

- en/orm/validation.rst
> Add docs for allowMultipleNulls option.

- en/appendices/3-5-migration-guide.rst
> Document changes in cakephp/cakephp#10631

- fr/controllers/components/security.rst
Text blocks under "allowedControllers", "allowedActions", "unlockedFields" and "validatePost" were incorrect
> Fix layout

- en/appendices/2-10-migration-guide.rst
- en/core-libraries/global-constants-and-functions.rst
> Document changes in cakephp/cakephp#10647

- fr/controllers/components/request-handling.rst
- fr/orm/database-basics.rst
- fr/orm/entities.rst
- fr/views.rst
- fr/views/cells.rst
Fix some typo and add the translation of one section
> Fix typo and add translation

- pt/console-and-shells/cache.rst
- pt/console-and-shells/cron-jobs.rst
- pt/console-and-shells/orm-cache.rst
- pt/development/configuration.rst
Completed **32%** of the translation of the files into Portuguese, being used as a base the English and French languages.
> [pt] Translation Updated

- en/controllers/components/authentication.rst
- fr/controllers/components/authentication.rst
- ja/controllers/components/authentication.rst
ServerRequest class reference (Refs: #4982).
And rename the namespace of Response from Cake\Network to Cake\Http.
> [fr][ja] follows #4982

- en/core-libraries/text.rst
- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/database.rst
Complete the ArticlesController section.
> Continue the CMS tutorial

- en/appendices/3-5-migration-guide.rst
> Document changes in cakephp/cakephp#10660

- en/core-libraries/hash.rst
- fr/core-libraries/hash.rst
- ja/core-libraries/hash.rst
https://api.cakephp.org/3.4/class-Cake.Utility.Hash.html#_remove
> [en][fr][ja] fix Hash::remove() definition.

- en/console-and-shells.rst
Documents the changes made in cakephp/cakephp#10661
> Add docs for Cake\Console\ConsoleOptionParser::setHelpAlias()

- en/appendices/3-5-migration-guide.rst
- en/orm/validation.rst
Fefers:
cakephp/cakephp#10691
cakephp/cakephp#10707
> 3.next - More deprecations

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/database.rst
- en/tutorials-and-examples/cms/installation.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
Found a few typos and missing instructions during the tutorial.
> CMS Tutorial clarity

- es/core-libraries/app.rst
I've added some notes to explain some ambiguous issues
> Translation of app.rst to spanish

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
Discovered a few issues while going through the CMS tutorial from scratch.
> CMS Tutorial fixes

- en/development/configuration.rst
As discussed in #4895 and provided (in comments) to core.php in https://github.com/cakephp/cakephp/pull/10560
> Added documentation for App.fullBaseUrl and App.base

- en/orm/validation.rst
inform existence of getErrors() function
> inform existence of getErrors function

- fr/views.rst
> [FR] Fix typo in views.rst

- fr/appendices/3-4-migration-guide.rst
- fr/controllers/components/authentication.rst
- fr/controllers/request-response.rst
- fr/core-libraries/internationalization-and-localization.rst
- fr/core-libraries/validation.rst
- fr/development/routing.rst
- fr/views/helpers/form.rst
Follows #4829, #4840, #4841, #4863, #4871, #4880, #4884, #4887, #4889
> [fr] And another batch of FR translations

- fr/console-and-shells.rst
- fr/controllers/request-response.rst
- fr/core-libraries/email.rst
- fr/development/routing.rst
- fr/installation.rst
- fr/orm/database-basics.rst
- fr/orm/query-builder.rst
Follows #4891, #4903, #4923, #4926, #4929, #4933, #4949, #4952
> [fr] Batch of FR translations

- en/intro/cakephp-folder-structure.rst
Fix up incorrect information in the folder description. I've removed the first file manifest as I don't think it is overly helpful and will get out of date easily.
Refs #5054
> Update folder structure.

- en/console-and-shells/cron-jobs.rst
- en/development/testing.rst
- en/orm/validation.rst
- fr/console-and-shells/cron-jobs.rst
- fr/controllers.rst
- fr/controllers/components/csrf.rst
- fr/controllers/components/security.rst
- fr/core-libraries/email.rst
- fr/core-libraries/httpclient.rst
- fr/development/dispatch-filters.rst
- fr/development/testing.rst
- fr/orm/database-basics.rst
- fr/orm/entities.rst
- fr/orm/saving-data.rst
- fr/orm/validation.rst
- fr/tutorials-and-examples/blog/part-two.rst
Follows #4954, #4960, #4961, #4971, #4975, #4986, #4992 
I also modified some formating on the main docs.
> [fr] Another batch of translations

- en/controllers/components/security.rst
- en/orm/entities.rst
- en/orm/query-builder.rst
- en/orm/validation.rst
- fr/controllers/components/authentication.rst
- fr/controllers/components/security.rst
- fr/core-libraries/email.rst
- fr/development/testing.rst
- fr/intro/cakephp-folder-structure.rst
- fr/orm/associations.rst
- fr/orm/database-basics.rst
- fr/orm/entities.rst
- fr/orm/query-builder.rst
- fr/orm/saving-data.rst
- fr/orm/validation.rst
Follows #4994, #4995, #5002, #5004, #5018, #5020, #5022, #5026, #5030, #5039, #5042, #5047, #5055.
As usual, I may have done some small modifications to the original version.
> [fr] FR translations

- en/development/routing.rst
Custom router class call mistyped
> Class call fix

- en/tutorials-and-examples/bookmarks/part-two.rst
It should be the 'add' action and not the logout action because that one was already there.
> Fixed mistake

- en/core-libraries/logging.rst
The old information is inaccurate. I've tried to add information about the way levels and scopes really work without adding too much text. My native language isn't English.
> Update information about levels and scopes

- en/core-libraries/logging.rst
- fr/core-libraries/logging.rst
Follows #5062.
Some minor formating modifications done on the original version.
> [fr] Follows #5062

- pt/core-libraries/inflector.rst
- pt/orm/associations.rst
- pt/orm/database-basics.rst
- pt/orm/deleting-data.rst
- pt/orm/entities.rst
- pt/orm/query-builder.rst
- pt/orm/saving-data.rst
- pt/orm/validation.rst
- pt/views/helpers/form.rst
Tradução completa da página Salvando Dados
> Incluído página Salvando Dados

- en/views/json-and-xml-views.rst
- fr/controllers/components/flash.rst
- fr/views/helpers/flash.rst
- fr/views/json-and-xml-views.rst
Follows #5066 & #5067
I also rephrased some sentences in the original version that I found confusing. I'll be glad if a native speaker can confirm this is valid.
> [fr] Follows #5066 & #5067

- en/core-libraries/global-constants-and-functions.rst
> Added documentation for Global Translation Functions supporting Context

- en/appendices/3-5-migration-guide.rst
- en/controllers/middleware.rst
- en/controllers/request-response.rst
- fr/appendices/3-5-migration-guide.rst
- fr/controllers/middleware.rst
- fr/controllers/request-response.rst
I rewrote a middleware description as it was probably a copy/paste of the one above in the summary of the available middlewares.
Follows #4912.
> [fr] Follows #4912

- en/orm/retrieving-data-and-resultsets.rst
Clarify nested contain not filtering records out and link to matching() docs.
Refs #4874
> Update docs to clarify contain() usage.

- fr/orm/retrieving-data-and-resultsets.rst
The only thing remaining to sync for the 3.X branches is the CMS tutorial.
> [fr] Follows #5081

- en/orm/database-basics.rst
Explain a little bit cakephp behavior with sqlite database name.
> Add information about sqlite

- en/console-and-shells/schema-management-and-migrations.rst
- en/development/testing.rst
- en/models/model-attributes.rst
- fr/appendices/2-10-migration-guide.rst
- fr/console-and-shells/schema-management-and-migrations.rst
- fr/core-libraries/internationalization-and-localization.rst
- fr/core-utility-libraries/string.rst
- fr/development/exceptions.rst
- fr/development/testing.rst
- fr/models/model-attributes.rst
- fr/models/virtual-fields.rst
- Follows #4685, #4697, #4727, #4799, #4820 
- Full translation of the 2.10 migration guide
> [fr] First round of 2.x translations

- fr/appendices/2-10-migration-guide.rst
- fr/appendices/glossary.rst
- fr/core-libraries/behaviors/tree.rst
- fr/core-libraries/global-constants-and-functions.rst
- fr/core-utility-libraries/hash.rst
- fr/installation.rst
- fr/tutorials-and-examples/blog/blog.rst
- fr/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
Follows #4875, #4883, #4885, #4947, #4967 and fix the typo seen by @cake17 on #5089
> [fr] Another batch for 2.X

- fr/console-and-shells/schema-management-and-migrations.rst
- fr/core-libraries/behaviors/translate.rst
- fr/core-libraries/global-constants-and-functions.rst
- fr/development/configuration.rst
- fr/development/testing.rst
Follows #4972, #5024, #5078 and a867312
> [fr] Another batch of 2.X translations

- en/core-libraries/internationalization-and-localization.rst
Added a short example ho how prepare a translation file for __x()
> Example how to use __x in .po file missing

- en/orm/database-basics.rst
added keyword new in complex data type query example
> added new keyword

- fr/orm/behaviors/tree.rst
- fr/orm/database-basics.rst
Follows #5102, #5103 and #5104.
> [fr] Follows recent modifications

- en/appendices/3-5-migration-guide.rst
And, I fixed the namespace of TypedResultTrait.
> Add more deprecated methods

- en/elasticsearch.rst
- fr/appendices/3-5-migration-guide.rst
- fr/development/testing.rst
- fr/elasticsearch.rst
- fr/orm/table-objects.rst
- ja/elasticsearch.rst
Follows #5106, #5123 & #5130
I posted a comment on #5130 because I think the wrong class might have been included. See https://github.com/cakephp/docs/pull/5130#issuecomment-318842069
I'll be glad revert it back and fix if I'm mistaken :smile: 
(I took care of the JA version for #5130)
> [fr] Follows #5106, #5123 & #5130

- en/orm/retrieving-data-and-resultsets.rst
Refs #4545
I totally forgot about this issue 😞
> Fix incorrect examples of MapReduce

- fr/core-libraries/collections.rst
- fr/tutorials-and-examples/blog/part-two.rst
[fr] Follows #5143 and replaces #5140
> [fr] Follows #5143 and replaces #5140

- en/models/retrieving-your-data.rst
'"' double quote is not necessary.
'User2.status' this also work.
do not put table name in quotes.
> Removed extra quotes.

- en/controllers/components/cookie.rst
> Add note to CookieComponent docs.

- en/orm/associations.rst
Ref: https://github.com/cakephp/docs/issues/5038
Added HABTM and BTM as people may actually search for that string to find the feature/functionality.
> Add note about HABTM rename

- en/development/testing.rst
> Update example for loading plugin fixtures.

- en/orm/saving-data.rst
- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/authentication.rst
Only the conclusion remains. If anyone has suggestions on how to wrap this up or where to recommend people go next I'm all ears 😸
> More CMS tutorial

- pt/views.rst
Alterando palavra "flexvel" para "Flexível". 
Changing "flexvel" to "flexible".
> Changing "flexvel" to "flexible" - pt_BR

- en/development/sessions.rst
Ref: https://github.com/cakephp/app/pull/537
> Update example session.sql

- en/orm/associations.rst
> Added the default hasMany saveStrategy

- en/appendices/3-6-migration-guide.rst
- en/appendices/3-x-migration-guide.rst
- en/console-and-shells.rst
- en/console-and-shells/orm-cache.rst
- en/console-and-shells/schema-cache.rst
- en/deployment.rst
- en/migrations.rst
- en/orm.rst
- en/orm/database-basics.rst
Update docs for schema_cache change.
See cakephp/cakephp#10977
> 3.6 - Schema cache

- ja/tutorials-and-examples/bookmarks/part-two.rst
"ログアウトします。" is "I will log out." In English.
I changed to the correct Japanese "ログアウトしました。"
> Small Typo

- en/installation.rst
`~3.5` is the same as `3.5.*`. no need to duplicate here.
> Use proper semver operator.

- en/console-and-shells.rst
- en/console-and-shells/completion-shell.rst
- en/deployment.rst
- fr/appendices/3-6-migration-guide.rst
- fr/appendices/3-x-migration-guide.rst
- fr/console-and-shells.rst
- fr/console-and-shells/completion-shell.rst
- fr/console-and-shells/orm-cache.rst
- fr/console-and-shells/schema-cache.rst
- fr/deployment.rst
- fr/migrations.rst
- fr/orm.rst
- fr/orm/database-basics.rst
@markstory I took care of replacing some `orm_cache` mentions that were still lying around.
> [fr] Follows #5203

- ja/development/routing.rst
Fixed Japanese explanation.　日本語の説明文を修正しました。
> [ja] Update routing.rst

- fr/orm/validation.rst
Correction of a minor error in the doc about validation.
> Correction of a translation error

- fr/tutorials-and-examples.rst
- fr/tutorials-and-examples/cms/authentication.rst
- fr/tutorials-and-examples/cms/tags-and-users.rst
And that's it for the tutorial which is now fully translated.
> [fr] Translate the last chapter of the CMS tutorial

- fr/orm/validation.rst
Une phrase non traduite + deux petites erreurs d'accord.
> Mise à jour validation.rst

- en/contents.rst
- en/phinx.rst
- en/phinx/commands.rst
- en/phinx/configuration.rst
- en/phinx/goals.rst
- en/phinx/install.rst
- en/phinx/intro.rst
- en/phinx/migrations.rst
- en/phinx/seeding.rst
Copied documentation form sphinx repo here, so that we only have one place to update documentation and a single way for deploying it.
> Added phinx docs

- fr/development/testing.rst
Fix sentences, fix url to fr source, finishing FR translation
> Updating testing.rst [FR]

- en/core-libraries/collections.rst
> Add information about performance improvement in Collection

- pt/appendices/glossary.rst
- pt/development/rest.rst
- pt/development/routing.rst
- pt/plugins.rst
Tradução para PT plugins e rest
> Tradução para PT plugins e rest

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/database.rst
- en/tutorials-and-examples/cms/installation.rst
Fixes a few small mistakes in the first few chapters of the CMS tutorial. I plan on going through the remaining chapters soon.
> Fix up small mistakes I found in the CMS tutorial.

- en/debug-kit.rst
Be clearer on what debugkit does and where you should use it.
> Update DebugKit documentation

- fr/contents.rst
- fr/core-libraries/collections.rst
- fr/debug-kit.rst
- fr/installation.rst
- fr/phinx.rst
- fr/phinx/commands.rst
- fr/phinx/configuration.rst
- fr/phinx/migrations.rst
- fr/phinx/seeding.rst
- fr/tutorials-and-examples/cms/articles-controller.rst
- fr/tutorials-and-examples/cms/database.rst
- fr/tutorials-and-examples/cms/tags-and-users.rst
> [fr] follows #5244, #5247

- en/installation.rst
Corrected format from self PR https://github.com/cakephp/docs/pull/5257
> Correct format

- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/installation.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
* Fix mistakes in code,
* Add missing authorization
> A few more tutorial fixes.

- en/contributing/backwards-compatibility.rst
- en/contributing/cakephp-coding-conventions.rst
Also clarified version for deprecation annotation.
> Clarify deprecations and void BC.

- en/orm/saving-data.rst
> Clarify docs regards cakephp/cakephp#11223

- en/appendices/3-6-migration-guide.rst
> Document changes in cakephp/cakephp#11233

- zh/core-libraries/events.rst
Translate "Events System" to Chinese.
> Translate to Chinese

- en/getting-started/cakephp-structure.rst
> beforeFilter should be listed before afterFilter, which should be listed after

- en/tutorials-and-examples/blog/part-two.rst
Models are the place to be for actual business logic.
https://book.cakephp.org/2.0/en/models.html
> Fix false statement about business logic

- en/intro/cakephp-folder-structure.rst
I'm not a English expert, but it seems to be used rarely.
https://en.wiktionary.org/wiki/publically
> Publically seems to be used rarely

- en/intro/conventions.rst
Clearly divide the "View Conventions" from the summary.
> Add sub title for summary

- en/intro/conventions.rst
https://en.wikipedia.org/wiki/PascalCase
Probably there are many more such statements, but let's fix this very important page first.
> The names are PascalCase, not camelCase

- en/intro/conventions.rst
https://github.com/CakeDC/cakephp/blob/3.5.2/composer.json#L59
https://github.com/CakeDC/app/blob/3.3.5/composer.json#L30
> We actually only use PSR-4

- en/plugins.rst
Added a reference to Mixer plugin.
> Add reference to Mixer

- en/controllers/middleware.rst
One of the things that seems to also be needed (for me at least) is that the file in app/config/requirements.php needs to be added as well to existing projects
> add instructions for adding app/config/requirements.php

- en/controllers/middleware.rst
Forgot to change the number of steps to complete in the paragraph following the previous change.  Sorry.
> there are now three steps rather then 2 information the `Adding the...`

- en/tutorials-and-examples/bookmarks/intro.rst
This tutorial use PHP’s built-in webserver and not apache.
> wrong note on error 404 and apache

- en/intro/conventions.rst
> Expand and clarify entity/model conventions.

- en/bake/development.rst
> Add info about setting custom theme as default

- en/appendices/3-6-migration-guide.rst
Document changes in:
* cakephp/cakephp#11292
* cakephp/cakephp#11286
> 3.next changes

- en/orm/validation.rst
https://github.com/cakephp/cakephp/issues/9387#issuecomment-244091882
> add a sample for conditional rules

- en/tutorials-and-examples/cms/database.rst
Some people found the old language to be confusing. Hopefully this is better.
cc @chinpei215
> Use a simpler benefit of composite primary key support.

- fr/phinx.rst
French traduction of the main page of phinx tool.
> French traduction.

- en/views/helpers/form.rst
> Fix Form::select multiple option's example code

- ja/views/helpers/form.rst
:bow:
https://github.com/cakephp/docs/blob/3.0/en/views/helpers/form.rst#creating-select-pickers
```
.. _create-select-picker:
Creating Select Pickers
~~~~~~~~~~~~~~~~~~~~~~~
```
https://github.com/cakephp/docs/blob/3.0/ja/views/helpers/form.rst#選択ピッカーの作成
```
.. _create-select-picker:
選択ピッカーの作成
------------------
```
> [ja] Fix heading level

- en/controllers.rst
https://github.com/cakephp/cakephp/issues/3861
> mention to Event address

- en/epub-contents.rst
- en/intro.rst
- en/intro/conventions.rst
- en/pdf-contents.rst
- en/quickstart.rst
- en/tutorials-and-examples.rst
- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
Continue to build the bookmarker and blog tutorials, so that incoming links work, but do not include them in the visible table of contents.
> Mainline CMS tutorial

- en/controllers/components/request-handling.rst
- en/views/helpers/form.rst
- en/views/helpers/url.rst
> Remove unnecessary escape

- en/plugins.rst
- en/views/themes.rst
A collegue of mine created a theme plugin by hand and could not successfullly load a helper class he added in there.
> Improve wording, link to creating a plugin

- en/views/themes.rst
https://api.cakephp.org/3.5/class-Cake.View.View.html#_theme
https://api.cakephp.org/3.5/class-Cake.View.View.html#_setTheme
> Use new setTheme(), instead of deprecated theme()

- en/appendices/3-6-migration-guide.rst
- en/core-libraries/caching.rst
- en/orm/database-basics.rst
> Document utf8mb4 change in 3.6

- en/appendices/3-6-migration-guide.rst
- en/orm/query-builder.rst
> Add docs for identifier expressions.

- en/tutorials-and-examples/cms/tags-and-users.rst
See https://github.com/cakephp/docs/pull/5357
You could also remove everything except add().
> Remove <?php

- en/appendices/3-6-migration-guide.rst
- en/development/routing.rst
- en/orm/query-builder.rst
> Add docs for entity routing.

- en/phinx/seeding.rst
fix mistake in 2nd code listing
> Fix A Typo

- en/core-libraries/caching.rst
fix path for cache engine in plugin
> fix path for cache engine in plugin

- ja/models/model-attributes.rst
> [ja] Fix typo and wording

- en/core-libraries/collections.rst
- fr/core-libraries/collections.rst
- ja/core-libraries/collections.rst
- zh/core-libraries/collections.rst
> typo at collections.rst

- en/orm/query-builder.rst
*Corrected typo (intead -> instead)
> Correct typo in query-builder.rst

- en/controllers/middleware.rst
> Correct redundancy in middleware.rst

- en/controllers.rst
*Fixed grammatical error (you -> your)
> Corrected typo in controllers.rst

- pt/orm/behaviors.rst
- pt/orm/table-objects.rst
- pt/orm/behaviors.rst
- pt/orm/table-objects.rst
> [pt] behaviors page

- en/orm/query-builder.rst
> Correct error in Subqueries documentation

- en/orm/table-objects.rst
*Added the word that was missed in a sentence
> Correct mistake in table-objects.rst

- en/orm/entities.rst
*Removed unnecessary lines
*Correct grammatical errors
> Correct style and grammar errors in entities.rst

- en/orm/saving-data.rst
*Removed unnecessary blank lines
*Correct code style
> Correct style in saving-data.rst

- CODE_OF_CONDUCT.md
> Create  CODE_OF_CONDUCT.md

- fr/phinx.rst
The code block for phinx init was missing an empty line before
> Correction of a block of code

- en/orm/query-builder.rst
I don't know enough french or japanese to update those translations.
Refs cakephp/cakephp#11487
> Remove use of orWhere in english docs.

- en/core-libraries/app.rst
- en/development/configuration.rst
- en/development/testing.rst
- en/plugins.rst
Follow https://github.com/cakephp/cakephp/pull/11493 and https://github.com/cakephp/cakephp/pull/11494
> Fix testsuite definition and psr4

- ru/controllers/pages-controller.rst
> Update pages-controller.rst Translation

- ru/bake/development.rst
Translation development.rst into RU
> Translation development.rst into RU

- ru/bake/usage.rst
> Translation usage.rst into RU

- en/views/themes.rst
You can add to the documentation to clarify.
> Update themes.rst - Addition to documentation

- en/views/helpers/paginator.rst
corrected a typos in paginator.rst
> corrected a typos in paginator.rst

- en/contributing/cakephp-coding-conventions.rst
Maybe, need to add clarification in the doc: cakephp-coding-conventions.rst ?
> Maybe, need to add clarification in the doc ?

- en/appendices/3-6-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/11555
> Note for i18n translation cleanup.

- en/orm/behaviors/translate.rst
> Update e.g. regarding multiple translations saving

- en/core-libraries/form.rst
I read a bit the core code
looks `validationDefault` calls in https://github.com/cakephp/cakephp/blob/dff88e6c67ce3e34a9b3d8c0dd176120236be77b/src/Validation/ValidatorAwareTrait.php#L174
so, needs this `return` 
Refs: https://github.com/cakephp/docs/pull/5492
> return object

- en/appendices/3-6-migration-guide.rst
- en/development/configuration.rst
- en/views/helpers/url.rst
> Document timestamp option added in 3.6

- ru/orm/behaviors/tree.rst
translation of the missed English line in tree.rst into RU
> Translation of the missed English line in tree.rst

- ru/controllers/middleware.rst
Translation middleware.rst into ru
> Translation middleware.rst into ru

- ja/tutorials-and-examples/cms/articles-controller.rst
- Use space indent.
- Delete deleted code from original text ( https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/articles-controller.html#adding-simple-slug-generation )
> [ja]Fix CMS Tutorial

- fr/tutorials-and-examples/cms/authentication.rst
- ja/tutorials-and-examples/cms/authentication.rst
same as the #5508, only delete unnecessary code.
> [ja][fr]follows #5508

- en/controllers/components/request-handling.rst
- ru/controllers/components/request-handling.rst
Small typo corrections in english documentation.
> [ru] Full translation of request-handling.rst

- en/appendices/3-6-migration-guide.rst
- en/core-libraries/validation.rst
- en/orm/validation.rst
I've also done a small re-organization of the validation docs as more frequently used content was buried beneath creating custom providers.
> Document changes in cakephp/cakephp#11599

- zh/intro/where-to-get-help.rst
Translated intro/where-to-get-help.rst
> [zh] done where-to-get-help.rst

- en/controllers/middleware.rst
https://github.com/cakephp/app/issues/577
> using  correct time format

- en/development/errors.rst
Remove a the custom status code section and add those concepts to the application exception documentation.
> More improvements to the error docs.

- zh/intro/cakephp-folder-structure.rst
> [zh] done cakephp-folder-structure page

- en/tutorials-and-examples/cms/articles-controller.rst
This is the first time this file is mentioned in this tutorial so should include the namespace and use statement for Table
> added namespace to Table when creating ArticlesTable.php

- en/views/cells.rst
> Update doc how to set cell template with ViewBundler

- en/views/cells.rst
> Document cell options.

- zh/development/routing.rst
- zh/intro/conventions.rst
- zh/intro/where-to-get-help.rst
- zh/tutorials-and-examples.rst
- zh/tutorials-and-examples/cms/articles-controller.rst
- zh/tutorials-and-examples/cms/authentication.rst
- zh/tutorials-and-examples/cms/database.rst
- zh/tutorials-and-examples/cms/installation.rst
- zh/tutorials-and-examples/cms/tags-and-users.rst
- Fix make warning
- Add missing docs reqiured by zh/intro/conventions.rst (But not translated yet)
- Done intro/conventions.rst
> [zh] Done intro/conventions.rst

- en/development/configuration.rst
Fixed spelling in paragraph of Configuration Engines
> Fixed spelling of configuration

- ru/development/configuration.rst
Also translated titles of reference links
> [ru] Fixed 1 translation error in configuration.rst

- en/appendices/3-6-migration-guide.rst
- en/development/routing.rst
> Add docs for compact route targets.

- ja/views.rst
> [ja]Fix typo

- zh/tutorials-and-examples.rst
> Done ZH translation

- zh/tutorials-and-examples/cms/installation.rst
> Done cms/installation.rst

- en/development/errors.rst
https://github.com/cakephp/docs/issues/5619
> remove invalid parameter

- en/controllers/components/authentication.rst
Related to https://github.com/cakephp/cakephp/issues/11716
> Clarifying stateless authentication behavior

- zh/tutorials-and-examples/cms/installation.rst
> Remove english content

- zh/tutorials-and-examples/cms/database.rst
> Done database.rst

- zh/tutorials-and-examples/cms/database.rst
> fix format

- en/bake.rst
Refs https://github.com/cakephp/bake/issues/391 and https://github.com/cakephp/bake/issues/381#issuecomment-368099940
> Clarify Twig plugin loading

- en/appendices/3-6-migration-guide.rst
- en/development/configuration.rst
Docs for https://github.com/cakephp/cakephp/pull/11752
> Docs for consumeOrFail()

- en/core-libraries/events.rst
Changes to reflect method deprecation on 3.5.0
> eventManager() to getEventManager()

- en/appendices/3-6-migration-guide.rst
- en/contents.rst
- en/controllers/middleware.rst
- en/core-libraries/security.rst
- en/development/application.rst
- en/plugins.rst
Start the documentation updates for the new plugin objects.
Refs cakephp/cakephp#11564
> Start Plugin docs

- en/views/helpers/form.rst
Add note about workaround for IDs being appended to URLs
https://github.com/cakephp/cakephp/issues/11794
> Add note about form URL workaround

- en/orm/behaviors/translate.rst
- fr/orm/behaviors/translate.rst
- ja/orm/behaviors/translate.rst
Fixes the `locale()` usage + some minor corrections.
> Fix usage of `TranslateBehavior::locale()`.

- en/appendices/3-6-migration-guide.rst
First part of https://github.com/cakephp/cakephp/pull/11782
Maybe we can add more in detail docs inside the ORM chapters.
> Add migration notes for whereInList() and whereNotInList().

- en/views/helpers/form.rst
Refs cakephp/cakephp#10382 cc @Slessi
> Attempt to clarify form helper usage.

- en/debug-kit.rst
> Move README docs over & expand mail preview docs.

- en/orm/query-builder.rst
Want to be able to see what object is being passed here so I can type hint it in my IDE with greater ease.
> Where clause anonymous functions with hints

- en/core-libraries/global-constants-and-functions.rst
Translation global-constants-and-functions.rst into Ru
> Translation global-constants-and-functions.rst into Ru

- en/development/sessions.rst
These changes need to go to 3.next instead.
Reverts cakephp/docs#5678
> Revert "Update sessions.rst"

- en/plugins.rst
Translation plugins.rst into Ru
> Translation plugins.rst into Ru

- en/orm/retrieving-data-and-resultsets.rst
Also added a reference to the `sql()` function
> Hiding toArray() a bit more in the ORM docs

- en/intro/conventions.rst
Maybe need to add conventions about plugins? in conventions.rst
I'm not an expert, but it's necessary to add this to the agreements ? (but I can be wrong).
> Maybe need to add conventions about plugins?

- pt/core-libraries/events.rst
A translated documentation for the Event System for PT-BR lang
> Portuguese documentation for Events System

- en/development/testing.rst
Just changing the URL for the repo in github.
> Link http://phpdbg.com is gone

- en/controllers/components/security.rst
@markstory based on your changes in cakephp/cakephp#11954
> fix redirects for cakephp hosted within subfolders

- en/debug-kit.rst
> Remove duplicate sentence

- en/plugins.rst
The previous names were not totally clear.
Refs cakephp/cakephp#11910
Refs #5338
> Improve naming.

- en/controllers/request-response.rst
Fixes https://github.com/cakephp/cakephp/issues/12026
> Document how to get all request params at once

- en/appendices/3-7-migration-guide.rst
> Document View::$request/$reponse deprecation.

- en/core-libraries/email.rst
- en/development/testing.rst
For https://github.com/cakephp/cakephp/pull/11983
> Testing email documentation

- en/console-and-shells/input-output.rst
ask doesn't allow options, in that case askCoice should be used.
> rename ConsoleIo::ask to ConsoleIo::askChoice

- en/development/testing.rst
refs: https://github.com/cakephp/cakephp/pull/12064
> Added assertResponseNotEquals to assertion list

- en/contributing/cakephp-coding-conventions.rst
This was missing, but can be valuable to know.
Feel free to propose more useful examples if you got ideas.
> Add note about bail early principle.

- en/console-and-shells/commands.rst
> Add shortage of `use` clause

- en/console-and-shells/commands.rst
- en/development/testing.rst
Following https://github.com/cakephp/cakephp/pull/12072
> Updated documentation to use new test traits

- en/core-libraries/validation.rst
- en/orm/validation.rst
Adds information on how validation and application rules can return dynamic error messages.
Needs translations.
> Document dynamic validation/rule error messages.

- en/core-libraries/form.rst
> Use withData() instead of data()

- ja/contents.rst
- ja/controllers/middleware.rst
- ja/development/application.rst
> [ja] translate application.rst

- ja/development/configuration.rst
"Chrome Frame" is [Chrome Frame](http://www.chromium.org/developers/how-tos/chrome-frame-getting-started)
> [ja][2.x]fix configuration.rst

- en/appendices/3-7-migration-guide.rst
- en/views/helpers/form.rst
Refs: https://github.com/cakephp/cakephp/pull/11837
>  Added documentation for autoSetCustomValidity FormHelper option

- en/appendices/3-7-migration-guide.rst
> List deprecations/removals of helper properties.

- en/core-libraries/form.rst
Minor correction of a typo error.
> Correction of a typo error.

- fr/installation.rst
Remove some english parts that shouldn't be here.
Correct lot of sentences that didn't have a lot of meaning for French speakers.
Fix some code block that didn't match English (.htaccess for eg).
See changes for others
> [FR] Lot of changes in Installation page

- en/views/helpers/paginator.rst
Also includes a link to the `sortWhitelist` docs.
> Added note to use sortWhitelist for associated columns.

- en/core-libraries/caching.rst
Refs https://github.com/cakephp/docs/pull/5817#issuecomment-413041669
> fix explanation about CacheEngine::write()

- en/console-and-shells/commands.rst
- en/console-and-shells/option-parsers.rst
- ja/console-and-shells/commands.rst
- ja/console-and-shells/option-parsers.rst
As per https://github.com/cakephp/cakephp/blob/master/src/Console/Command.php#L133
> Fix visbility of commands.

- en/development/configuration.rst
Pull request is: https://github.com/cakephp/app/pull/625
This allows the user to define the Assets' cache time headers.
> Adding documentation to support the Accepted pull request I submitted.

- fr/core-libraries/events.rst
Quelques corrections mineures et ajout d'une phrase qui se trouvait dans le manuel en VO.
> Correction sur la traduction

- fr/core-libraries/components/access-control-lists.rst
J'ai aussi corrigé quelques petites erreurs (Mamie au lieu de Mamy, diplomatie au lieu de diplomacie, etc.) Il y avait aussi un tableau en VO qui traînait dans le code, je ne sais pas pourquoi...
> Un tableau n'était pas traduit

- en/development/testing.rst
> Update info regardign phpunit.

- en/console-and-shells/plugin-shell.rst
- en/development/testing.rst
- en/plugins.rst
Found some smaller issues. Now fixed.
> Some minor updates & improvements

- en/appendices/3-7-migration-guide.rst
- en/console-and-shells/commands.rst
- en/development/testing.rst
- en/elasticsearch.rst
> CamelCased fixture names.

- en/controllers/request-response.rst
see https://github.com/cakephp/docs/issues/5847
> updated deprecated code

- en/development/routing.rst
> Add warning about caching and filters.

- fr/models/data-validation.rst
- fr/tutorials-and-examples/simple-acl-controlled-application/simple-acl-controlled-application.rst
> Same fixes than #5854 in french

- en/core-libraries/form.rst
Replaces https://github.com/cakephp/docs/pull/5861
> Replaces https://github.com/cakephp/docs/pull/5861

- en/tutorials-and-examples/cms/tags-and-users.rst
Creating the View section code has missing </span> tag
> Added closing span tag on Creating the View code

- en/console-and-shells/input-output.rst
- en/controllers/components/pagination.rst
- en/views/helpers/paginator.rst
Several links were broken and I fixed it.
> [en] Fix links

- en/models/retrieving-your-data.rst
- Improved description of having option
- Add inline code markup
> [en]2.x improve retrieving-your-data

- en/appendices/3-7-migration-guide.rst
- en/core-libraries/validation.rst
- en/orm/validation.rst
- en/tutorials-and-examples/blog/part-three.rst
Update docs for cakephp/cakephp#12486
cc @chinpei215
> Update docs for cakephp/cakephp#12486

- en/appendices/4-0-migration-guide.rst
- en/development/routing.rst
- en/plugins.rst
Refs cakephp/cakephp#12735.
I also organized the "Breaking Changes" list into groups based on package/namespace for better readability.
> Add info about router's default inflection changes.

- en/controllers/middleware.rst
> [en] CsrfProtectionMiddleware documentation scoped vs. application-wide

- en/appendices/3-7-migration-guide.rst
I felt this was worth mentioning :)
> Added notes on a couple of new features

- en/orm/behaviors/translate.rst
Add info about the two different strategies available. Refs cakephp/cakephp#12113.
> Update Translate behavior page.

- en/orm/retrieving-data-and-resultsets.rst
> word error

- en/appendices/4-0-migration-guide.rst
> Case sensitive method name matching

- en/orm/entities.rst
> Use magic properties instead of $_properties

- en/core-libraries/email.rst
Refs: https://github.com/cakephp/cakephp/pull/12865
If the above isn't merged, this can be closed.
> Update requirements for using EmailTrait

- fr/console-and-shells/input-output.rst
Thanks @Mydexios for helping me in this translation!
> [FR] input-output.rst translation

- en/appendices/3-6-migration-guide.rst
- en/development/testing.rst
- en/plugins.rst
Stab at adding few missing infos
- https://github.com/cakephp/cakephp/issues/12727
- routing change - migration guide update necessary
Please help to enrich the part about plugin testing.
I feel like - also from the feedback of others in the chat - that we have some infos missing here.
> 3.0 plugin testing

- ja/development/testing.rst
fix testing.rst to use IntegrationTestTrait in controller integrating test
refs: https://github.com/cakephp/docs/pull/5748/files#diff-ebf92610d3d3b626d67181a6bf1196c2
> [ja]translate and fix testing.rst to use IntegrationTestTrait in controller integrating test

- en/controllers/components/security.rst
It removes the duplicate code line.
> Remove duplicate code

- ja/development/testing.rst
- ja/elasticsearch.rst
fix testing.rst with deprecated fix (snake case fixture and eventManager)
refs:
- https://github.com/cakephp/docs/pull/5845/files
- https://github.com/cakephp/docs/pull/5921/files
> [ja] 3.0 fix testing.rst with deprecated fix (snake case fixture and eventManager)

- ja/installation.rst
> [ja] remove mcrypt from requirements

- ja/development/testing.rst
add following methods.
- assertRedirectNotContains
- assertHeaderNotContains
refs: https://book.cakephp.org/3.0/en/appendices/3-7-migration-guide.html#testsuite
> [ja] Add translation to  testing.rst to add test suite methods

- en/appendices/3-7-migration-guide.rst
> fix typo in 3-7-migration guide

- en/core-libraries/validation.rst
2nd argument of allowEmptyString() is $when not $message.
> Fix example code.

- en/appendices/3-7-migration-guide.rst
> fix typo in 3-7-migration-guides

- ja/development/routing.rst
Add Japanese translate at Router::addUrlFilter Warning Section
> Add Japanese translate at Router::addUrlFilter Warning Section

- en/orm/associations.rst
* Recommend finders over conditions.
* Explain that association finders are used for delete/update.
Refs cakephp/cakephp#12929
> 4.x - Update association docs for finder changes

- en/appendices/4-0-migration-guide.rst
- en/views/helpers/form.rst
> Add info regarding native datetime inputs.

- ja/orm/saving-data.rst
Japanese translation for #5971
> [ja] add translation at saving-data.rst to The fieldList option deprecated

- ja/debug-kit.rst
Add translation for `DebugKit.safeTld` option.
refs https://book.cakephp.org/3.0/en/debug-kit.html#configuration
> [ja] add translation at debug-kit.rst to The DebugKit.safeTld option

- en/development/configuration.rst
- en/installation.rst
- en/intro/cakephp-folder-structure.rst
- en/intro/conventions.rst
* Use fewer words
* Don't use simple & easy.
> Make installation docs simpler

- es/development/debugging.rst
Translating debugging.rst to spanish
> Translation of debugging.rst to spanish

- en/appendices/3-8-migration-guide.rst
> Update 3.8 migration guide.

- en/appendices/3-8-migration-guide.rst
Document https://github.com/cakephp/cakephp/pull/13100
> 3.next Add missing autoload for $modelClass

- en/views/json-and-xml-views.rst
https://github.com/cakephp/app/blob/3.5.0/src/Controller/AppController.php
https://github.com/cakephp/app/blob/3.5.1/src/Controller/AppController.php
> Correct outdated statement about _seralize

- ja/orm/saving-data.rst
Update example code.
https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types
> [ja] update example code in saving-data.rst

- ja/appendices/3-6-migration-guide.rst
> [ja] Update transration at 3-6-migration-guide.rst

- en/appendices/4-0-migration-guide.rst
> Update info about BoolType marshalling

- en/controllers/components/authentication.rst
- ja/contents.rst
- ja/controllers/components/authentication.rst
- add AuthN/Z plugin in contents.rst
- fix authentication chapter title
- https://github.com/cakephp/docs/pull/6032/files
>  add AuthN/Z plugin in contents.rst and fix authentication chapter title

- en/appendices/4-0-migration-guide.rst
> Add info about layout.

- en/views/helpers/form.rst
Hopefully makes it easier to grasp the various options available.
> Make date control input example more clear

- en/core-libraries/collections.rst
The rather helpful firstMatch method was missing from the list of methods section
> Added firstMatch to list of methods

- ja/contents.rst
- ja/controllers/components/authentication.rst
follow https://github.com/cakephp/docs/pull/6036
> [ja] make AuthComponent as deprecated

- en/appendices/4-0-migration-guide.rst
> Add info regarding JSON encoding of date objects.

- ja/core-libraries/collections.rst
- ja/views/helpers/form.rst
Patches to follow these PR changes.
- https://github.com/cakephp/docs/pull/6043/files
- https://github.com/cakephp/docs/pull/6042/files
> [ja] add comment to date control and firstMatch to list of methods

- fr/index.rst
> Fix php version

- ja/development/sessions.rst
follow PR changes https://github.com/cakephp/docs/pull/6052
> [ja] change Network/Session to Http/Session in sessions.rst

- en/tutorials-and-examples/cms/tags-and-users.rst
Updated config/routes.php code, tested and working, for 3.x version
> Updated config/routes.php code, tested and working

- en/orm/database-basics.rst
- fr/orm/database-basics.rst
- ja/orm/database-basics.rst
- pt/orm/database-basics.rst
- tl/orm/database-basics.rst
Fixed the code example for runtime auto quoting.
> Fixed code example for enabling automatic identifier quoting at runtime

- en/development/application.rst
Additions to "Adding the new HTTP Stack to an Existing Application", as per #13211
> Ticket 13211

- en/orm.rst
- fr/console-and-shells.rst
The other pull request was sloppy.  This is smaller and cleaner.
> Fixed unterminated string literals in code examples

- en/appendices/4-0-migration-guide.rst
- en/controllers/middleware.rst
> Add docs for CspMiddleware

- en/appendices/4-0-migration-guide.rst
> Add info about ObjectRegistry changes.

- en/orm/database-basics.rst
- en/tutorials-and-examples/cms/database.rst
- fr/orm/database-basics.rst
- fr/tutorials-and-examples/cms/database.rst
- ja/orm/database-basics.rst
- ja/tutorials-and-examples/cms/database.rst
- kr/tutorials-and-examples/cms/database.rst
- pt/orm/database-basics.rst
- tl/orm/database-basics.rst
- tl/tutorials-and-examples/cms/database.rst
- zh/tutorials-and-examples/cms/database.rst
Its a secret, not sekret.
Especially in german it can be misunderstood as "Sekret" (secretion)
> Replaced sekret with secret

- en/appendices/4-0-migration-guide.rst
- en/orm/deleting-data.rst
- en/orm/saving-data.rst
Migration notes for
- https://github.com/cakephp/cakephp/pull/13212
- https://github.com/cakephp/cakephp/pull/13213
> Add table methods.

- en/appendices/4-0-migration-guide.rst
- en/controllers/request-response.rst
- fr/controllers/request-response.rst
- ja/controllers/request-response.rst
- ru/controllers/request-response.rst
- tl/controllers/request-response.rst
Docs for https://github.com/cakephp/cakephp/pull/13278
> Fix up referer() security adjustment.

- en/appendices/4-0-migration-guide.rst
Refs cakephp/cakephp#13276,  cakephp/cakephp#13287.
> Add info about logger and cacher changes to database.

- en/appendices/4-0-migration-guide.rst
- en/development/errors.rst
- en/development/rest.rst
- en/development/testing.rst
- en/tutorials-and-examples/blog/part-three.rst
- en/tutorials-and-examples/bookmarks/part-two.rst
- en/views/json-and-xml-views.rst
> Document view options changes

- en/appendices/4-0-migration-guide.rst
- en/development/errors.rst
> Add info about error handler updates.

- en/appendices/4-0-migration-guide.rst
For https://github.com/cakephp/cakephp/pull/13325
> Update depr docs.

- en/controllers/request-response.rst
> Improve docs for request::is()

- es/tutorials-and-examples/cms/installation.rst
added installation.rst in docs/es/tutorials-and-examples/cms
> Added installation.rst

- en/controllers/components/authentication.rst
Just replacing a gender specific pronoun
> Replace gender pronoun

- en/core-libraries/httpclient.rst
> Add adapter option docs.

- en/orm/saving-data.rst
> Add docs for findOrCreate()

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
noticed these needed to be updated in the doc source examples
> Update usage of newEntity to newEmptyEntity

- en/appendices/3-9-migration-guide.rst
For https://github.com/cakephp/cakephp/pull/13494
> Document manyOrFail() backports.

- en/appendices/4-0-migration-guide.rst
Refs https://github.com/cakephp/cakephp/pull/13065
> Document newEmptyEntity() addition.

- en/development/rest.rst
Protect users from incorrect HTTP method usage should they cook up their own routes.
Fixes #6158
> Include request method checks in REST example

- en/appendices/4-0-migration-guide.rst
> Add info about cakephp/cakephp#13502

- en/appendices.rst
> Add shim plugin info.

- en/appendices/4-0-migration-guide.rst
- en/views/helpers/form.rst
> Add info about change in FormHelper::create()'s context inference.

- en/appendices/4-0-migration-guide.rst
- en/core-libraries/email.rst
> Update info about mailer.

- en/core-libraries/email.rst
> Revert some Mailers back to Emails

- en/controllers/request-response.rst
- en/development/configuration.rst
> Add docs for the file upload objects in request data feature.

- en/appendices/4-0-migration-guide.rst
- en/core-libraries/app.rst
> Add info about App::path() changes.

- en/appendices/4-0-migration-guide.rst
- en/development/routing.rst
> Add docs for Asset class

- en/orm/retrieving-data-and-resultsets.rst
> Remove unnnecessary examples of TableRegistry usage.

- en/appendices/4-0-migration-guide.rst
> Document updates to Router methods.

- en/appendices/4-0-migration-guide.rst
- en/controllers/components/pagination.rst
- en/views/cells.rst
> Document changes to request params.

- en/controllers/request-response.rst
- fr/controllers/request-response.rst
- ja/controllers/request-response.rst
- ru/controllers/request-response.rst
- tl/controllers/request-response.rst
See https://github.com/cakephp/cakephp/pull/13678
> 4.x: Server request built-in detector 'requested' was removed

- en/development/configuration.rst
Update the configuration file documentation and co-locate the environment variable docs closer to the configuration file docs as they are related.
Refs cakephp/app#713
cc @inoas
> Update configuration docs for recent file changes.

- en/orm/associations.rst
This literally just fixes the capitalization of the sentences in Associations options.
I have some english and phrasing suggestions, but wanted to make this specific fix before those in case they are rejected.
> Fixed capitalization of first word in sentences

- en/orm/associations.rst
This follows the changes made to hasOne in https://github.com/cakephp/docs/pull/6209.
I stopped short of trying to adjust everything, this is just a high-level pass to sync up some of the options.
> Updated phrasing of belongsTo, hasMany and belongsToMany assocations

- en/appendices/4-0-migration-guide.rst
- en/controllers/components/security.rst
- en/controllers/middleware.rst
Remove outdated information for SecurityComponent as well.
> Update docs for HttpsEnforcerMiddleware

- en/appendices/4-0-migration-guide.rst
Refs cakephp/app#717, cakephp/cakephp#13672.
> Add info about Router::fullBaseUrl() in bootstrap.

- en/appendices/4-0-migration-guide.rst
- en/controllers/components/form-protection.rst
- en/security.rst
> Add info about new FormProtectionComponent.

- en/orm/query-builder.rst
This also touches https://github.com/cakephp/docs/pull/6204
I moved the deprecation notice for `orWhere()` up so it's not out of context and clarified that it is `Query::where()` replacing `Query::orWhere()` for anyone who wants to look up the API docs.
I also tried to clarify some of the steps showing `QueryExpression` combinators and conditions.  Hopefully this provides more consistent phrasing and terms in a few places.  I use `QueryExpression` explicitly and specified the type of the callback arguments so no one is confused when looking up the API.  I pulled `and_()` and `or_()` out so they stand out more.
I updated the line breaks of a few SQL examples.
> Clarified deprecation of Query::orWhere()

- en/development/configuration.rst
Started a new app and tried to set database config via `config/.env`. This didn't work and the book wasn't helpful diagnosing the issue.
> dotenv support is opt in.

- en/appendices/4-0-migration-guide.rst
Clarify that the change is regarding the exception.
> Reword migration note about comparison with null.

- README.md
- kr/installation.rst
Following up on link change as promised.
> Updated links from book.cakephp.org/3.0/ to book.cakephp.org/3/

- fr/index.rst
> Fix French epub file link

- en/appendices/4-0-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/13849
> Inflector change

- en/appendices/4-0-migration-guide.rst
- en/orm/database-basics.rst
- en/views/helpers/form.rst
Doc changes for https://github.com/cakephp/cakephp/pull/13864
> 4.x - Added migration notes for new fractional db types

- en/appendices/4-0-migration-guide.rst
- en/controllers/components/authentication.rst
- en/controllers/components/form-protection.rst
- en/controllers/components/security.rst
- en/controllers/middleware.rst
- en/development/errors.rst
- en/development/routing.rst
- en/intro/conventions.rst
- en/plugins.rst
> Add docs for cakephp/cakephp#13868

- en/appendices/4-0-migration-guide.rst
- en/appendices/4-0-upgrade-guide.rst
- en/contents.rst
> Start upgrade tool docs.

- en/appendices/4-0-migration-guide.rst
I also merged the two copies of ORM under New Features.
> Added 4.0 migration notes for Date/FrozenDate time zone support

- pt/development/application.rst
- pt/development/errors.rst
Added new file in _development/application.rst_, exist in folder "en/", but don't "pt/"
> Created application.rst in portuguese

- pt/development/application.rst
Simple corrections in portuguese language and list items
> Fixes in application.rst

- fr/console-and-shells/commands.rst
- fr/console-and-shells/input-output.rst
- fr/console-and-shells/option-parsers.rst
- fr/console-and-shells/shells.rst
- fr/development/application.rst
I just started the translations of missing fr files. If someone @cakephp/docs-fr wants to continue or to review, don't hesitate
> WIP add missing fr files and translate commands.rst

- en/appendices/4-0-migration-guide.rst
- en/core-libraries/app.rst
Docs for https://github.com/cakephp/cakephp/pull/13898
> 4.x class path

- en/development/testing.rst
Ref.: https://github.com/cakephp/cakephp/pull/13586
> Document alternative way to define fixtures

- en/appendices/4-0-migration-guide.rst
- en/views/helpers/html.rst
> Document removal of HtmlHelper::docType()

- en/appendices/4-0-migration-guide.rst
Migration notes for https://github.com/cakephp/cakephp/pull/13914
> 4.x - Added migration notes for sqlserver fractional datetime types

- en/appendices/3-9-migration-guide.rst
- en/core-libraries/validation.rst
- en/orm/validation.rst
- fr/core-libraries/validation.rst
- fr/orm/validation.rst
- ja/core-libraries/validation.rst
- ja/orm/validation.rst
- tl/core-libraries/validation.rst
- tl/orm/validation.rst
Migration notes for https://github.com/cakephp/cakephp/pull/13953
> 3.9 - Added migration notes for Validator::validate()

- en/installation.rst
Refs https://github.com/cakephp/cakephp/pull/13969
> Some 2.x EOL notes/warnings.

- en/appendices/4-0-migration-guide.rst
Fixes https://github.com/cakephp/docs/issues/6295.
> 4.x - Fixed upgrade guide link

- en/controllers/components.rst
- en/controllers/components/authentication.rst
- en/controllers/components/request-handling.rst
- en/core-libraries/email.rst
- en/core-libraries/form.rst
- en/intro.rst
- en/orm/entities.rst
- en/orm/saving-data.rst
- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/blog/part-three.rst
- en/tutorials-and-examples/blog/part-two.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/views/cells.rst
- en/views/helpers.rst
Resolves https://github.com/cakephp/docs/issues/6301
> 4.x: Fix up newEmptyEntity() usage.

- en/appendices/4-0-migration-guide.rst
- en/orm/database-basics.rst
Migration notes for https://github.com/cakephp/cakephp/pull/13943
> 4.x - Added migration notes for DateTimeTimezoneType

- en/core-libraries/email.rst
Closes https://github.com/cakephp/docs/issues/3882.
> Updated example of attaching custom Mailer with event handler to model

- en/console-and-shells/option-parsers.rst
Fix incorrect option description indents which broke styling of the document
> Fix indents

- en/core-libraries/validation.rst
> Add link and better details on the context parameter.

- en/appendices/4-0-migration-guide.rst
https://github.com/cakephp/cakephp/pull/13943
> 4.x - Added migration notes for DateTimeType::setKeepDatabaseTimezone()

- en/appendices/4-0-upgrade-guide.rst
> Add warning about order of operations.

- en/views/cells.rst
Removed extra parenthesis in Pagination example
> Extra parenthesis in example

- en/orm/behaviors/translate.rst
> Add example for setting default locale.

- en/core-libraries/file-folder.rst
> Add info about alternatives to File and Folder

- en/appendices/4-0-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14059
> 4.x - Removed sqlserver datetime to datetimefractional mapping

- en/contributing/tickets.rst
Added the slack link and the discourse link for users to find community support
> Updated community support links on Reporting Bugs

- en/core-libraries/email.rst
> Don't troll meth users.

- en/orm/retrieving-data-and-resultsets.rst
https://github.com/cakephp/docs/issues/6303
> 3.x - Fixed use of Query::distinct()

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14081
> 4.1 - Added migration notes for schema dialect class moves

- en/contents.rst
- es/contents.rst
- ja/contents.rst
> Update links to plugins.

- en/appendices/4-0-migration-guide.rst
- en/core-libraries/logging.rst
> Update docs to match code.

- ja/tutorials-and-examples/cms/database.rst
follow this changes https://github.com/cakephp/docs/pull/6386/files
```
If you have **config/app_local.php** in your app folder,
it overrides app.php configuration.
```
> follow ja/database.rst to PR#6386

- en/appendices/4-0-migration-guide.rst
- en/development/sessions.rst
> Document changes regarding "SameSite" attribute for session cookies.

- en/appendices/4-0-migration-guide.rst
> Add notes for #6408

- en/core-libraries/email.rst
- en/development/configuration.rst
Instead referenec the configuration concepts and how the application
skeleton works.
> Don't reference outdated configuration files.

- en/core-libraries/email.rst
> Expand Mailer testing section

- en/appendices/4-0-migration-guide.rst
> Add info about auto quoting change to migration guide

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14198
> 4.1 - Migration notes for mysql 8 changes

- en/controllers.rst
- en/controllers/components.rst
* Add more information on doing redirects in event handlers
* Simplify examples and reduce verbosity.
Refs cakephp/cakephp#11197
> Update redirect docs to be clearer

- en/controllers/request-response.rst
> Update info regarding ServerRequest::getData()

- en/core-libraries/form.rst
Fixed for compatibile to Cake4
> Typing updated

- en/controllers.rst
> Update Setting view options code in controllers.rst

- ja/controllers.rst
> [ja] Update setup view options code

- en/orm/validation.rst
Updated from deprecated errors() method to getters and setters
> Updated to correct error methods

- ja/controllers/middleware.rst
Added the following translations.
- Body Parser Middleware
- HTTPS Enforcer Middleware
> add ja docs of Middleware

- en/tutorials-and-examples/cms/articles-controller.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/authorization.rst
- en/tutorials-and-examples/cms/database.rst
- en/tutorials-and-examples/cms/tags-and-users.rst
I went through the second round of feedback in [this discourse thread](https://discourse.cakephp.org/t/issues-with-cms-tutorial/7180/5) and updated the docs.
> More CMS tutorial fixes

- en/appendices/4-1-migration-guide.rst
migration note for https://github.com/cakephp/cakephp/pull/14251
> 4.next: Add EntityInterface::getAccessible()

- ja/core-libraries/httpclient.rst
Replace old method with new method.
> Fix: Japanese doc

- en/appendices/4-0-migration-guide.rst
> Fix config name

- en/core-libraries/email.rst
> Update email.rst for Issue #6463

- en/appendices/4-1-migration-guide.rst
Refs https://github.com/cakephp/cakephp/pull/14284
> ServerRequest::input() is deprecated

- fr/The-Manual/Core-Behaviors/Containable.rst
> Fix: French typo

- pt/The-Manual/Developing-with-CakePHP/Behaviors.rst
> Fix: Portuguese typo

- ja/core-libraries/time.rst
> Fix: Japanese typo

- en/contents.rst
- en/standalone-packages.rst
The fact that we have various standalone packages is very poorly advertised.
I have list out the ones we provide on this page with a single line intro picked up from repo titles/readmes.
Hoping someone can complete this by adding intro, updating packages descriptions if necessary and linking the page in menu/TOC.
> Start page providing info about standalone packages.

- ja/console-and-shells/commands.rst
I noticed when creating a batch with CakePHP4.0.
> [ja] 4.x Return type declarations

- .dockerignore
- Dockerfile
- deploy.Dockerfile
- scripts/populate_search_index.php
https://github.com/cakephp/docs/issues/6466
This also updates the docker build to include php packages and exclude any local temporary files.
> Added file exclusions to elastisearch index generation.

- en/development/routing.rst
See https://github.com/cakephp/cakephp/blob/4.0.0/src/Routing/Route/Route.php#L420 for more details
> docs: fix class route should extend and failure response

- ja/tutorials-and-examples/cms/authentication.rst
Update japanese authentication.rst
> Update ja authentication.rst

- en/core-libraries/validation.rst
https://book.cakephp.org/4/en/core-libraries/validation.html
> [4.x] five -> six

- es/tutorials-and-examples/blog-auth-example/auth.rst
- es/tutorials-and-examples/blog/part-three.rst
- es/tutorials-and-examples/blog/part-two.rst
- fr/tutorials-and-examples/blog-auth-example/auth.rst
- fr/tutorials-and-examples/blog/part-three.rst
- fr/tutorials-and-examples/blog/part-two.rst
- fr/tutorials-and-examples/cms/articles-controller.rst
- fr/tutorials-and-examples/cms/authentication.rst
- fr/tutorials-and-examples/cms/tags-and-users.rst
- ja/tutorials-and-examples/blog-auth-example/auth.rst
- ja/tutorials-and-examples/blog/part-three.rst
- ja/tutorials-and-examples/blog/part-two.rst
- ja/tutorials-and-examples/cms/articles-controller.rst
- ja/tutorials-and-examples/cms/tags-and-users.rst
- pt/tutorials-and-examples/blog-auth-example/auth.rst
- pt/tutorials-and-examples/blog/part-three.rst
- pt/tutorials-and-examples/blog/part-two.rst
- ru/tutorials-and-examples/blog-auth-example/auth.rst
- ru/tutorials-and-examples/blog/part-three.rst
- ru/tutorials-and-examples/blog/part-two.rst
- tl/elasticsearch.rst
- tl/tutorials-and-examples/blog-auth-example/auth.rst
- tl/tutorials-and-examples/blog/part-three.rst
- tl/tutorials-and-examples/blog/part-two.rst
- tl/tutorials-and-examples/cms/articles-controller.rst
- tl/tutorials-and-examples/cms/authentication.rst
- tl/tutorials-and-examples/cms/tags-and-users.rst
- zh/tutorials-and-examples/cms/articles-controller.rst
- zh/tutorials-and-examples/cms/authentication.rst
- zh/tutorials-and-examples/cms/tags-and-users.rst
fix Too few arguments to function Cake\ORM\Table::newEntity(), 0 passed in /var/www/html/src/Controller/ArticlesController.php....
Thank you.
> Added the ability to add articles

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14376
> 4.1 - Add deprecation notes for DateTimeType::setTimezone()

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14377
> 4.1 - Add change notes for BelongsToMany respecting bindingKey

- ja/development/rest.rst
fix code
https://book.cakephp.org/4/en/development/rest.html#the-simple-setup
> [ja][4.x] fix RestCode

- en/tutorials-and-examples/cms/authentication.rst
This is left over from a change in this commit: 2f2cbf365c14e90aed38282f651b75de2381a844
> CMS Tutorial: Remove Partial Sentence

- en/tutorials-and-examples/cms/articles-controller.rst
Remove EventInterface type from beforeSave method example
Fixes #6549
> Fix Typing Error

- en/tutorials-and-examples/blog-auth-example/auth.rst
- en/tutorials-and-examples/cms/authentication.rst
- en/tutorials-and-examples/cms/authorization.rst
- ja/tutorials-and-examples/cms/authentication.rst
Also update the formatting around the `login` method to match other method formatting in tutorial.
> CMS Tutorial: Minor Grammar and Code Changes

- en/controllers/request-response.rst
Follow https://github.com/cakephp/cakephp/pull/14395
> Fix up missing docs for getParsedBody().

- en/controllers/request-response.rst
Same problem as https://github.com/cakephp/docs/pull/6555 .
> [4.x] fix: Zend -> Laminas

- ja/controllers/components.rst
https://book.cakephp.org/4/en/controllers/components.html
https://book.cakephp.org/4/ja/controllers/components.html
> [ja][4.x] controllers/components.rst

- en/orm/query-builder.rst
https://book.cakephp.org/4/en/orm/query-builder.html
Confirmation of deletion during translation
https://github.com/cakephp/docs/pull/6559
> [4.x] delete deprecated:: 3.5.0

- ja/controllers/request-response.rst
https://book.cakephp.org/4/en/controllers/request-response.html
https://book.cakephp.org/4/ja/controllers/request-response.html
> [ja][4.x] controllers/request-response.rst

- ja/core-libraries/time.rst
https://book.cakephp.org/4/en/core-libraries/time.html
https://book.cakephp.org/4/ja/core-libraries/time.html
> [ja][4.x] core-libraries/time.rst

- en/development/configuration.rst
It took me a few tries to figure this out, hopefully helps someone save time.
> Update configuration.rst - clarification

- ja/controllers/middleware.rst
https://book.cakephp.org/4/en/controllers/middleware.html
https://book.cakephp.org/4/ja/controllers/middleware.html
> [ja][4.x] controllers/middleware.rst 

- ja/views/helpers/form.rst
> [ja][3.x] Update form.rst

- en/core-libraries/inflector.rst
> Remove ref to now nonexistent method

- en/appendices/4-1-migration-guide.rst
- en/views/helpers/html.rst
- en/views/helpers/url.rst
Docs for https://github.com/cakephp/cakephp/pull/14474
> Docs for *fromPath() methods.

- en/installation.rst
Added configuration example for URL Rewrite using Lighttpd web server.
> Add Lighttpd configuration for URL Rewrite

- en/appendices/3-9-migration-guide.rst
- en/console-and-shells/commands.rst
https://github.com/cakephp/cakephp/pull/14478
> 3.9 - Notes for Command::defaultName()

- en/installation.rst
Added configuration details for another NGINX app server, Unit, in an adjacent section.
> Added Unit app server config to installation.rst

- en/development/routing.rst
- en/views.rst
- en/views/helpers/url.rst
Refs https://github.com/cakephp/docs/pull/6592
we should still also add some ` _path` documentation for the helpers.
> Some docs about pathUrl().

- en/appendices/3-9-migration-guide.rst
- en/plugins.rst
https://github.com/cakephp/cakephp/pull/14493
> 3.9 - Added notes for addOptionalPlugin

- en/controllers/components/pagination.rst
Word changes (service => serve)
Added missing set call on code snippet
> Small fixes

- en/development/routing.rst
> Attempt to clarify routing parameters

- ja/controllers/components/pagination.rst
https://book.cakephp.org/4/en/controllers/components/pagination.html
https://book.cakephp.org/4/ja/controllers/components/pagination.html
> [ja][4.x] orm/controllers/components/pagination.rst

- en/contents.rst
- en/core-libraries/app.rst
- en/core-libraries/plugin.rst
Resolves https://github.com/cakephp/docs/issues/6604
> Resolve Plugin class docs.

- en/appendices/3-9-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14508
> 3.9 - Added notes on replacing abandoned zend packages

- en/appendices/4-0-upgrade-guide.rst
- en/appendices/4-1-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/14497
> Add urlArray() migration note.

- ja/core-libraries/logging.rst
https://book.cakephp.org/4/en/core-libraries/logging.html
https://book.cakephp.org/4/ja/core-libraries/logging.html
> [ja][4.x] core-libraries/logging.rst

- en/development/testing.rst
I noticed during Japanese translation.
#6618
I have matched the following.
https://github.com/cakephp/app/blob/master/composer.json#L19
> phpunit/phpunit:"^8.5"

- ja/development/testing.rst
https://book.cakephp.org/4/en/development/testing.html
https://book.cakephp.org/4/ja/development/testing.html
> [ja][4.x] development/testing

- ja/orm/behaviors/timestamp.rst
https://book.cakephp.org/4/en/orm/behaviors/timestamp.html
https://book.cakephp.org/4/ja/orm/behaviors/timestamp.html
> [ja][4.x] orm/behaviors/timestamp.rst

- en/core-libraries/validation.rst
> Fix inaccurate info regarding entity data validation.

- en/appendices/4-1-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14525
> Added notes for #14525

- en/appendices/4-1-migration-guide.rst
Docs for https://github.com/cakephp/cakephp/pull/14576
> Interactive false for Commands.

- ja/tutorials-and-examples/blog-auth-example/auth.rst
https://book.cakephp.org/4/en/tutorials-and-examples/blog-auth-example/auth.html
https://book.cakephp.org/4/ja/tutorials-and-examples/blog-auth-example/auth.html
> [ja][4.x] tutorials-and-examples/blog-auth-example/auth.rst

- en/views/helpers/paginator.rst
> Add an example for multiple pagination URL parameters.

- en/core-libraries/internationalization-and-localization.rst
Maybe it was forgotten to remove DispatcherFactory while upgrading the cookbook to CakePHP4.x
Additionally I added a line to make clear how to accept any locale header value.
> removed obsolet DispatcherFactory

- en/orm/query-builder.rst
Are there other methods/usage that we should be including? I don't think we should have exhaustive docs on windowing functions but a cursory introduction/API overview is important to have.
cc @othercorey
> 4.1 - Start docs for windowing functions.

- en/development/configuration.rst
> fix typo on configuration doc

- en/appendices/4-1-migration-guide.rst
- en/development/testing.rst
Docs for https://github.com/cakephp/cakephp/pull/14617
> Docs for TestCase::addFixture().

- ja/tutorials-and-examples/cms/articles-controller.rst
Add some typehints, and update validation method.
> [ja] Update  tutorials code

- en/appendices/4-1-migration-guide.rst
- en/development/sessions.rst
Docs for https://github.com/cakephp/cakephp/pull/14647
The wording might not yet be perfect, help welcome
> Docs for Session::readOrFail().

- en/appendices/4-0-upgrade-guide.rst
I updated some wording and layout in the intro.
> Update upgrade tool branch for 4.0 upgrade

- en/console-commands/routes.rst
Resolving typo/unclear sentence for Testing URL Generation
> 4.x console commands routes typo

- en/core-libraries/inflector.rst
Alternative to https://github.com/cakephp/docs/pull/6658
As per changes to PR in https://github.com/cakephp/cakephp/pull/14667
> Docs of CamelCase plural/singular limitations.

- en/controllers/components/pagination.rst
- en/development/routing.rst
- en/orm/entities.rst
- en/orm/saving-data.rst
- en/tutorials-and-examples/bookmarks/part-two.rst
There are better words to use than whitelist in these contexts.
> Reduce usage of whitelist

- en/development/sessions.rst
> Update docs for accessing request instance

- en/contents.rst
The auth packages can be used standalone too.
> Update contents list.

- en/appendices/4-0-upgrade-guide.rst
- en/appendices/4-1-migration-guide.rst
Add information to both the upgrade guide and the upgrade tool guide to show how to help with the 4.0 -> 4.1 upgrade.
> Add information on how to use the upgrade tool for 4.1

- en/core-libraries/validation.rst
Refs https://github.com/cakephp/cakephp/issues/14703
> Don't promote hackish usage of validation providers.

- en/appendices/4-2-migration-guide.rst
- en/orm/query-builder.rst
> Add docs for cakephp/cakephp#14764

- en/console-and-shells/commands.rst
I just tripped over this and thought, it would be good to add  note.
> Add note about assertiing text output

- ja/plugins.rst
https://book.cakephp.org/4/en/plugins.html
https://book.cakephp.org/4/ja/plugins.html
> [ja][4.x] plugins.rst

- ja/views/helpers.rst
https://book.cakephp.org/4/en/views/helpers.html
https://book.cakephp.org/4/ja/views/helpers.html
> [ja][4.x] views/helpers.rst

- en/appendices/4-2-migration-guide.rst
- en/controllers/middleware.rst
> Add SessionCsrfProtectionMiddleware documentation

- en/appendices/4-2-migration-guide.rst
https://github.com/cakephp/cakephp/pull/14842
> Migration notes for SqlServer client-side cursor

- en/installation.rst
This updates the supported databases to versions that are reasonably recent and testable.
> Update supported database versions

- en/appendices/4-2-migration-guide.rst
For https://github.com/cakephp/cakephp/pull/14858
> Add fixture cleanup notes.

- en/orm/saving-data.rst
refs discussion in chat today.
that info was missing and some people trip over this.
> Add note about existing UUID for saving.

- en/appendices/4-2-migration-guide.rst
- en/core-libraries/internationalization-and-localization.rst
> Add info about Aura.Intl dependency removal.

- en/appendices/cakephp-development-process.rst
I decided to make this page more about our release policies instead of contributing code/tickets as we have a separate section for that already.
> Update the development process docs

- ja/controllers/components/security.rst
https://book.cakephp.org/4/en/controllers/components/security.html
https://book.cakephp.org/4/ja/controllers/components/security.html
> [ja][4.x] controllers/components/security.rst

- ja/tutorials-and-examples/cms/tags-and-users.rst
https://book.cakephp.org/4/en/tutorials-and-examples/cms/tags-and-users.html
https://book.cakephp.org/4/ja/tutorials-and-examples/cms/tags-and-users.html
> [ja][4.x] tutorials-and-examples/cms/tags-and-users.rst

- en/tutorials-and-examples/cms/authentication.rst
Change "in you appcontroller" to "in your appcontroller".  Happened to catch this while reading the tutorial.
> minor typo

- en/views/themes.rst
> Update outdated info regarding theme asset loading

- en/views/themes.rst
> Reword statement about theme plugin loading.

- en/appendices/4-2-migration-guide.rst
Refs https://github.com/cakephp/cakephp/pull/14969
> Migration docs for Validation::time() restriction

- en/core-libraries/text.rst
- en/core-libraries/time.rst
- fr/core-libraries/text.rst
- fr/core-libraries/time.rst
- ja/core-libraries/text.rst
- ja/core-libraries/time.rst
- tl/core-libraries/text.rst
- tl/core-libraries/time.rst
The user guide and the API reference have been moved.
> 3.x - Update outdated/non-existent ICU project links.

- en/core-libraries/text.rst
- en/core-libraries/time.rst
- fr/core-libraries/text.rst
- fr/core-libraries/time.rst
- ja/core-libraries/text.rst
- ja/core-libraries/time.rst
- tl/core-libraries/text.rst
- tl/core-libraries/time.rst
The user guide and the API reference have been moved.
> 4.x - Update outdated ICU project links.

- pt/tutorials-and-examples/blog/part-two.rst
changing "localziado" for "localizado"
> Portuguese writing correction

- ja/core-libraries/email.rst
> Add translate (ja)

- en/contents.rst
- en/development/dependency-injection.rst
Get an outline of the headings in place so that content can be added.
> Start with the outline of the container docs.

- en/development/dependency-injection.rst
Not done, but this is a reviewable chunk :smile:
> 4.next - Start fililng in the container documentation.

- en/core-libraries/collections.rst
- fr/core-libraries/collections.rst
- ja/core-libraries/collections.rst
- pt/core-libraries/collections.rst
- tl/core-libraries/collections.rst
- zh/core-libraries/collections.rst
Refs https://github.com/cakephp/cakephp/pull/15005
> Updated Collection parameter names

- en/appendices/4-2-migration-guide.rst
- en/development/errors.rst
Refs https://github.com/cakephp/cakephp/pull/14998
> Migration notes for ExceptionRenderer HTTP code changes

- en/orm/associations.rst
Follow https://github.com/cakephp/docs/pull/6813
Not sure if we need this, but so far people seem to not know about this.
So maybe it doesn't hurt to clarify at this point.
> Note about entity prop.
